fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX::FXStream Class Reference
#include <FXStream.h>
Public Member Functions
FXStream (const FXObject *cont=NULL)
bool open (FXStreamDirection save_or_load, FXuval size=8192, FXuchar *data=NULL)
virtual bool flush ()
virtual bool close ()
FXuval getSpace () const
void setSpace (FXuval sp)
FXStreamStatus status () const
bool eof () const
void setError (FXStreamStatus err)
FXStreamDirection direction () const
const FXObject * container () const
FXlong position () const
virtual bool position (FXlong offset, FXWhence whence=FXFromStart)
void swapBytes (bool s)
bool swapBytes () const
void setBigEndian (bool big)
bool isBigEndian () const
FXStream & operator<< (const FXuchar &v)
FXStream & operator<< (const FXchar &v)
FXStream & operator<< (const FXushort &v)
FXStream & operator<< (const FXshort &v)
FXStream & operator<< (const FXuint &v)
FXStream & operator<< (const FXint &v)
FXStream & operator<< (const FXfloat &v)
FXStream & operator<< (const FXdouble &v)
FXStream & operator<< (const FXlong &v)
FXStream & operator<< (const FXulong &v)
FXStream & save (const FXuchar *p, FXuval n)
FXStream & save (const FXchar *p, FXuval n)
FXStream & save (const FXushort *p, FXuval n)
FXStream & save (const FXshort *p, FXuval n)
FXStream & save (const FXuint *p, FXuval n)
FXStream & save (const FXint *p, FXuval n)
FXStream & save (const FXfloat *p, FXuval n)
FXStream & save (const FXdouble *p, FXuval n)
FXStream & save (const FXlong *p, FXuval n)
FXStream & save (const FXulong *p, FXuval n)
FXStream & operator>> (FXuchar &v)
FXStream & operator>> (FXchar &v)
FXStream & operator>> (FXushort &v)
FXStream & operator>> (FXshort &v)
FXStream & operator>> (FXuint &v)
FXStream & operator>> (FXint &v)
FXStream & operator>> (FXfloat &v)
FXStream & operator>> (FXdouble &v)
FXStream & operator>> (FXlong &v)
FXStream & operator>> (FXulong &v)
FXStream & load (FXuchar *p, FXuval n)
FXStream & load (FXchar *p, FXuval n)
FXStream & load (FXushort *p, FXuval n)
FXStream & load (FXshort *p, FXuval n)
FXStream & load (FXuint *p, FXuval n)
FXStream & load (FXint *p, FXuval n)
FXStream & load (FXfloat *p, FXuval n)
FXStream & load (FXdouble *p, FXuval n)
FXStream & load (FXlong *p, FXuval n)
FXStream & load (FXulong *p, FXuval n)
FXStream & saveObject (const FXObject *v)
FXStream & loadObject (FXObject *&v)
FXStream & addObject (const FXObject *v)
virtual ~FXStream ()
Detailed Description
A stream is a way to serialize data and objects into a byte stream.
Each item of data that is saved or loaded from the stream may be byte-swapped, thus allowing little-endian machines to read data produced on big endian ones and vice-versa. Data is serialized exactly as-is. There are no tags or other markers inserted into the stream; thus, the stream may be used to save or load arbitrary binary data. Objects derived from FXObjects may be serialized also; whenever a reference to an object is serialized, a table is consulted to determine if the same object has been encountered previously; if not, the object is added to the table and then its contents are serialized. If the object has been encountered before, only a reference to the object is serialized. When loading back a serialized object, new instances are constructed using the default constructor, and subsequently the object's contents are loaded. A special container object may be passed in which is placed in the table as if it had been encountered before; this will cause only references to this object to be saved. The container object is typically the top-level document object which manages all objects contained by it. Additional objects may be added using addObject(); these will not be actually saved or loaded.
See also:
Stream data flow direction.
Stream status codes.
Stream seeking.
Constructor & Destructor Documentation
FXStream()
FX::FXStream::FXStream (const FXObject * cont = NULL)
Construct stream with given container object.
The container object is an object that will itself not be saved to or loaded from the stream, but which may be referenced by other objects. These references will be properly saved and restored.
~FXStream()
virtual FX::FXStream::~FXStream () virtual
Destructor.
Member Function Documentation
open()
bool FX::FXStream::open (FXStreamDirection save_or_load, FXuval size = 8192, FXuchar * data = NULL)
Open stream for reading (FXStreamLoad) or for writing (FXStreamSave).
An initial buffer size may be given, which must be at least 16 bytes. If data is not NULL, it is expected to point to an external data buffer of length size; otherwise stream will use an internally managed buffer.
flush()
virtual bool FX::FXStream::flush () virtual
Flush buffer.
close()
virtual bool FX::FXStream::close () virtual
Close; return true if OK.
Reimplemented in FX::FXMemoryStream, and FX::FXFileStream.
getSpace()
FXuval FX::FXStream::getSpace () const
Get available buffer space.
setSpace()
void FX::FXStream::setSpace (FXuval sp)
Set available buffer space.
status()
FXStreamStatus FX::FXStream::status () const inline
Get status code.
eof()
bool FX::FXStream::eof () const inline
Return true if at end of file or error.
References FX::FXStreamOK.
setError()
void FX::FXStream::setError (FXStreamStatus err)
Set status code.
direction()
FXStreamDirection FX::FXStream::direction () const inline
Obtain stream direction.
container()
const FXObject* FX::FXStream::container () const inline
Get parent object.
position() [1/2]
FXlong FX::FXStream::position () const inline
Get position.
Referenced by FX::FXFileStream::position(), and FX::FXMemoryStream::position().
position() [2/2]
virtual bool FX::FXStream::position (FXlong offset, FXWhence whence = FXFromStart) virtual
Move to position relative to head, tail, or current location.
Reimplemented in FX::FXMemoryStream, and FX::FXFileStream.
swapBytes() [1/2]
void FX::FXStream::swapBytes (bool s) inline
Change swap bytes flag.
References FX::swap().
swapBytes() [2/2]
bool FX::FXStream::swapBytes () const inline
Get state of the swap bytes flag.
References FX::swap().
setBigEndian()
void FX::FXStream::setBigEndian (bool big)
Set stream to big endian mode if true.
Byte swapping will be enabled if the machine native byte order is not equal to the desired byte order.
isBigEndian()
bool FX::FXStream::isBigEndian () const
Return true if big endian mode.
operator<<() [1/10]
FXStream& FX::FXStream::operator<< (const FXuchar & v)
Save single items to stream.
Referenced by FX::FXFileStream::operator<<(), and FX::FXMemoryStream::operator<<().
operator<<() [2/10]
FXStream& FX::FXStream::operator<< (const FXchar & v) inline
operator<<() [3/10]
FXStream& FX::FXStream::operator<< (const FXushort & v)
operator<<() [4/10]
FXStream& FX::FXStream::operator<< (const FXshort & v) inline
operator<<() [5/10]
FXStream& FX::FXStream::operator<< (const FXuint & v)
operator<<() [6/10]
FXStream& FX::FXStream::operator<< (const FXint & v) inline
operator<<() [7/10]
FXStream& FX::FXStream::operator<< (const FXfloat & v) inline
operator<<() [8/10]
FXStream& FX::FXStream::operator<< (const FXdouble & v)
operator<<() [9/10]
FXStream& FX::FXStream::operator<< (const FXlong & v) inline
operator<<() [10/10]
FXStream& FX::FXStream::operator<< (const FXulong & v) inline
save() [1/10]
FXStream& FX::FXStream::save (const FXuchar * p, FXuval n)
Save arrays of items to stream.
Referenced by FX::FXFileStream::save(), FX::FXMemoryStream::save(), and FX::saveElms().
save() [2/10]
FXStream& FX::FXStream::save (const FXchar * p, FXuval n) inline
References save().
Referenced by save().
save() [3/10]
FXStream& FX::FXStream::save (const FXushort * p, FXuval n)
save() [4/10]
FXStream& FX::FXStream::save (const FXshort * p, FXuval n) inline
References save().
Referenced by save().
save() [5/10]
FXStream& FX::FXStream::save (const FXuint * p, FXuval n)
save() [6/10]
FXStream& FX::FXStream::save (const FXint * p, FXuval n) inline
References save().
Referenced by save().
save() [7/10]
FXStream& FX::FXStream::save (const FXfloat * p, FXuval n) inline
References save().
Referenced by save().
save() [8/10]
FXStream& FX::FXStream::save (const FXdouble * p, FXuval n)
save() [9/10]
FXStream& FX::FXStream::save (const FXlong * p, FXuval n) inline
References save().
Referenced by save().
save() [10/10]
FXStream& FX::FXStream::save (const FXulong * p, FXuval n) inline
References save().
Referenced by save().
operator>>() [1/10]
FXStream& FX::FXStream::operator>> (FXuchar & v)
Load single items from stream.
Referenced by FX::FXFileStream::operator>>(), and FX::FXMemoryStream::operator>>().
operator>>() [2/10]
FXStream& FX::FXStream::operator>> (FXchar & v) inline
operator>>() [3/10]
FXStream& FX::FXStream::operator>> (FXushort & v)
operator>>() [4/10]
FXStream& FX::FXStream::operator>> (FXshort & v) inline
operator>>() [5/10]
FXStream& FX::FXStream::operator>> (FXuint & v)
operator>>() [6/10]
FXStream& FX::FXStream::operator>> (FXint & v) inline
operator>>() [7/10]
FXStream& FX::FXStream::operator>> (FXfloat & v) inline
operator>>() [8/10]
FXStream& FX::FXStream::operator>> (FXdouble & v)
operator>>() [9/10]
FXStream& FX::FXStream::operator>> (FXlong & v) inline
operator>>() [10/10]
FXStream& FX::FXStream::operator>> (FXulong & v) inline
load() [1/10]
FXStream& FX::FXStream::load (FXuchar * p, FXuval n)
Load arrays of items from stream.
Referenced by FX::FXFileStream::load(), FX::FXMemoryStream::load(), and FX::loadElms().
load() [2/10]
FXStream& FX::FXStream::load (FXchar * p, FXuval n) inline
References load().
Referenced by load().
load() [3/10]
FXStream& FX::FXStream::load (FXushort * p, FXuval n)
load() [4/10]
FXStream& FX::FXStream::load (FXshort * p, FXuval n) inline
References load().
Referenced by load().
load() [5/10]
FXStream& FX::FXStream::load (FXuint * p, FXuval n)
load() [6/10]
FXStream& FX::FXStream::load (FXint * p, FXuval n) inline
References load().
Referenced by load().
load() [7/10]
FXStream& FX::FXStream::load (FXfloat * p, FXuval n) inline
References load().
Referenced by load().
load() [8/10]
FXStream& FX::FXStream::load (FXdouble * p, FXuval n)
load() [9/10]
FXStream& FX::FXStream::load (FXlong * p, FXuval n) inline
References load().
Referenced by load().
load() [10/10]
FXStream& FX::FXStream::load (FXulong * p, FXuval n) inline
References load().
Referenced by load().
saveObject()
FXStream& FX::FXStream::saveObject (const FXObject * v)
Save object.
Referenced by FX::FXFileStream::saveObject(), and FX::FXMemoryStream::saveObject().
loadObject()
FXStream& FX::FXStream::loadObject (FXObject *& v)
Load object.
Referenced by FX::FXFileStream::loadObject(), and FX::FXMemoryStream::loadObject().
addObject()
FXStream& FX::FXStream::addObject (const FXObject * v)
Add object without saving or loading.
Copyright © 1997-2005 Jeroen van der Zijp