fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX::FXStringDict Class Reference
#include <FXStringDict.h>
Public Member Functions
FXStringDict ()
FXStringDict (const FXStringDict &orig)
FXStringDict & operator= (const FXStringDict &orig)
const FXchar * insert (const FXchar *ky, const FXchar *str, bool mrk=false)
const FXchar * replace (const FXchar *ky, const FXchar *str, bool mrk=false)
const FXchar * remove (const FXchar *ky)
const FXchar * find (const FXchar *ky) const
const FXchar * data (FXuint pos) const
virtual ~FXStringDict ()
Public Member Functions inherited from FX::FXDict
FXDict ()
FXDict (const FXDict &orig)
FXDict & operator= (const FXDict &orig)
void size (FXint m)
FXint size () const
FXint no () const
void * insert (const FXchar *ky, const void *ptr, bool mrk=false)
void * replace (const FXchar *ky, const void *ptr, bool mrk=false)
void * remove (const FXchar *ky)
void * find (const FXchar *ky) const
bool empty (FXint pos) const
const FXchar * key (FXuint pos) const
void * data (FXuint pos) const
bool mark (FXuint pos) const
FXint first () const
FXint last () const
FXint next (FXint pos) const
FXint prev (FXint pos) const
void clear ()
virtual ~FXDict ()
Public Member Functions inherited from FX::FXObject
virtual long onDefault (FXObject *, FXSelector, void *)
const FXchar * getClassName () const
bool isMemberOf (const FXMetaClass *metaclass) const
virtual long tryHandle (FXObject *sender, FXSelector sel, void *ptr)
virtual void save (FXStream &store) const
virtual void load (FXStream &store)
virtual ~FXObject ()
Detailed Description
String dictionary maps a character string to a character string.
The inserted strings are copied when they're inserted.
Constructor & Destructor Documentation
FXStringDict() [1/2]
FX::FXStringDict::FXStringDict ()
Construct a string dictionary.
FXStringDict() [2/2]
FX::FXStringDict::FXStringDict (const FXStringDict & orig)
Copy constructor.
~FXStringDict()
virtual FX::FXStringDict::~FXStringDict () virtual
Destructor.
Member Function Documentation
operator=()
FXStringDict& FX::FXStringDict::operator= (const FXStringDict & orig)
Assignment operator.
insert()
const FXchar* FX::FXStringDict::insert (const FXchar * ky, const FXchar * str, bool mrk = false) inline
Insert a new string indexed by key, with given mark flag.
References FX::FXDict::insert().
replace()
const FXchar* FX::FXStringDict::replace (const FXchar * ky, const FXchar * str, bool mrk = false) inline
Replace or insert a new string indexed by key, unless given mark is lower that the existing mark.
References FX::FXDict::replace().
remove()
const FXchar* FX::FXStringDict::remove (const FXchar * ky) inline
Remove entry indexed by key.
References FX::FXDict::remove().
find()
const FXchar* FX::FXStringDict::find (const FXchar * ky) const inline
Return the entry indexed by key, or return NULL if the key does not exist.
References FX::FXDict::find().
data()
const FXchar* FX::FXStringDict::data (FXuint pos) const inline
Return the string at position pos.
Copyright © 1997-2005 Jeroen van der Zijp