fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX::FXFileStream Class Reference
#include <FXFileStream.h>
Public Member Functions
FXFileStream (const FXObject *cont=NULL)
bool open (const FXString &filename, FXStreamDirection save_or_load, FXuval size=8192)
virtual bool close ()
FXlong position () const
virtual bool position (FXlong offset, FXWhence whence=FXFromStart)
FXFileStream & operator<< (const FXuchar &v)
FXFileStream & operator<< (const FXchar &v)
FXFileStream & operator<< (const FXushort &v)
FXFileStream & operator<< (const FXshort &v)
FXFileStream & operator<< (const FXuint &v)
FXFileStream & operator<< (const FXint &v)
FXFileStream & operator<< (const FXfloat &v)
FXFileStream & operator<< (const FXdouble &v)
FXFileStream & operator<< (const FXlong &v)
FXFileStream & operator<< (const FXulong &v)
FXFileStream & save (const FXuchar *p, FXuval n)
FXFileStream & save (const FXchar *p, FXuval n)
FXFileStream & save (const FXushort *p, FXuval n)
FXFileStream & save (const FXshort *p, FXuval n)
FXFileStream & save (const FXuint *p, FXuval n)
FXFileStream & save (const FXint *p, FXuval n)
FXFileStream & save (const FXfloat *p, FXuval n)
FXFileStream & save (const FXdouble *p, FXuval n)
FXFileStream & save (const FXlong *p, FXuval n)
FXFileStream & save (const FXulong *p, FXuval n)
FXFileStream & operator>> (FXuchar &v)
FXFileStream & operator>> (FXchar &v)
FXFileStream & operator>> (FXushort &v)
FXFileStream & operator>> (FXshort &v)
FXFileStream & operator>> (FXuint &v)
FXFileStream & operator>> (FXint &v)
FXFileStream & operator>> (FXfloat &v)
FXFileStream & operator>> (FXdouble &v)
FXFileStream & operator>> (FXlong &v)
FXFileStream & operator>> (FXulong &v)
FXFileStream & load (FXuchar *p, FXuval n)
FXFileStream & load (FXchar *p, FXuval n)
FXFileStream & load (FXushort *p, FXuval n)
FXFileStream & load (FXshort *p, FXuval n)
FXFileStream & load (FXuint *p, FXuval n)
FXFileStream & load (FXint *p, FXuval n)
FXFileStream & load (FXfloat *p, FXuval n)
FXFileStream & load (FXdouble *p, FXuval n)
FXFileStream & load (FXlong *p, FXuval n)
FXFileStream & load (FXulong *p, FXuval n)
FXFileStream & saveObject (const FXObject *v)
FXFileStream & loadObject (FXObject *&v)
virtual ~FXFileStream ()
Public Member Functions inherited from FX::FXStream
FXStream (const FXObject *cont=NULL)
bool open (FXStreamDirection save_or_load, FXuval size=8192, FXuchar *data=NULL)
virtual bool flush ()
FXuval getSpace () const
void setSpace (FXuval sp)
FXStreamStatus status () const
bool eof () const
void setError (FXStreamStatus err)
FXStreamDirection direction () const
const FXObject * container () const
FXlong position () const
void swapBytes (bool s)
bool swapBytes () const
void setBigEndian (bool big)
bool isBigEndian () const
FXStream & operator<< (const FXuchar &v)
FXStream & operator<< (const FXchar &v)
FXStream & operator<< (const FXushort &v)
FXStream & operator<< (const FXshort &v)
FXStream & operator<< (const FXuint &v)
FXStream & operator<< (const FXint &v)
FXStream & operator<< (const FXfloat &v)
FXStream & operator<< (const FXdouble &v)
FXStream & operator<< (const FXlong &v)
FXStream & operator<< (const FXulong &v)
FXStream & save (const FXuchar *p, FXuval n)
FXStream & save (const FXchar *p, FXuval n)
FXStream & save (const FXushort *p, FXuval n)
FXStream & save (const FXshort *p, FXuval n)
FXStream & save (const FXuint *p, FXuval n)
FXStream & save (const FXint *p, FXuval n)
FXStream & save (const FXfloat *p, FXuval n)
FXStream & save (const FXdouble *p, FXuval n)
FXStream & save (const FXlong *p, FXuval n)
FXStream & save (const FXulong *p, FXuval n)
FXStream & operator>> (FXuchar &v)
FXStream & operator>> (FXchar &v)
FXStream & operator>> (FXushort &v)
FXStream & operator>> (FXshort &v)
FXStream & operator>> (FXuint &v)
FXStream & operator>> (FXint &v)
FXStream & operator>> (FXfloat &v)
FXStream & operator>> (FXdouble &v)
FXStream & operator>> (FXlong &v)
FXStream & operator>> (FXulong &v)
FXStream & load (FXuchar *p, FXuval n)
FXStream & load (FXchar *p, FXuval n)
FXStream & load (FXushort *p, FXuval n)
FXStream & load (FXshort *p, FXuval n)
FXStream & load (FXuint *p, FXuval n)
FXStream & load (FXint *p, FXuval n)
FXStream & load (FXfloat *p, FXuval n)
FXStream & load (FXdouble *p, FXuval n)
FXStream & load (FXlong *p, FXuval n)
FXStream & load (FXulong *p, FXuval n)
FXStream & saveObject (const FXObject *v)
FXStream & loadObject (FXObject *&v)
FXStream & addObject (const FXObject *v)
virtual ~FXStream ()
Detailed Description
File Store Definition.
Constructor & Destructor Documentation
FXFileStream()
FX::FXFileStream::FXFileStream (const FXObject * cont = NULL)
Create file store.
~FXFileStream()
virtual FX::FXFileStream::~FXFileStream () virtual
Destructor.
Member Function Documentation
open()
bool FX::FXFileStream::open (const FXString & filename, FXStreamDirection save_or_load, FXuval size = 8192)
Open binary data file stream; allocate a buffer of the given size for the file I/O; the buffer must be at least 16 bytes.
close()
virtual bool FX::FXFileStream::close () virtual
Close file store.
Reimplemented from FX::FXStream.
position() [1/2]
FXlong FX::FXFileStream::position () const inline
Get position.
References FX::FXStream::position().
position() [2/2]
virtual bool FX::FXFileStream::position (FXlong offset, FXWhence whence = FXFromStart) virtual
Move to position.
Reimplemented from FX::FXStream.
operator<<() [1/10]
FXFileStream& FX::FXFileStream::operator<< (const FXuchar & v) inline
Save single items to stream.
References FX::FXStream::operator<<().
operator<<() [2/10]
FXFileStream& FX::FXFileStream::operator<< (const FXchar & v) inline
References FX::FXStream::operator<<().
operator<<() [3/10]
FXFileStream& FX::FXFileStream::operator<< (const FXushort & v) inline
References FX::FXStream::operator<<().
operator<<() [4/10]
FXFileStream& FX::FXFileStream::operator<< (const FXshort & v) inline
References FX::FXStream::operator<<().
operator<<() [5/10]
FXFileStream& FX::FXFileStream::operator<< (const FXuint & v) inline
References FX::FXStream::operator<<().
operator<<() [6/10]
FXFileStream& FX::FXFileStream::operator<< (const FXint & v) inline
References FX::FXStream::operator<<().
operator<<() [7/10]
FXFileStream& FX::FXFileStream::operator<< (const FXfloat & v) inline
References FX::FXStream::operator<<().
operator<<() [8/10]
FXFileStream& FX::FXFileStream::operator<< (const FXdouble & v) inline
References FX::FXStream::operator<<().
operator<<() [9/10]
FXFileStream& FX::FXFileStream::operator<< (const FXlong & v) inline
References FX::FXStream::operator<<().
operator<<() [10/10]
FXFileStream& FX::FXFileStream::operator<< (const FXulong & v) inline
References FX::FXStream::operator<<().
save() [1/10]
FXFileStream& FX::FXFileStream::save (const FXuchar * p, FXuval n) inline
Save arrays of items to stream.
References FX::FXStream::save().
save() [2/10]
FXFileStream& FX::FXFileStream::save (const FXchar * p, FXuval n) inline
References FX::FXStream::save().
save() [3/10]
FXFileStream& FX::FXFileStream::save (const FXushort * p, FXuval n) inline
References FX::FXStream::save().
save() [4/10]
FXFileStream& FX::FXFileStream::save (const FXshort * p, FXuval n) inline
References FX::FXStream::save().
save() [5/10]
FXFileStream& FX::FXFileStream::save (const FXuint * p, FXuval n) inline
References FX::FXStream::save().
save() [6/10]
FXFileStream& FX::FXFileStream::save (const FXint * p, FXuval n) inline
References FX::FXStream::save().
save() [7/10]
FXFileStream& FX::FXFileStream::save (const FXfloat * p, FXuval n) inline
References FX::FXStream::save().
save() [8/10]
FXFileStream& FX::FXFileStream::save (const FXdouble * p, FXuval n) inline
References FX::FXStream::save().
save() [9/10]
FXFileStream& FX::FXFileStream::save (const FXlong * p, FXuval n) inline
References FX::FXStream::save().
save() [10/10]
FXFileStream& FX::FXFileStream::save (const FXulong * p, FXuval n) inline
References FX::FXStream::save().
operator>>() [1/10]
FXFileStream& FX::FXFileStream::operator>> (FXuchar & v) inline
Load single items from stream.
References FX::FXStream::operator>>().
operator>>() [2/10]
FXFileStream& FX::FXFileStream::operator>> (FXchar & v) inline
References FX::FXStream::operator>>().
operator>>() [3/10]
FXFileStream& FX::FXFileStream::operator>> (FXushort & v) inline
References FX::FXStream::operator>>().
operator>>() [4/10]
FXFileStream& FX::FXFileStream::operator>> (FXshort & v) inline
References FX::FXStream::operator>>().
operator>>() [5/10]
FXFileStream& FX::FXFileStream::operator>> (FXuint & v) inline
References FX::FXStream::operator>>().
operator>>() [6/10]
FXFileStream& FX::FXFileStream::operator>> (FXint & v) inline
References FX::FXStream::operator>>().
operator>>() [7/10]
FXFileStream& FX::FXFileStream::operator>> (FXfloat & v) inline
References FX::FXStream::operator>>().
operator>>() [8/10]
FXFileStream& FX::FXFileStream::operator>> (FXdouble & v) inline
References FX::FXStream::operator>>().
operator>>() [9/10]
FXFileStream& FX::FXFileStream::operator>> (FXlong & v) inline
References FX::FXStream::operator>>().
operator>>() [10/10]
FXFileStream& FX::FXFileStream::operator>> (FXulong & v) inline
References FX::FXStream::operator>>().
load() [1/10]
FXFileStream& FX::FXFileStream::load (FXuchar * p, FXuval n) inline
Load arrays of items from stream.
References FX::FXStream::load().
load() [2/10]
FXFileStream& FX::FXFileStream::load (FXchar * p, FXuval n) inline
References FX::FXStream::load().
load() [3/10]
FXFileStream& FX::FXFileStream::load (FXushort * p, FXuval n) inline
References FX::FXStream::load().
load() [4/10]
FXFileStream& FX::FXFileStream::load (FXshort * p, FXuval n) inline
References FX::FXStream::load().
load() [5/10]
FXFileStream& FX::FXFileStream::load (FXuint * p, FXuval n) inline
References FX::FXStream::load().
load() [6/10]
FXFileStream& FX::FXFileStream::load (FXint * p, FXuval n) inline
References FX::FXStream::load().
load() [7/10]
FXFileStream& FX::FXFileStream::load (FXfloat * p, FXuval n) inline
References FX::FXStream::load().
load() [8/10]
FXFileStream& FX::FXFileStream::load (FXdouble * p, FXuval n) inline
References FX::FXStream::load().
load() [9/10]
FXFileStream& FX::FXFileStream::load (FXlong * p, FXuval n) inline
References FX::FXStream::load().
load() [10/10]
FXFileStream& FX::FXFileStream::load (FXulong * p, FXuval n) inline
References FX::FXStream::load().
saveObject()
FXFileStream& FX::FXFileStream::saveObject (const FXObject * v) inline
Save object.
References FX::FXStream::saveObject().
loadObject()
FXFileStream& FX::FXFileStream::loadObject (FXObject *& v) inline
Load object.
References FX::FXStream::loadObject().
Copyright © 1997-2005 Jeroen van der Zijp