fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX::FXIconDict Class Reference
#include <FXIconDict.h>
Public Member Functions
FXIconDict (FXApp *app, const FXString &p=defaultIconPath)
void setIconSource (FXIconSource *src)
FXIconSource * getIconSource () const
void setIconPath (const FXString &p)
const FXString & getIconPath () const
FXIcon * insert (const FXchar *name)
FXIcon * remove (const FXchar *name)
FXIcon * find (const FXchar *name)
virtual void save (FXStream &store) const
virtual void load (FXStream &store)
virtual ~FXIconDict ()
Public Member Functions inherited from FX::FXDict
FXDict ()
FXDict (const FXDict &orig)
FXDict & operator= (const FXDict &orig)
void size (FXint m)
FXint size () const
FXint no () const
void * insert (const FXchar *ky, const void *ptr, bool mrk=false)
void * replace (const FXchar *ky, const void *ptr, bool mrk=false)
void * remove (const FXchar *ky)
void * find (const FXchar *ky) const
bool empty (FXint pos) const
const FXchar * key (FXuint pos) const
void * data (FXuint pos) const
bool mark (FXuint pos) const
FXint first () const
FXint last () const
FXint next (FXint pos) const
FXint prev (FXint pos) const
void clear ()
virtual ~FXDict ()
Public Member Functions inherited from FX::FXObject
virtual long onDefault (FXObject *, FXSelector, void *)
const FXchar * getClassName () const
bool isMemberOf (const FXMetaClass *metaclass) const
virtual long tryHandle (FXObject *sender, FXSelector sel, void *ptr)
virtual ~FXObject ()
Static Public Attributes
static const FXchar defaultIconPath []
Detailed Description
The Icon Dictionary manages a collection of icons.
The icons are referenced by their file name. When first encountering a new file name, the icon is located by searching the icon search path for the icon file. If found, the services of the icon source object are used to load the icon from the file. A custom icon source may be installed to furnish support for additonal image file formats. Once the icon is loaded, an association between the icon name and the icon is entered into the icon dictionary. Subsequent searches for an icon with this name will be satisfied from the cached value. The lifetype of the icons is managed by the icon dictionary, and thus all icons will be deleted when the dictionary is deleted.
Constructor & Destructor Documentation
FXIconDict()
FX::FXIconDict::FXIconDict (FXApp * app, const FXString & p = defaultIconPath)
Construct icon dictionary, and set initial search path; also creates a default icon source object.
~FXIconDict()
virtual FX::FXIconDict::~FXIconDict () virtual
Destroy the icon dict as well as the icon source.
Member Function Documentation
setIconSource()
void FX::FXIconDict::setIconSource (FXIconSource * src) inline
Change icon source.
getIconSource()
FXIconSource* FX::FXIconDict::getIconSource () const inline
Return icon source.
setIconPath()
void FX::FXIconDict::setIconPath (const FXString & p) inline
Set icon search path.
getIconPath()
const FXString& FX::FXIconDict::getIconPath () const inline
Return current icon search path.
insert()
FXIcon* FX::FXIconDict::insert (const FXchar * name) inline
Insert unique icon loaded from filename into dictionary.
References FX::FXDict::insert(), and FX::FXPath::name().
remove()
FXIcon* FX::FXIconDict::remove (const FXchar * name) inline
Remove icon from dictionary.
References FX::FXPath::name(), and FX::FXDict::remove().
find()
FXIcon* FX::FXIconDict::find (const FXchar * name) inline
Find icon by name.
References FX::FXDict::find(), and FX::FXPath::name().
save()
virtual void FX::FXIconDict::save (FXStream & store) const virtual
Save to stream.
Reimplemented from FX::FXObject.
load()
virtual void FX::FXIconDict::load (FXStream & store) virtual
Load from stream.
Reimplemented from FX::FXObject.
Member Data Documentation
defaultIconPath
const FXchar FX::FXIconDict::defaultIconPath[] static
Default icon search path.
Copyright © 1997-2005 Jeroen van der Zijp