fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX::FXMemoryStream Class Reference
#include <FXMemoryStream.h>
Public Member Functions
FXMemoryStream (const FXObject *cont=NULL)
bool open (FXStreamDirection save_or_load, FXuchar *data)
bool open (FXStreamDirection save_or_load, FXuval size, FXuchar *data)
void takeBuffer (FXuchar *&data, FXuval &size)
void giveBuffer (FXuchar *data, FXuval size)
virtual bool close ()
FXlong position () const
virtual bool position (FXlong offset, FXWhence whence=FXFromStart)
FXMemoryStream & operator<< (const FXuchar &v)
FXMemoryStream & operator<< (const FXchar &v)
FXMemoryStream & operator<< (const FXushort &v)
FXMemoryStream & operator<< (const FXshort &v)
FXMemoryStream & operator<< (const FXuint &v)
FXMemoryStream & operator<< (const FXint &v)
FXMemoryStream & operator<< (const FXfloat &v)
FXMemoryStream & operator<< (const FXdouble &v)
FXMemoryStream & operator<< (const FXlong &v)
FXMemoryStream & operator<< (const FXulong &v)
FXMemoryStream & save (const FXuchar *p, FXuval n)
FXMemoryStream & save (const FXchar *p, FXuval n)
FXMemoryStream & save (const FXushort *p, FXuval n)
FXMemoryStream & save (const FXshort *p, FXuval n)
FXMemoryStream & save (const FXuint *p, FXuval n)
FXMemoryStream & save (const FXint *p, FXuval n)
FXMemoryStream & save (const FXfloat *p, FXuval n)
FXMemoryStream & save (const FXdouble *p, FXuval n)
FXMemoryStream & save (const FXlong *p, FXuval n)
FXMemoryStream & save (const FXulong *p, FXuval n)
FXMemoryStream & operator>> (FXuchar &v)
FXMemoryStream & operator>> (FXchar &v)
FXMemoryStream & operator>> (FXushort &v)
FXMemoryStream & operator>> (FXshort &v)
FXMemoryStream & operator>> (FXuint &v)
FXMemoryStream & operator>> (FXint &v)
FXMemoryStream & operator>> (FXfloat &v)
FXMemoryStream & operator>> (FXdouble &v)
FXMemoryStream & operator>> (FXlong &v)
FXMemoryStream & operator>> (FXulong &v)
FXMemoryStream & load (FXuchar *p, FXuval n)
FXMemoryStream & load (FXchar *p, FXuval n)
FXMemoryStream & load (FXushort *p, FXuval n)
FXMemoryStream & load (FXshort *p, FXuval n)
FXMemoryStream & load (FXuint *p, FXuval n)
FXMemoryStream & load (FXint *p, FXuval n)
FXMemoryStream & load (FXfloat *p, FXuval n)
FXMemoryStream & load (FXdouble *p, FXuval n)
FXMemoryStream & load (FXlong *p, FXuval n)
FXMemoryStream & load (FXulong *p, FXuval n)
FXMemoryStream & saveObject (const FXObject *v)
FXMemoryStream & loadObject (FXObject *&v)
Public Member Functions inherited from FX::FXStream
FXStream (const FXObject *cont=NULL)
bool open (FXStreamDirection save_or_load, FXuval size=8192, FXuchar *data=NULL)
virtual bool flush ()
FXuval getSpace () const
void setSpace (FXuval sp)
FXStreamStatus status () const
bool eof () const
void setError (FXStreamStatus err)
FXStreamDirection direction () const
const FXObject * container () const
FXlong position () const
void swapBytes (bool s)
bool swapBytes () const
void setBigEndian (bool big)
bool isBigEndian () const
FXStream & operator<< (const FXuchar &v)
FXStream & operator<< (const FXchar &v)
FXStream & operator<< (const FXushort &v)
FXStream & operator<< (const FXshort &v)
FXStream & operator<< (const FXuint &v)
FXStream & operator<< (const FXint &v)
FXStream & operator<< (const FXfloat &v)
FXStream & operator<< (const FXdouble &v)
FXStream & operator<< (const FXlong &v)
FXStream & operator<< (const FXulong &v)
FXStream & save (const FXuchar *p, FXuval n)
FXStream & save (const FXchar *p, FXuval n)
FXStream & save (const FXushort *p, FXuval n)
FXStream & save (const FXshort *p, FXuval n)
FXStream & save (const FXuint *p, FXuval n)
FXStream & save (const FXint *p, FXuval n)
FXStream & save (const FXfloat *p, FXuval n)
FXStream & save (const FXdouble *p, FXuval n)
FXStream & save (const FXlong *p, FXuval n)
FXStream & save (const FXulong *p, FXuval n)
FXStream & operator>> (FXuchar &v)
FXStream & operator>> (FXchar &v)
FXStream & operator>> (FXushort &v)
FXStream & operator>> (FXshort &v)
FXStream & operator>> (FXuint &v)
FXStream & operator>> (FXint &v)
FXStream & operator>> (FXfloat &v)
FXStream & operator>> (FXdouble &v)
FXStream & operator>> (FXlong &v)
FXStream & operator>> (FXulong &v)
FXStream & load (FXuchar *p, FXuval n)
FXStream & load (FXchar *p, FXuval n)
FXStream & load (FXushort *p, FXuval n)
FXStream & load (FXshort *p, FXuval n)
FXStream & load (FXuint *p, FXuval n)
FXStream & load (FXint *p, FXuval n)
FXStream & load (FXfloat *p, FXuval n)
FXStream & load (FXdouble *p, FXuval n)
FXStream & load (FXlong *p, FXuval n)
FXStream & load (FXulong *p, FXuval n)
FXStream & saveObject (const FXObject *v)
FXStream & loadObject (FXObject *&v)
FXStream & addObject (const FXObject *v)
virtual ~FXStream ()
Detailed Description
Memory Store Definition.
Constructor & Destructor Documentation
FXMemoryStream()
FX::FXMemoryStream::FXMemoryStream (const FXObject * cont = NULL)
Create memory store.
Member Function Documentation
open() [1/2]
bool FX::FXMemoryStream::open (FXStreamDirection save_or_load, FXuchar * data)
Open file store.
open() [2/2]
bool FX::FXMemoryStream::open (FXStreamDirection save_or_load, FXuval size, FXuchar * data)
Open memory store.
takeBuffer()
void FX::FXMemoryStream::takeBuffer (FXuchar *& data, FXuval & size)
Take buffer away from stream.
giveBuffer()
void FX::FXMemoryStream::giveBuffer (FXuchar * data, FXuval size)
Give buffer to stream.
close()
virtual bool FX::FXMemoryStream::close () virtual
Close memory store.
Reimplemented from FX::FXStream.
position() [1/2]
FXlong FX::FXMemoryStream::position () const inline
Get position.
References FX::FXStream::position().
position() [2/2]
virtual bool FX::FXMemoryStream::position (FXlong offset, FXWhence whence = FXFromStart) virtual
Move to position.
Reimplemented from FX::FXStream.
operator<<() [1/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXuchar & v) inline
Save single items to stream.
References FX::FXStream::operator<<().
operator<<() [2/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXchar & v) inline
References FX::FXStream::operator<<().
operator<<() [3/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXushort & v) inline
References FX::FXStream::operator<<().
operator<<() [4/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXshort & v) inline
References FX::FXStream::operator<<().
operator<<() [5/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXuint & v) inline
References FX::FXStream::operator<<().
operator<<() [6/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXint & v) inline
References FX::FXStream::operator<<().
operator<<() [7/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXfloat & v) inline
References FX::FXStream::operator<<().
operator<<() [8/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXdouble & v) inline
References FX::FXStream::operator<<().
operator<<() [9/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXlong & v) inline
References FX::FXStream::operator<<().
operator<<() [10/10]
FXMemoryStream& FX::FXMemoryStream::operator<< (const FXulong & v) inline
References FX::FXStream::operator<<().
save() [1/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXuchar * p, FXuval n) inline
Save arrays of items to stream.
References FX::FXStream::save().
save() [2/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXchar * p, FXuval n) inline
References FX::FXStream::save().
save() [3/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXushort * p, FXuval n) inline
References FX::FXStream::save().
save() [4/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXshort * p, FXuval n) inline
References FX::FXStream::save().
save() [5/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXuint * p, FXuval n) inline
References FX::FXStream::save().
save() [6/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXint * p, FXuval n) inline
References FX::FXStream::save().
save() [7/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXfloat * p, FXuval n) inline
References FX::FXStream::save().
save() [8/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXdouble * p, FXuval n) inline
References FX::FXStream::save().
save() [9/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXlong * p, FXuval n) inline
References FX::FXStream::save().
save() [10/10]
FXMemoryStream& FX::FXMemoryStream::save (const FXulong * p, FXuval n) inline
References FX::FXStream::save().
operator>>() [1/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXuchar & v) inline
Load single items from stream.
References FX::FXStream::operator>>().
operator>>() [2/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXchar & v) inline
References FX::FXStream::operator>>().
operator>>() [3/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXushort & v) inline
References FX::FXStream::operator>>().
operator>>() [4/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXshort & v) inline
References FX::FXStream::operator>>().
operator>>() [5/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXuint & v) inline
References FX::FXStream::operator>>().
operator>>() [6/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXint & v) inline
References FX::FXStream::operator>>().
operator>>() [7/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXfloat & v) inline
References FX::FXStream::operator>>().
operator>>() [8/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXdouble & v) inline
References FX::FXStream::operator>>().
operator>>() [9/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXlong & v) inline
References FX::FXStream::operator>>().
operator>>() [10/10]
FXMemoryStream& FX::FXMemoryStream::operator>> (FXulong & v) inline
References FX::FXStream::operator>>().
load() [1/10]
FXMemoryStream& FX::FXMemoryStream::load (FXuchar * p, FXuval n) inline
Load arrays of items from stream.
References FX::FXStream::load().
load() [2/10]
FXMemoryStream& FX::FXMemoryStream::load (FXchar * p, FXuval n) inline
References FX::FXStream::load().
load() [3/10]
FXMemoryStream& FX::FXMemoryStream::load (FXushort * p, FXuval n) inline
References FX::FXStream::load().
load() [4/10]
FXMemoryStream& FX::FXMemoryStream::load (FXshort * p, FXuval n) inline
References FX::FXStream::load().
load() [5/10]
FXMemoryStream& FX::FXMemoryStream::load (FXuint * p, FXuval n) inline
References FX::FXStream::load().
load() [6/10]
FXMemoryStream& FX::FXMemoryStream::load (FXint * p, FXuval n) inline
References FX::FXStream::load().
load() [7/10]
FXMemoryStream& FX::FXMemoryStream::load (FXfloat * p, FXuval n) inline
References FX::FXStream::load().
load() [8/10]
FXMemoryStream& FX::FXMemoryStream::load (FXdouble * p, FXuval n) inline
References FX::FXStream::load().
load() [9/10]
FXMemoryStream& FX::FXMemoryStream::load (FXlong * p, FXuval n) inline
References FX::FXStream::load().
load() [10/10]
FXMemoryStream& FX::FXMemoryStream::load (FXulong * p, FXuval n) inline
References FX::FXStream::load().
saveObject()
FXMemoryStream& FX::FXMemoryStream::saveObject (const FXObject * v) inline
Save object.
References FX::FXStream::saveObject().
loadObject()
FXMemoryStream& FX::FXMemoryStream::loadObject (FXObject *& v) inline
Load object.
References FX::FXStream::loadObject().
Copyright © 1997-2005 Jeroen van der Zijp