fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX::FXDict Class Reference
#include <FXDict.h>
Public Member Functions
FXDict ()
FXDict (const FXDict &orig)
FXDict & operator= (const FXDict &orig)
void size (FXint m)
FXint size () const
FXint no () const
void * insert (const FXchar *ky, const void *ptr, bool mrk=false)
void * replace (const FXchar *ky, const void *ptr, bool mrk=false)
void * remove (const FXchar *ky)
void * find (const FXchar *ky) const
bool empty (FXint pos) const
const FXchar * key (FXuint pos) const
void * data (FXuint pos) const
bool mark (FXuint pos) const
FXint first () const
FXint last () const
FXint next (FXint pos) const
FXint prev (FXint pos) const
void clear ()
virtual ~FXDict ()
Public Member Functions inherited from FX::FXObject
virtual long onDefault (FXObject *, FXSelector, void *)
const FXchar * getClassName () const
bool isMemberOf (const FXMetaClass *metaclass) const
virtual long tryHandle (FXObject *sender, FXSelector sel, void *ptr)
virtual void save (FXStream &store) const
virtual void load (FXStream &store)
virtual ~FXObject ()
Detailed Description
The dictionary class maintains a fast-access hash table of entities indexed by a character string.
It is typically used to map strings to pointers; however, overloading the createData() and deleteData() members allows any type of data to be indexed by strings.
Constructor & Destructor Documentation
FXDict() [1/2]
FX::FXDict::FXDict ()
Construct an empty dictionary.
FXDict() [2/2]
FX::FXDict::FXDict (const FXDict & orig)
Copy constructor; does bit-copy of void pointer data.
~FXDict()
virtual FX::FXDict::~FXDict () virtual
Destructor.
Member Function Documentation
operator=()
FXDict& FX::FXDict::operator= (const FXDict & orig)
Assignment operator.
size() [1/2]
void FX::FXDict::size (FXint m)
Resize the table to the given size.
size() [2/2]
FXint FX::FXDict::size () const inline
Return the size of the table, including the empty slots.
no()
FXint FX::FXDict::no () const inline
Return the total number of entries in the table.
insert()
void* FX::FXDict::insert (const FXchar * ky, const void * ptr, bool mrk = false)
Insert a new entry into the table given key and mark.
If there is already an entry with that key, leave it unchanged, otherwise insert the new entry.
Referenced by FX::FXStringDict::insert(), and FX::FXIconDict::insert().
replace()
void* FX::FXDict::replace (const FXchar * ky, const void * ptr, bool mrk = false)
Replace data at key, if the entry's mark is less than or equal to the given mark.
If there was no existing entry, a new entry is inserted with the given mark.
Referenced by FX::FXStringDict::replace().
remove()
void* FX::FXDict::remove (const FXchar * ky)
Remove data given key.
Referenced by FX::FXStringDict::remove(), and FX::FXIconDict::remove().
find()
void* FX::FXDict::find (const FXchar * ky) const
Find data pointer given key.
Referenced by FX::FXStringDict::find(), FX::FXSettings::find(), and FX::FXIconDict::find().
empty()
bool FX::FXDict::empty (FXint pos) const inline
Return true if slot is empty.
key()
const FXchar* FX::FXDict::key (FXuint pos) const inline
Return key at position pos.
data()
void* FX::FXDict::data (FXuint pos) const inline
return data pointer at position pos.
Referenced by FX::FXSettings::data().
mark()
bool FX::FXDict::mark (FXuint pos) const inline
Return mark flag of entry at position pos.
first()
FXint FX::FXDict::first () const
Return position of first filled slot, or >= total.
last()
FXint FX::FXDict::last () const
Return position of last filled slot or -1.
next()
FXint FX::FXDict::next (FXint pos) const
Return position of next filled slot in hash table or a value greater than or equal to total if no filled slot was found.
prev()
FXint FX::FXDict::prev (FXint pos) const
Return position of previous filled slot in hash table or a -1 if no filled slot was found.
clear()
void FX::FXDict::clear ()
Clear all entries.
Copyright © 1997-2005 Jeroen van der Zijp