fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX::FXArray< TYPE > Class Template Reference
#include <FXArray.h>
Public Member Functions
FXArray ()
FXArray (FXint n)
FXArray (const FXArray< TYPE > &src)
FXArray (const TYPE &src, FXint n)
FXArray (const TYPE *src, FXint n)
FXint no () const
bool no (FXint n)
FXArray< TYPE > & operator= (const FXArray< TYPE > &src)
TYPE & operator[] (FXint i)
const TYPE & operator[] (FXint i) const
TYPE & at (FXint i)
const TYPE & at (FXint i) const
TYPE * data () const
FXArray< TYPE > & adopt (FXArray< TYPE > &src)
FXArray< TYPE > & assign (const TYPE &src)
FXArray< TYPE > & assign (const TYPE &src, FXint n)
FXArray< TYPE > & assign (const TYPE *src, FXint n)
FXArray< TYPE > & assign (const FXArray< TYPE > &src)
FXArray< TYPE > & insert (FXint pos, const TYPE &src)
FXArray< TYPE > & insert (FXint pos, const TYPE &src, FXint n)
FXArray< TYPE > & insert (FXint pos, const TYPE *src, FXint n)
FXArray< TYPE > & insert (FXint pos, const FXArray< TYPE > &src)
FXArray< TYPE > & prepend (const TYPE &src)
FXArray< TYPE > & prepend (const TYPE &src, FXint n)
FXArray< TYPE > & prepend (const TYPE *src, FXint n)
FXArray< TYPE > & prepend (const FXArray< TYPE > &src)
FXArray< TYPE > & append (const TYPE &src)
FXArray< TYPE > & append (const TYPE &src, FXint n)
FXArray< TYPE > & append (const TYPE *src, FXint n)
FXArray< TYPE > & append (const FXArray< TYPE > &src)
FXArray< TYPE > & erase (FXint pos)
FXArray< TYPE > & erase (FXint pos, FXint n)
FXArray< TYPE > & clear ()
~FXArray ()
Detailed Description
template<class TYPE>
class FX::FXArray< TYPE >
Array of some generic type.
Constructor & Destructor Documentation
FXArray() [1/5]
template<class TYPE> FX::FXArray< TYPE >::FXArray () inline
Create as empty.
FXArray() [2/5]
template<class TYPE> FX::FXArray< TYPE >::FXArray (FXint n) inline
Create with given size n.
References FX::allocElms(), and FX::constructElms().
FXArray() [3/5]
template<class TYPE> FX::FXArray< TYPE >::FXArray (const FXArray< TYPE > & src) inline
Create initialized from another array.
References FX::allocElms(), FX::constructElms(), and FX::copyElms().
FXArray() [4/5]
template<class TYPE> FX::FXArray< TYPE >::FXArray (const TYPE & src, FXint n) inline
Create initialized with n copies of object.
References FX::allocElms(), FX::constructElms(), and FX::fillElms().
FXArray() [5/5]
template<class TYPE> FX::FXArray< TYPE >::FXArray (const TYPE * src, FXint n) inline
Create initialized with array of n objects.
References FX::allocElms(), FX::constructElms(), and FX::copyElms().
~FXArray()
template<class TYPE> FX::FXArray< TYPE >::~FXArray () inline
Delete data.
References FX::destructElms(), and FX::freeElms().
Member Function Documentation
no() [1/2]
template<class TYPE> FXint FX::FXArray< TYPE >::no () const inline
Return number of elements.
Referenced by FX::FXArray< TYPE >::adopt(), FX::FXArray< TYPE >::append(), FX::FXArray< TYPE >::assign(), FX::FXArray< TYPE >::erase(), FX::FXArray< TYPE >::insert(), FX::FXArray< TYPE >::operator=(), and FX::FXArray< TYPE >::prepend().
no() [2/2]
template<class TYPE> bool FX::FXArray< TYPE >::no (FXint n) inline
Change number of elements to n.
References FX::constructElms(), FX::destructElms(), and FX::resizeElms().
operator=()
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::operator= (const FXArray< TYPE > & src) inline
Assign from another list.
References FX::copyElms(), and FX::FXArray< TYPE >::no().
operator[]() [1/2]
template<class TYPE> TYPE& FX::FXArray< TYPE >::operator[] (FXint i) inline
Index into array.
operator[]() [2/2]
template<class TYPE> const TYPE& FX::FXArray< TYPE >::operator[] (FXint i) const inline
at() [1/2]
template<class TYPE> TYPE& FX::FXArray< TYPE >::at (FXint i) inline
Index into list.
at() [2/2]
template<class TYPE> const TYPE& FX::FXArray< TYPE >::at (FXint i) const inline
data()
template<class TYPE> TYPE* FX::FXArray< TYPE >::data () const inline
Return pointer to list.
adopt()
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::adopt (FXArray< TYPE > & src) inline
Adopt array from source.
References FX::FXArray< TYPE >::no(), and NULL.
assign() [1/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::assign (const TYPE & src) inline
Assign object p to list.
References FX::FXArray< TYPE >::no().
assign() [2/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::assign (const TYPE & src, FXint n) inline
Assign n copies of object to list.
References FX::fillElms(), and FX::FXArray< TYPE >::no().
assign() [3/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::assign (const TYPE * src, FXint n) inline
Assign n objects to list.
References FX::copyElms(), and FX::FXArray< TYPE >::no().
assign() [4/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::assign (const FXArray< TYPE > & src) inline
Assign n objects to list.
References FX::copyElms(), and FX::FXArray< TYPE >::no().
insert() [1/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::insert (FXint pos, const TYPE & src) inline
Insert an object.
References FX::moveElms(), and FX::FXArray< TYPE >::no().
insert() [2/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::insert (FXint pos, const TYPE & src, FXint n) inline
Insert n copies of object at specified position.
References FX::fillElms(), FX::moveElms(), and FX::FXArray< TYPE >::no().
insert() [3/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::insert (FXint pos, const TYPE * src, FXint n) inline
Insert n objects at specified position.
References FX::copyElms(), FX::moveElms(), and FX::FXArray< TYPE >::no().
insert() [4/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::insert (FXint pos, const FXArray< TYPE > & src) inline
Insert n objects at specified position.
References FX::copyElms(), FX::moveElms(), and FX::FXArray< TYPE >::no().
prepend() [1/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::prepend (const TYPE & src) inline
Prepend object.
References FX::moveElms(), and FX::FXArray< TYPE >::no().
prepend() [2/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::prepend (const TYPE & src, FXint n) inline
Prepend n copies of object.
References FX::fillElms(), FX::moveElms(), and FX::FXArray< TYPE >::no().
prepend() [3/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::prepend (const TYPE * src, FXint n) inline
Prepend n objects.
References FX::copyElms(), FX::moveElms(), and FX::FXArray< TYPE >::no().
prepend() [4/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::prepend (const FXArray< TYPE > & src) inline
Prepend n objects.
References FX::copyElms(), FX::moveElms(), and FX::FXArray< TYPE >::no().
append() [1/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::append (const TYPE & src) inline
Append object.
References FX::FXArray< TYPE >::no().
append() [2/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::append (const TYPE & src, FXint n) inline
Append n copies of object.
References FX::fillElms(), and FX::FXArray< TYPE >::no().
append() [3/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::append (const TYPE * src, FXint n) inline
Append n objects.
References FX::copyElms(), and FX::FXArray< TYPE >::no().
append() [4/4]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::append (const FXArray< TYPE > & src) inline
Append n objects.
References FX::copyElms(), and FX::FXArray< TYPE >::no().
erase() [1/2]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::erase (FXint pos) inline
Remove object at pos.
References FX::moveElms(), and FX::FXArray< TYPE >::no().
erase() [2/2]
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::erase (FXint pos, FXint n) inline
Remove n objects starting at pos.
References FX::moveElms(), and FX::FXArray< TYPE >::no().
clear()
template<class TYPE> FXArray<TYPE>& FX::FXArray< TYPE >::clear () inline
Remove all objects.
References FX::destructElms(), and FX::freeElms().
Copyright © 1997-2005 Jeroen van der Zijp