fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX Namespace Reference
Namespaces
Ascii
FXPath
FXSystem
FXURL
Unicode
Classes
class FX4Splitter
class FX7Segment
class FX885910Codec
class FX885911Codec
class FX885913Codec
class FX885914Codec
class FX885915Codec
class FX885916Codec
class FX88591Codec
class FX88592Codec
class FX88593Codec
class FX88594Codec
class FX88595Codec
class FX88596Codec
class FX88597Codec
class FX88598Codec
class FX88599Codec
class FXAccelTable
class FXApp
struct FXArc
class FXArray
class FXArrowButton
class FXBitmap
class FXBitmapFrame
class FXBitmapView
class FXBMPIcon
class FXBMPImage
class FXButton
class FXCanvas
class FXCheckButton
class FXChoiceBox
class FXColorBar
class FXColorDialog
class FXColorItem
class FXColorList
class FXColorRing
class FXColorSelector
class FXColorWell
class FXColorWheel
class FXComboBox
class FXComboTableItem
class FXCommand
class FXCommandGroup
class FXComposeContext
class FXComposite
class FXCondition
class FXCP1250Codec
class FXCP1251Codec
class FXCP1252Codec
class FXCP1253Codec
class FXCP1254Codec
class FXCP1255Codec
class FXCP1256Codec
class FXCP1257Codec
class FXCP1258Codec
class FXCP437Codec
class FXCP850Codec
class FXCP852Codec
class FXCP855Codec
class FXCP856Codec
class FXCP857Codec
class FXCP860Codec
class FXCP861Codec
class FXCP862Codec
class FXCP863Codec
class FXCP864Codec
class FXCP865Codec
class FXCP866Codec
class FXCP869Codec
class FXCP874Codec
class FXCURCursor
class FXCursor
class FXDataTarget
class FXDate
class FXDC
class FXDCPrint
class FXDCWindow
class FXDebugTarget
class FXDelegator
class FXDial
class FXDialogBox
class FXDict
class FXDir
class FXDirBox
class FXDirDialog
class FXDirItem
class FXDirList
class FXDirSelector
class FXDockBar
class FXDockHandler
class FXDockSite
class FXDockTitle
class FXDocument
class FXDragCorner
class FXDrawable
class FXDriveBox
class FXErrorException
struct FXEvent
class FXException
class FXExpression
class FXExtentd
class FXExtentf
class FXFile
struct FXFileAssoc
class FXFileDialog
class FXFileDict
class FXFileItem
class FXFileList
class FXFileSelector
class FXFileStream
class FXFoldingItem
class FXFoldingList
class FXFont
struct FXFontDesc
class FXFontDialog
class FXFontException
class FXFontSelector
class FXFrame
class FXGIFCursor
class FXGIFIcon
class FXGIFImage
class FXGLCanvas
class FXGLCone
class FXGLContext
class FXGLCube
class FXGLCylinder
class FXGLGroup
class FXGLLine
class FXGLObject
class FXGLPoint
class FXGLShape
class FXGLSphere
class FXGLTriangleMesh
class FXGLViewer
class FXGLVisual
struct FXGradient
class FXGradientBar
class FXGroupBox
class FXGUISignal
class FXHash
class FXHeader
class FXHeaderItem
struct FXHiliteStyle
class FXHorizontalFrame
class FXHorizontalSeparator
class FXICOIcon
class FXICOImage
class FXIcon
class FXIconDict
class FXIconItem
class FXIconList
class FXIconSource
class FXId
class FXIFFIcon
class FXIFFImage
class FXImage
class FXImageException
class FXImageFrame
class FXImageView
class FXInputDialog
class FXIO
class FXJPGIcon
class FXJPGImage
class FXKnob
class FXKOI8RCodec
class FXLabel
struct FXLight
class FXList
class FXListBox
class FXListItem
class FXMainWindow
class FXMat3d
class FXMat3f
class FXMat4d
class FXMat4f
struct FXMaterial
class FXMatrix
class FXMDIChild
class FXMDIClient
class FXMDIDeleteButton
class FXMDIMaximizeButton
class FXMDIMenu
class FXMDIMinimizeButton
class FXMDIRestoreButton
class FXMDIWindowButton
class FXMemMap
class FXMemoryException
class FXMemoryStream
class FXMenuBar
class FXMenuButton
class FXMenuCaption
class FXMenuCascade
class FXMenuCheck
class FXMenuCommand
class FXMenuPane
class FXMenuRadio
class FXMenuSeparator
class FXMenuTitle
class FXMessageBox
class FXMetaClass
class FXMutex
class FXMutexLock
class FXObject
class FXObjectList
class FXObjectListOf
class FXOption
class FXOptionMenu
class FXPacker
class FXPCXIcon
class FXPCXImage
class FXPicker
class FXPipe
class FXPNGIcon
class FXPNGImage
class FXPoint
class FXPointerException
class FXPopup
class FXPPMIcon
class FXPPMImage
class FXPrintDialog
struct FXPrinter
class FXProgressBar
class FXProgressDialog
struct FXPSBounds
class FXQuatd
class FXQuatf
class FXRadioButton
class FXRanged
class FXRangeException
class FXRangef
class FXRASIcon
class FXRASImage
class FXRealSlider
class FXRealSpinner
class FXRecentFiles
class FXRectangle
class FXRegion
class FXRegistry
class FXReplaceDialog
class FXResourceException
class FXRex
class FXRGBIcon
class FXRGBImage
class FXRootWindow
class FXRuler
class FXRulerView
class FXScrollArea
class FXScrollBar
class FXScrollCorner
class FXScrollPane
class FXScrollWindow
class FXSearchDialog
struct FXSegment
class FXSemaphore
class FXSeparator
class FXSettings
class FXShell
class FXShutter
class FXShutterItem
class FXSize
class FXSlider
class FXSocket
class FXSphered
class FXSpheref
class FXSpinner
class FXSplashWindow
class FXSplitter
class FXSpring
class FXStat
class FXStatusBar
class FXStatusLine
class FXStream
class FXString
class FXStringDict
class FXSwitcher
class FXTabBar
class FXTabBook
class FXTabItem
class FXTable
class FXTableItem
struct FXTablePos
struct FXTableRange
class FXText
struct FXTextChange
class FXTextCodec
class FXTextField
class FXTGAIcon
class FXTGAImage
class FXThread
class FXTIFIcon
class FXTIFImage
class FXToggleButton
class FXToolBar
class FXToolBarGrip
class FXToolBarShell
class FXToolBarTab
class FXToolTip
class FXTopWindow
class FXTranslator
class FXTreeItem
class FXTreeList
class FXTreeListBox
class FXTriStateButton
class FXUndoList
class FXUTF16BECodec
class FXUTF16Codec
class FXUTF16LECodec
class FXUTF32BECodec
class FXUTF32Codec
class FXUTF32LECodec
class FXUTF8Codec
class FXVec2d
class FXVec2f
class FXVec3d
class FXVec3f
class FXVec4d
class FXVec4f
class FXVerticalFrame
class FXVerticalSeparator
struct FXViewport
class FXVisual
class FXWindow
class FXWindowException
class FXWizard
class FXXBMIcon
class FXXBMImage
class FXXPMIcon
class FXXPMImage
Typedefs
typedef char FXchar
typedef unsigned char FXuchar
typedef FXuchar FXbool
typedef unsigned short FXushort
typedef short FXshort
typedef unsigned int FXuint
typedef int FXint
typedef float FXfloat
typedef double FXdouble
typedef FXObject * FXObjectPtr
typedef wchar_t FXwchar
typedef unsigned short FXnchar
typedef long FXival
typedef unsigned long FXuval
typedef unsigned long FXID
typedef long FXTime
typedef unsigned long FXPixel
typedef FXuint FXColor
typedef FXuint FXHotKey
typedef FXID FXDragType
typedef FXint FXInputHandle
typedef _XEvent FXRawEvent
typedef FXint(* FXFoldingListSortFunc) (const FXFoldingItem *, const FXFoldingItem *)
typedef FXObjectListOf< FXGLObject > FXGLObjectList
typedef FXbool(* FXZSortFunc) (FXfloat *&buffer, FXint &used, FXint &size)
typedef FXObjectListOf< FXHeaderItem > FXHeaderItemList
typedef FXint(* FXIconListSortFunc) (const FXIconItem *, const FXIconItem *)
typedef FXObjectListOf< FXIconItem > FXIconItemList
typedef FXint(* FXListSortFunc) (const FXListItem *, const FXListItem *)
typedef FXObjectListOf< FXListItem > FXListItemList
typedef FXuint FXSelector
typedef unsigned long FXThreadID
typedef FXint(* FXTreeListSortFunc) (const FXTreeItem *, const FXTreeItem *)
Enumerations
enum {
FOURSPLITTER_TRACKING = 0x00008000,
FOURSPLITTER_NORMAL = 0
}
enum {
SEVENSEGMENT_NORMAL = 0,
SEVENSEGMENT_SHADOW = 0x00080000
}
enum FXInputMode {
INPUT_NONE = 0,
INPUT_READ = 1,
INPUT_WRITE = 2,
INPUT_EXCEPT = 4
}
enum FXModality {
MODAL_FOR_NONE,
MODAL_FOR_WINDOW,
MODAL_FOR_POPUP
}
enum FXDefaultCursor {
DEF_ARROW_CURSOR,
DEF_RARROW_CURSOR,
DEF_TEXT_CURSOR,
DEF_HSPLIT_CURSOR,
DEF_VSPLIT_CURSOR,
DEF_XSPLIT_CURSOR,
DEF_SWATCH_CURSOR,
DEF_MOVE_CURSOR,
DEF_DRAGH_CURSOR,
DEF_DRAGV_CURSOR,
DEF_DRAGTL_CURSOR,
DEF_DRAGBR_CURSOR =DEF_DRAGTL_CURSOR,
DEF_DRAGTR_CURSOR,
DEF_DRAGBL_CURSOR =DEF_DRAGTR_CURSOR,
DEF_DNDSTOP_CURSOR,
DEF_DNDCOPY_CURSOR,
DEF_DNDMOVE_CURSOR,
DEF_DNDLINK_CURSOR,
DEF_CROSSHAIR_CURSOR,
DEF_CORNERNE_CURSOR,
DEF_CORNERNW_CURSOR,
DEF_CORNERSE_CURSOR,
DEF_CORNERSW_CURSOR,
DEF_HELP_CURSOR,
DEF_HAND_CURSOR,
DEF_ROTATE_CURSOR,
DEF_WAIT_CURSOR
}
enum {
ARROW_NONE = 0,
ARROW_UP = 0x00080000,
ARROW_DOWN = 0x00100000,
ARROW_LEFT = 0x00200000,
ARROW_RIGHT = 0x00400000,
ARROW_AUTO = 0x00800000,
ARROW_REPEAT = 0x01000000,
ARROW_AUTOGRAY = 0x02000000,
ARROW_AUTOHIDE = 0x04000000,
ARROW_TOOLBAR = 0x08000000,
ARROW_NORMAL = FRAME_RAISED|FRAME_THICK|ARROW_UP
}
enum {
BITMAP_KEEP = 0x00000001,
BITMAP_OWNED = 0x00000002,
BITMAP_SHMI = 0x00000020,
BITMAP_SHMP = 0x00000040
}
enum {
BITMAPVIEW_NORMAL = 0,
BITMAPVIEW_CENTER_X = 0,
BITMAPVIEW_LEFT = 0x00100000,
BITMAPVIEW_RIGHT = 0x00200000,
BITMAPVIEW_CENTER_Y = 0,
BITMAPVIEW_TOP = 0x00400000,
BITMAPVIEW_BOTTOM = 0x00800000
}
enum {
STATE_UP = 0,
STATE_DOWN = 1,
STATE_ENGAGED = 2,
STATE_UNCHECKED = STATE_UP,
STATE_CHECKED = STATE_ENGAGED
}
enum {
BUTTON_AUTOGRAY = 0x00800000,
BUTTON_AUTOHIDE = 0x01000000,
BUTTON_TOOLBAR = 0x02000000,
BUTTON_DEFAULT = 0x04000000,
BUTTON_INITIAL = 0x08000000,
BUTTON_NORMAL = (FRAME_RAISED|FRAME_THICK|JUSTIFY_NORMAL|ICON_BEFORE_TEXT)
}
enum {
CHECKBUTTON_AUTOGRAY = 0x00800000,
CHECKBUTTON_AUTOHIDE = 0x01000000,
CHECKBUTTON_PLUS = 0x02000000,
CHECKBUTTON_NORMAL = JUSTIFY_NORMAL|ICON_BEFORE_TEXT
}
enum {
COLORBAR_HORIZONTAL = 0,
COLORBAR_VERTICAL = 0x00008000
}
enum {
COLORWELL_OPAQUEONLY = 0x00008000,
COLORWELL_SOURCEONLY = 0x00010000,
COLORWELL_NORMAL = JUSTIFY_NORMAL
}
enum {
COMBOBOX_NO_REPLACE = 0,
COMBOBOX_REPLACE = 0x00020000,
COMBOBOX_INSERT_BEFORE = 0x00040000,
COMBOBOX_INSERT_AFTER = 0x00060000,
COMBOBOX_INSERT_FIRST = 0x00080000,
COMBOBOX_INSERT_LAST = 0x000A0000,
COMBOBOX_STATIC = 0x00100000,
COMBOBOX_NORMAL = 0
}
enum FXStockCursor {
CURSOR_ARROW =1,
CURSOR_RARROW,
CURSOR_IBEAM,
CURSOR_WATCH,
CURSOR_CROSS,
CURSOR_UPDOWN,
CURSOR_LEFTRIGHT,
CURSOR_MOVE
}
enum {
CURSOR_KEEP = 0x00000100,
CURSOR_OWNED = 0x00000200
}
enum FXFunction {
BLT_CLR,
BLT_SRC_AND_DST,
BLT_SRC_AND_NOT_DST,
BLT_SRC,
BLT_NOT_SRC_AND_DST,
BLT_DST,
BLT_SRC_XOR_DST,
BLT_SRC_OR_DST,
BLT_NOT_SRC_AND_NOT_DST,
BLT_NOT_SRC_XOR_DST,
BLT_NOT_DST,
BLT_SRC_OR_NOT_DST,
BLT_NOT_SRC,
BLT_NOT_SRC_OR_DST,
BLT_NOT_SRC_OR_NOT_DST,
BLT_SET
}
enum FXLineStyle {
LINE_SOLID,
LINE_ONOFF_DASH,
LINE_DOUBLE_DASH
}
enum FXCapStyle {
CAP_NOT_LAST,
CAP_BUTT,
CAP_ROUND,
CAP_PROJECTING
}
enum FXJoinStyle {
JOIN_MITER,
JOIN_ROUND,
JOIN_BEVEL
}
enum FXFillStyle {
FILL_SOLID,
FILL_TILED,
FILL_STIPPLED,
FILL_OPAQUESTIPPLED
}
enum FXFillRule {
RULE_EVEN_ODD,
RULE_WINDING
}
enum FXStipplePattern {
STIPPLE_0 = 0,
STIPPLE_NONE = 0,
STIPPLE_BLACK = 0,
STIPPLE_1 = 1,
STIPPLE_2 = 2,
STIPPLE_3 = 3,
STIPPLE_4 = 4,
STIPPLE_5 = 5,
STIPPLE_6 = 6,
STIPPLE_7 = 7,
STIPPLE_8 = 8,
STIPPLE_GRAY = 8,
STIPPLE_9 = 9,
STIPPLE_10 = 10,
STIPPLE_11 = 11,
STIPPLE_12 = 12,
STIPPLE_13 = 13,
STIPPLE_14 = 14,
STIPPLE_15 = 15,
STIPPLE_16 = 16,
STIPPLE_WHITE = 16,
STIPPLE_HORZ = 17,
STIPPLE_VERT = 18,
STIPPLE_CROSS = 19,
STIPPLE_DIAG = 20,
STIPPLE_REVDIAG = 21,
STIPPLE_CROSSDIAG = 22
}
enum FXPrintFlags {
PRINT_DEST_PAPER = 0,
PRINT_DEST_FILE = 1,
PRINT_PAGES_ALL = 0,
PRINT_PAGES_EVEN = 2,
PRINT_PAGES_ODD = 4,
PRINT_PAGES_RANGE = 8,
PRINT_COLLATE_NORMAL = 0,
PRINT_COLLATE_REVERSED = 16,
PRINT_PORTRAIT = 0,
PRINT_LANDSCAPE = 32,
PRINT_BLACKANDWHITE = 0,
PRINT_COLOR = 64,
PRINT_NOBOUNDS = 128
}
enum FXMediaSize {
MEDIA_CUSTOM = 0,
MEDIA_USLETTER = 1,
MEDIA_LEGAL = 2,
MEDIA_A4 = 3,
MEDIA_ENVELOPE = 4
}
enum FXSelType {
SEL_NONE,
SEL_KEYPRESS,
SEL_KEYRELEASE,
SEL_LEFTBUTTONPRESS,
SEL_LEFTBUTTONRELEASE,
SEL_MIDDLEBUTTONPRESS,
SEL_MIDDLEBUTTONRELEASE,
SEL_RIGHTBUTTONPRESS,
SEL_RIGHTBUTTONRELEASE,
SEL_MOTION,
SEL_ENTER,
SEL_LEAVE,
SEL_FOCUSIN,
SEL_FOCUSOUT,
SEL_KEYMAP,
SEL_UNGRABBED,
SEL_PAINT,
SEL_CREATE,
SEL_DESTROY,
SEL_UNMAP,
SEL_MAP,
SEL_CONFIGURE,
SEL_SELECTION_LOST,
SEL_SELECTION_GAINED,
SEL_SELECTION_REQUEST,
SEL_RAISED,
SEL_LOWERED,
SEL_CLOSE,
SEL_DELETE,
SEL_MINIMIZE,
SEL_RESTORE,
SEL_MAXIMIZE,
SEL_UPDATE,
SEL_COMMAND,
SEL_CLICKED,
SEL_DOUBLECLICKED,
SEL_TRIPLECLICKED,
SEL_MOUSEWHEEL,
SEL_CHANGED,
SEL_VERIFY,
SEL_DESELECTED,
SEL_SELECTED,
SEL_INSERTED,
SEL_REPLACED,
SEL_DELETED,
SEL_OPENED,
SEL_CLOSED,
SEL_EXPANDED,
SEL_COLLAPSED,
SEL_BEGINDRAG,
SEL_ENDDRAG,
SEL_DRAGGED,
SEL_LASSOED,
SEL_TIMEOUT,
SEL_SIGNAL,
SEL_CLIPBOARD_LOST,
SEL_CLIPBOARD_GAINED,
SEL_CLIPBOARD_REQUEST,
SEL_CHORE,
SEL_FOCUS_SELF,
SEL_FOCUS_RIGHT,
SEL_FOCUS_LEFT,
SEL_FOCUS_DOWN,
SEL_FOCUS_UP,
SEL_FOCUS_NEXT,
SEL_FOCUS_PREV,
SEL_DND_ENTER,
SEL_DND_LEAVE,
SEL_DND_DROP,
SEL_DND_MOTION,
SEL_DND_REQUEST,
SEL_IO_READ,
SEL_IO_WRITE,
SEL_IO_EXCEPT,
SEL_PICKED,
SEL_QUERY_TIP,
SEL_QUERY_HELP,
SEL_DOCKED,
SEL_FLOATED,
SEL_SESSION_NOTIFY,
SEL_SESSION_CLOSED,
SEL_LAST
}
enum {
SHIFTMASK = 0x001,
CAPSLOCKMASK = 0x002,
CONTROLMASK = 0x004,
ALTMASK = 0x008,
METAMASK = 0x040,
NUMLOCKMASK = 0x010,
SCROLLLOCKMASK = 0x0E0,
LEFTBUTTONMASK = 0x100,
MIDDLEBUTTONMASK = 0x200,
RIGHTBUTTONMASK = 0x400
}
enum {
LEFTBUTTON = 1,
MIDDLEBUTTON = 2,
RIGHTBUTTON = 3
}
enum {
CROSSINGNORMAL,
CROSSINGGRAB,
CROSSINGUNGRAB
}
enum {
VISIBILITYTOTAL,
VISIBILITYPARTIAL,
VISIBILITYNONE
}
enum {
FILEMATCH_FILE_NAME = 1,
FILEMATCH_NOESCAPE = 2,
FILEMATCH_PERIOD = 4,
FILEMATCH_LEADING_DIR = 8,
FILEMATCH_CASEFOLD = 16
}
enum FXDragAction {
DRAG_REJECT = 0,
DRAG_ACCEPT = 1,
DRAG_COPY = 2,
DRAG_MOVE = 3,
DRAG_LINK = 4,
DRAG_PRIVATE = 5
}
enum FXDNDOrigin {
FROM_SELECTION = 0,
FROM_CLIPBOARD = 1,
FROM_DRAGNDROP = 2
}
enum FXExponent {
EXP_NEVER =FALSE,
EXP_ALWAYS =TRUE,
EXP_AUTO =MAYBE
}
enum {
SEARCH_FORWARD = 0,
SEARCH_BACKWARD = 1,
SEARCH_NOWRAP = 0,
SEARCH_WRAP = 2,
SEARCH_EXACT = 0,
SEARCH_IGNORECASE = 4,
SEARCH_REGEX = 8,
SEARCH_PREFIX = 16
}
enum {
DIAL_VERTICAL = 0,
DIAL_HORIZONTAL = 0x00008000,
DIAL_CYCLIC = 0x00010000,
DIAL_HAS_NOTCH = 0x00020000,
DIAL_NORMAL = DIAL_VERTICAL
}
enum { DIRBOX_NO_OWN_ASSOC = 0x00020000 }
enum {
DIRLIST_SHOWFILES = 0x08000000,
DIRLIST_SHOWHIDDEN = 0x10000000,
DIRLIST_NO_OWN_ASSOC = 0x20000000
}
enum {
DOCKSITE_WRAP = 0,
DOCKSITE_NO_WRAP = 0x00020000
}
enum { DRIVEBOX_NO_OWN_ASSOC = 0x00020000 }
enum FXExpressionError {
EXPRERR_OK,
EXPRERR_EMPTY,
EXPRERR_MEMORY,
EXPRERR_PAREN,
EXPRERR_TOKEN,
EXPRERR_COMMA,
EXPRERR_IDENT
}
enum {
FILELIST_SHOWHIDDEN = 0x04000000,
FILELIST_SHOWDIRS = 0x08000000,
FILELIST_SHOWFILES = 0x10000000,
FILELIST_SHOWIMAGES = 0x20000000,
FILELIST_NO_OWN_ASSOC = 0x40000000,
FILELIST_NO_PARENT = 0x80000000
}
enum {
SELECTFILE_ANY,
SELECTFILE_EXISTING,
SELECTFILE_MULTIPLE,
SELECTFILE_MULTIPLE_ALL,
SELECTFILE_DIRECTORY
}
enum {
FOLDINGLIST_EXTENDEDSELECT = 0,
FOLDINGLIST_SINGLESELECT = 0x00100000,
FOLDINGLIST_BROWSESELECT = 0x00200000,
FOLDINGLIST_MULTIPLESELECT = 0x00300000,
FOLDINGLIST_AUTOSELECT = 0x00400000,
FOLDINGLIST_SHOWS_LINES = 0x00800000,
FOLDINGLIST_SHOWS_BOXES = 0x01000000,
FOLDINGLIST_ROOT_BOXES = 0x02000000,
FOLDINGLIST_NORMAL = FOLDINGLIST_EXTENDEDSELECT
}
enum FXFontEncoding {
FONTENCODING_DEFAULT,
FONTENCODING_ISO_8859_1 = 1,
FONTENCODING_ISO_8859_2 = 2,
FONTENCODING_ISO_8859_3 = 3,
FONTENCODING_ISO_8859_4 = 4,
FONTENCODING_ISO_8859_5 = 5,
FONTENCODING_ISO_8859_6 = 6,
FONTENCODING_ISO_8859_7 = 7,
FONTENCODING_ISO_8859_8 = 8,
FONTENCODING_ISO_8859_9 = 9,
FONTENCODING_ISO_8859_10 = 10,
FONTENCODING_ISO_8859_11 = 11,
FONTENCODING_ISO_8859_13 = 13,
FONTENCODING_ISO_8859_14 = 14,
FONTENCODING_ISO_8859_15 = 15,
FONTENCODING_ISO_8859_16 = 16,
FONTENCODING_KOI8 = 17,
FONTENCODING_KOI8_R = 18,
FONTENCODING_KOI8_U = 19,
FONTENCODING_KOI8_UNIFIED = 20,
FONTENCODING_CP437 = 437,
FONTENCODING_CP850 = 850,
FONTENCODING_CP851 = 851,
FONTENCODING_CP852 = 852,
FONTENCODING_CP855 = 855,
FONTENCODING_CP856 = 856,
FONTENCODING_CP857 = 857,
FONTENCODING_CP860 = 860,
FONTENCODING_CP861 = 861,
FONTENCODING_CP862 = 862,
FONTENCODING_CP863 = 863,
FONTENCODING_CP864 = 864,
FONTENCODING_CP865 = 865,
FONTENCODING_CP866 = 866,
FONTENCODING_CP869 = 869,
FONTENCODING_CP870 = 870,
FONTENCODING_CP1250 = 1250,
FONTENCODING_CP1251 = 1251,
FONTENCODING_CP1252 = 1252,
FONTENCODING_CP1253 = 1253,
FONTENCODING_CP1254 = 1254,
FONTENCODING_CP1255 = 1255,
FONTENCODING_CP1256 = 1256,
FONTENCODING_CP1257 = 1257,
FONTENCODING_CP1258 = 1258,
FONTENCODING_CP874 = 874,
FONTENCODING_UNICODE = 9999,
FONTENCODING_LATIN1 = FONTENCODING_ISO_8859_1,
FONTENCODING_LATIN2 = FONTENCODING_ISO_8859_2,
FONTENCODING_LATIN3 = FONTENCODING_ISO_8859_3,
FONTENCODING_LATIN4 = FONTENCODING_ISO_8859_4,
FONTENCODING_LATIN5 = FONTENCODING_ISO_8859_9,
FONTENCODING_LATIN6 = FONTENCODING_ISO_8859_10,
FONTENCODING_LATIN7 = FONTENCODING_ISO_8859_13,
FONTENCODING_LATIN8 = FONTENCODING_ISO_8859_14,
FONTENCODING_LATIN9 = FONTENCODING_ISO_8859_15,
FONTENCODING_LATIN10 = FONTENCODING_ISO_8859_16,
FONTENCODING_USASCII = FONTENCODING_ISO_8859_1,
FONTENCODING_WESTEUROPE = FONTENCODING_ISO_8859_1,
FONTENCODING_EASTEUROPE = FONTENCODING_ISO_8859_2,
FONTENCODING_SOUTHEUROPE = FONTENCODING_ISO_8859_3,
FONTENCODING_NORTHEUROPE = FONTENCODING_ISO_8859_4,
FONTENCODING_CYRILLIC = FONTENCODING_ISO_8859_5,
FONTENCODING_RUSSIAN = FONTENCODING_KOI8,
FONTENCODING_ARABIC = FONTENCODING_ISO_8859_6,
FONTENCODING_GREEK = FONTENCODING_ISO_8859_7,
FONTENCODING_HEBREW = FONTENCODING_ISO_8859_8,
FONTENCODING_TURKISH = FONTENCODING_ISO_8859_9,
FONTENCODING_NORDIC = FONTENCODING_ISO_8859_10,
FONTENCODING_THAI = FONTENCODING_ISO_8859_11,
FONTENCODING_BALTIC = FONTENCODING_ISO_8859_13,
FONTENCODING_CELTIC = FONTENCODING_ISO_8859_14
}
enum {
JUSTIFY_NORMAL = 0,
JUSTIFY_CENTER_X = 0,
JUSTIFY_LEFT = 0x00008000,
JUSTIFY_RIGHT = 0x00010000,
JUSTIFY_HZ_APART = JUSTIFY_LEFT|JUSTIFY_RIGHT,
JUSTIFY_CENTER_Y = 0,
JUSTIFY_TOP = 0x00020000,
JUSTIFY_BOTTOM = 0x00040000,
JUSTIFY_VT_APART = JUSTIFY_TOP|JUSTIFY_BOTTOM
}
enum { DEFAULT_PAD = 2 }
enum {
SURFACE_SINGLESIDED = 0,
SURFACE_DUALSIDED = 0x00000001,
SHADING_NONE = 0,
SHADING_SMOOTH = 0x00000002,
SHADING_FLAT = 0x00000004,
FACECULLING_OFF = 0,
FACECULLING_ON = 0x00000008,
STYLE_SURFACE = 0x00000010,
STYLE_WIREFRAME = 0x00000020,
STYLE_POINTS = 0x00000040,
STYLE_BOUNDBOX = 0x00000080
}
enum {
VIEWER_LIGHTING = 0x00008000,
VIEWER_FOG = 0x00010000,
VIEWER_DITHER = 0x00020000
}
enum {
GRADIENTBAR_HORIZONTAL = 0,
GRADIENTBAR_VERTICAL = 0x00008000,
GRADIENTBAR_NO_CONTROLS = 0,
GRADIENTBAR_CONTROLS_TOP = 0x00010000,
GRADIENTBAR_CONTROLS_BOTTOM = 0x00020000,
GRADIENTBAR_CONTROLS_LEFT = GRADIENTBAR_CONTROLS_TOP,
GRADIENTBAR_CONTROLS_RIGHT = GRADIENTBAR_CONTROLS_BOTTOM
}
enum {
GRADIENT_BLEND_LINEAR,
GRADIENT_BLEND_POWER,
GRADIENT_BLEND_SINE,
GRADIENT_BLEND_INCREASING,
GRADIENT_BLEND_DECREASING
}
enum {
GROUPBOX_TITLE_LEFT = 0,
GROUPBOX_TITLE_CENTER = 0x00020000,
GROUPBOX_TITLE_RIGHT = 0x00040000,
GROUPBOX_NORMAL = GROUPBOX_TITLE_LEFT
}
enum {
HEADER_BUTTON = 0x00008000,
HEADER_HORIZONTAL = 0,
HEADER_VERTICAL = 0x00010000,
HEADER_TRACKING = 0x00020000,
HEADER_RESIZE = 0x00040000,
HEADER_NORMAL = HEADER_HORIZONTAL|FRAME_NORMAL
}
enum {
ICONLIST_EXTENDEDSELECT = 0,
ICONLIST_SINGLESELECT = 0x00100000,
ICONLIST_BROWSESELECT = 0x00200000,
ICONLIST_MULTIPLESELECT = 0x00300000,
ICONLIST_AUTOSIZE = 0x00400000,
ICONLIST_DETAILED = 0,
ICONLIST_MINI_ICONS = 0x00800000,
ICONLIST_BIG_ICONS = 0x01000000,
ICONLIST_ROWS = 0,
ICONLIST_COLUMNS = 0x02000000,
ICONLIST_NORMAL = ICONLIST_EXTENDEDSELECT
}
enum {
IMAGE_KEEP = 0x00000001,
IMAGE_OWNED = 0x00000002,
IMAGE_DITHER = 0,
IMAGE_NEAREST = 0x00000004,
IMAGE_OPAQUE = 0x00000008,
IMAGE_ALPHACOLOR = 0x00000010,
IMAGE_SHMI = 0x00000020,
IMAGE_SHMP = 0x00000040,
IMAGE_ALPHAGUESS = 0x00000080
}
enum {
IMAGEVIEW_NORMAL = 0,
IMAGEVIEW_CENTER_X = 0,
IMAGEVIEW_LEFT = 0x00100000,
IMAGEVIEW_RIGHT = 0x00200000,
IMAGEVIEW_CENTER_Y = 0,
IMAGEVIEW_TOP = 0x00400000,
IMAGEVIEW_BOTTOM = 0x00800000
}
enum {
INPUTDIALOG_STRING = 0,
INPUTDIALOG_INTEGER = 0x01000000,
INPUTDIALOG_REAL = 0x02000000,
INPUTDIALOG_PASSWORD = 0x04000000
}
enum {
KEY_VoidSymbol = 0,
KEY_BackSpace = 0xFF08,
KEY_Tab = 0xFF09,
KEY_Linefeed = 0xFF0A,
KEY_Clear = 0xFF0B,
KEY_Return = 0xFF0D,
KEY_Pause = 0xFF13,
KEY_Scroll_Lock = 0xFF14,
KEY_Sys_Req = 0xFF15,
KEY_Escape = 0xFF1B,
KEY_Delete = 0xFFFF,
KEY_Multi_key = 0xFF20,
KEY_Kanji = 0xFF21,
KEY_Muhenkan = 0xFF22,
KEY_Henkan_Mode = 0xFF23,
KEY_Henkan = 0xFF23,
KEY_Romaji = 0xFF24,
KEY_Hiragana = 0xFF25,
KEY_Katakana = 0xFF26,
KEY_Hiragana_Katakana = 0xFF27,
KEY_Zenkaku = 0xFF28,
KEY_Hankaku = 0xFF29,
KEY_Zenkaku_Hankaku = 0xFF2A,
KEY_Touroku = 0xFF2B,
KEY_Massyo = 0xFF2C,
KEY_Kana_Lock = 0xFF2D,
KEY_Kana_Shift = 0xFF2E,
KEY_Eisu_Shift = 0xFF2F,
KEY_Eisu_toggle = 0xFF30,
KEY_Home = 0xFF50,
KEY_Left = 0xFF51,
KEY_Up = 0xFF52,
KEY_Right = 0xFF53,
KEY_Down = 0xFF54,
KEY_Prior = 0xFF55,
KEY_Page_Up = 0xFF55,
KEY_Next = 0xFF56,
KEY_Page_Down = 0xFF56,
KEY_End = 0xFF57,
KEY_Begin = 0xFF58,
KEY_Select = 0xFF60,
KEY_Print = 0xFF61,
KEY_Execute = 0xFF62,
KEY_Insert = 0xFF63,
KEY_Undo = 0xFF65,
KEY_Redo = 0xFF66,
KEY_Menu = 0xFF67,
KEY_Find = 0xFF68,
KEY_Cancel = 0xFF69,
KEY_Help = 0xFF6A,
KEY_Break = 0xFF6B,
KEY_Mode_switch = 0xFF7E,
KEY_script_switch = 0xFF7E,
KEY_Num_Lock = 0xFF7F,
KEY_KP_Space = 0xFF80,
KEY_KP_Tab = 0xFF89,
KEY_KP_Enter = 0xFF8D,
KEY_KP_F1 = 0xFF91,
KEY_KP_F2 = 0xFF92,
KEY_KP_F3 = 0xFF93,
KEY_KP_F4 = 0xFF94,
KEY_KP_Home = 0xFF95,
KEY_KP_Left = 0xFF96,
KEY_KP_Up = 0xFF97,
KEY_KP_Right = 0xFF98,
KEY_KP_Down = 0xFF99,
KEY_KP_Prior = 0xFF9A,
KEY_KP_Page_Up = 0xFF9A,
KEY_KP_Next = 0xFF9B,
KEY_KP_Page_Down = 0xFF9B,
KEY_KP_End = 0xFF9C,
KEY_KP_Begin = 0xFF9D,
KEY_KP_Insert = 0xFF9E,
KEY_KP_Delete = 0xFF9F,
KEY_KP_Equal = 0xFFBD,
KEY_KP_Multiply = 0xFFAA,
KEY_KP_Add = 0xFFAB,
KEY_KP_Separator = 0xFFAC,
KEY_KP_Subtract = 0xFFAD,
KEY_KP_Decimal = 0xFFAE,
KEY_KP_Divide = 0xFFAF,
KEY_KP_0 = 0xFFB0,
KEY_KP_1 = 0xFFB1,
KEY_KP_2 = 0xFFB2,
KEY_KP_3 = 0xFFB3,
KEY_KP_4 = 0xFFB4,
KEY_KP_5 = 0xFFB5,
KEY_KP_6 = 0xFFB6,
KEY_KP_7 = 0xFFB7,
KEY_KP_8 = 0xFFB8,
KEY_KP_9 = 0xFFB9,
KEY_F1 = 0xFFBE,
KEY_F2 = 0xFFBF,
KEY_F3 = 0xFFC0,
KEY_F4 = 0xFFC1,
KEY_F5 = 0xFFC2,
KEY_F6 = 0xFFC3,
KEY_F7 = 0xFFC4,
KEY_F8 = 0xFFC5,
KEY_F9 = 0xFFC6,
KEY_F10 = 0xFFC7,
KEY_F11 = 0xFFC8,
KEY_L1 = 0xFFC8,
KEY_F12 = 0xFFC9,
KEY_L2 = 0xFFC9,
KEY_F13 = 0xFFCA,
KEY_L3 = 0xFFCA,
KEY_F14 = 0xFFCB,
KEY_L4 = 0xFFCB,
KEY_F15 = 0xFFCC,
KEY_L5 = 0xFFCC,
KEY_F16 = 0xFFCD,
KEY_L6 = 0xFFCD,
KEY_F17 = 0xFFCE,
KEY_L7 = 0xFFCE,
KEY_F18 = 0xFFCF,
KEY_L8 = 0xFFCF,
KEY_F19 = 0xFFD0,
KEY_L9 = 0xFFD0,
KEY_F20 = 0xFFD1,
KEY_L10 = 0xFFD1,
KEY_F21 = 0xFFD2,
KEY_R1 = 0xFFD2,
KEY_F22 = 0xFFD3,
KEY_R2 = 0xFFD3,
KEY_F23 = 0xFFD4,
KEY_R3 = 0xFFD4,
KEY_F24 = 0xFFD5,
KEY_R4 = 0xFFD5,
KEY_F25 = 0xFFD6,
KEY_R5 = 0xFFD6,
KEY_F26 = 0xFFD7,
KEY_R6 = 0xFFD7,
KEY_F27 = 0xFFD8,
KEY_R7 = 0xFFD8,
KEY_F28 = 0xFFD9,
KEY_R8 = 0xFFD9,
KEY_F29 = 0xFFDA,
KEY_R9 = 0xFFDA,
KEY_F30 = 0xFFDB,
KEY_R10 = 0xFFDB,
KEY_F31 = 0xFFDC,
KEY_R11 = 0xFFDC,
KEY_F32 = 0xFFDD,
KEY_R12 = 0xFFDD,
KEY_F33 = 0xFFDE,
KEY_R13 = 0xFFDE,
KEY_F34 = 0xFFDF,
KEY_R14 = 0xFFDF,
KEY_F35 = 0xFFE0,
KEY_R15 = 0xFFE0,
KEY_Shift_L = 0xFFE1,
KEY_Shift_R = 0xFFE2,
KEY_Control_L = 0xFFE3,
KEY_Control_R = 0xFFE4,
KEY_Caps_Lock = 0xFFE5,
KEY_Shift_Lock = 0xFFE6,
KEY_Meta_L = 0xFFE7,
KEY_Meta_R = 0xFFE8,
KEY_Alt_L = 0xFFE9,
KEY_Alt_R = 0xFFEA,
KEY_Super_L = 0xFFEB,
KEY_Super_R = 0xFFEC,
KEY_Hyper_L = 0xFFED,
KEY_Hyper_R = 0xFFEE,
KEY_ISO_Lock = 0xFE01,
KEY_ISO_Level2_Latch = 0xFE02,
KEY_ISO_Level3_Shift = 0xFE03,
KEY_ISO_Level3_Latch = 0xFE04,
KEY_ISO_Level3_Lock = 0xFE05,
KEY_ISO_Group_Shift = 0xFF7E,
KEY_ISO_Group_Latch = 0xFE06,
KEY_ISO_Group_Lock = 0xFE07,
KEY_ISO_Next_Group = 0xFE08,
KEY_ISO_Next_Group_Lock = 0xFE09,
KEY_ISO_Prev_Group = 0xFE0A,
KEY_ISO_Prev_Group_Lock = 0xFE0B,
KEY_ISO_First_Group = 0xFE0C,
KEY_ISO_First_Group_Lock = 0xFE0D,
KEY_ISO_Last_Group = 0xFE0E,
KEY_ISO_Last_Group_Lock = 0xFE0F,
KEY_ISO_Left_Tab = 0xFE20,
KEY_ISO_Move_Line_Up = 0xFE21,
KEY_ISO_Move_Line_Down = 0xFE22,
KEY_ISO_Partial_Line_Up = 0xFE23,
KEY_ISO_Partial_Line_Down = 0xFE24,
KEY_ISO_Partial_Space_Left = 0xFE25,
KEY_ISO_Partial_Space_Right = 0xFE26,
KEY_ISO_Set_Margin_Left = 0xFE27,
KEY_ISO_Set_Margin_Right = 0xFE28,
KEY_ISO_Release_Margin_Left = 0xFE29,
KEY_ISO_Release_Margin_Right = 0xFE2A,
KEY_ISO_Release_Both_Margins = 0xFE2B,
KEY_ISO_Fast_Cursor_Left = 0xFE2C,
KEY_ISO_Fast_Cursor_Right = 0xFE2D,
KEY_ISO_Fast_Cursor_Up = 0xFE2E,
KEY_ISO_Fast_Cursor_Down = 0xFE2F,
KEY_ISO_Continuous_Underline = 0xFE30,
KEY_ISO_Discontinuous_Underline = 0xFE31,
KEY_ISO_Emphasize = 0xFE32,
KEY_ISO_Center_Object = 0xFE33,
KEY_ISO_Enter = 0xFE34,
KEY_dead_grave = 0xFE50,
KEY_dead_acute = 0xFE51,
KEY_dead_circumflex = 0xFE52,
KEY_dead_tilde = 0xFE53,
KEY_dead_macron = 0xFE54,
KEY_dead_breve = 0xFE55,
KEY_dead_abovedot = 0xFE56,
KEY_dead_diaeresis = 0xFE57,
KEY_dead_abovering = 0xFE58,
KEY_dead_doubleacute = 0xFE59,
KEY_dead_caron = 0xFE5A,
KEY_dead_cedilla = 0xFE5B,
KEY_dead_ogonek = 0xFE5C,
KEY_dead_iota = 0xFE5D,
KEY_dead_voiced_sound = 0xFE5E,
KEY_dead_semivoiced_sound = 0xFE5F,
KEY_dead_belowdot = 0xFE60,
KEY_First_Virtual_Screen = 0xFED0,
KEY_Prev_Virtual_Screen = 0xFED1,
KEY_Next_Virtual_Screen = 0xFED2,
KEY_Last_Virtual_Screen = 0xFED4,
KEY_Terminate_Server = 0xFED5,
KEY_AccessX_Enable = 0xFE70,
KEY_AccessX_Feedback_Enable = 0xFE71,
KEY_RepeatKeys_Enable = 0xFE72,
KEY_SlowKeys_Enable = 0xFE73,
KEY_BounceKeys_Enable = 0xFE74,
KEY_StickyKeys_Enable = 0xFE75,
KEY_MouseKeys_Enable = 0xFE76,
KEY_MouseKeys_Accel_Enable = 0xFE77,
KEY_Overlay1_Enable = 0xFE78,
KEY_Overlay2_Enable = 0xFE79,
KEY_AudibleBell_Enable = 0xFE7A,
KEY_Pointer_Left = 0xFEE0,
KEY_Pointer_Right = 0xFEE1,
KEY_Pointer_Up = 0xFEE2,
KEY_Pointer_Down = 0xFEE3,
KEY_Pointer_UpLeft = 0xFEE4,
KEY_Pointer_UpRight = 0xFEE5,
KEY_Pointer_DownLeft = 0xFEE6,
KEY_Pointer_DownRight = 0xFEE7,
KEY_Pointer_Button_Dflt = 0xFEE8,
KEY_Pointer_Button1 = 0xFEE9,
KEY_Pointer_Button2 = 0xFEEA,
KEY_Pointer_Button3 = 0xFEEB,
KEY_Pointer_Button4 = 0xFEEC,
KEY_Pointer_Button5 = 0xFEED,
KEY_Pointer_DblClick_Dflt = 0xFEEE,
KEY_Pointer_DblClick1 = 0xFEEF,
KEY_Pointer_DblClick2 = 0xFEF0,
KEY_Pointer_DblClick3 = 0xFEF1,
KEY_Pointer_DblClick4 = 0xFEF2,
KEY_Pointer_DblClick5 = 0xFEF3,
KEY_Pointer_Drag_Dflt = 0xFEF4,
KEY_Pointer_Drag1 = 0xFEF5,
KEY_Pointer_Drag2 = 0xFEF6,
KEY_Pointer_Drag3 = 0xFEF7,
KEY_Pointer_Drag4 = 0xFEF8,
KEY_Pointer_Drag5 = 0xFEFD,
KEY_Pointer_EnableKeys = 0xFEF9,
KEY_Pointer_Accelerate = 0xFEFA,
KEY_Pointer_DfltBtnNext = 0xFEFB,
KEY_Pointer_DfltBtnPrev = 0xFEFC,
KEY_3270_Duplicate = 0xFD01,
KEY_3270_FieldMark = 0xFD02,
KEY_3270_Right2 = 0xFD03,
KEY_3270_Left2 = 0xFD04,
KEY_3270_BackTab = 0xFD05,
KEY_3270_EraseEOF = 0xFD06,
KEY_3270_EraseInput = 0xFD07,
KEY_3270_Reset = 0xFD08,
KEY_3270_Quit = 0xFD09,
KEY_3270_PA1 = 0xFD0A,
KEY_3270_PA2 = 0xFD0B,
KEY_3270_PA3 = 0xFD0C,
KEY_3270_Test = 0xFD0D,
KEY_3270_Attn = 0xFD0E,
KEY_3270_CursorBlink = 0xFD0F,
KEY_3270_AltCursor = 0xFD10,
KEY_3270_KeyClick = 0xFD11,
KEY_3270_Jump = 0xFD12,
KEY_3270_Ident = 0xFD13,
KEY_3270_Rule = 0xFD14,
KEY_3270_Copy = 0xFD15,
KEY_3270_Play = 0xFD16,
KEY_3270_Setup = 0xFD17,
KEY_3270_Record = 0xFD18,
KEY_3270_ChangeScreen = 0xFD19,
KEY_3270_DeleteWord = 0xFD1A,
KEY_3270_ExSelect = 0xFD1B,
KEY_3270_CursorSelect = 0xFD1C,
KEY_3270_PrintScreen = 0xFD1D,
KEY_3270_Enter = 0xFD1E,
KEY_space = 0x0020,
KEY_exclam = 0x0021,
KEY_quotedbl = 0x0022,
KEY_numbersign = 0x0023,
KEY_dollar = 0x0024,
KEY_percent = 0x0025,
KEY_ampersand = 0x0026,
KEY_apostrophe = 0x0027,
KEY_quoteright = 0x0027,
KEY_parenleft = 0x0028,
KEY_parenright = 0x0029,
KEY_asterisk = 0x002A,
KEY_plus = 0x002B,
KEY_comma = 0x002C,
KEY_minus = 0x002D,
KEY_period = 0x002E,
KEY_slash = 0x002F,
KEY_0 = 0x0030,
KEY_1 = 0x0031,
KEY_2 = 0x0032,
KEY_3 = 0x0033,
KEY_4 = 0x0034,
KEY_5 = 0x0035,
KEY_6 = 0x0036,
KEY_7 = 0x0037,
KEY_8 = 0x0038,
KEY_9 = 0x0039,
KEY_colon = 0x003A,
KEY_semicolon = 0x003B,
KEY_less = 0x003C,
KEY_equal = 0x003D,
KEY_greater = 0x003E,
KEY_question = 0x003F,
KEY_at = 0x0040,
KEY_A = 0x0041,
KEY_B = 0x0042,
KEY_C = 0x0043,
KEY_D = 0x0044,
KEY_E = 0x0045,
KEY_F = 0x0046,
KEY_G = 0x0047,
KEY_H = 0x0048,
KEY_I = 0x0049,
KEY_J = 0x004A,
KEY_K = 0x004B,
KEY_L = 0x004C,
KEY_M = 0x004D,
KEY_N = 0x004E,
KEY_O = 0x004F,
KEY_P = 0x0050,
KEY_Q = 0x0051,
KEY_R = 0x0052,
KEY_S = 0x0053,
KEY_T = 0x0054,
KEY_U = 0x0055,
KEY_V = 0x0056,
KEY_W = 0x0057,
KEY_X = 0x0058,
KEY_Y = 0x0059,
KEY_Z = 0x005A,
KEY_bracketleft = 0x005B,
KEY_backslash = 0x005C,
KEY_bracketright = 0x005D,
KEY_asciicircum = 0x005E,
KEY_underscore = 0x005F,
KEY_grave = 0x0060,
KEY_quoteleft = 0x0060,
KEY_a = 0x0061,
KEY_b = 0x0062,
KEY_c = 0x0063,
KEY_d = 0x0064,
KEY_e = 0x0065,
KEY_f = 0x0066,
KEY_g = 0x0067,
KEY_h = 0x0068,
KEY_i = 0x0069,
KEY_j = 0x006A,
KEY_k = 0x006B,
KEY_l = 0x006C,
KEY_m = 0x006D,
KEY_n = 0x006E,
KEY_o = 0x006F,
KEY_p = 0x0070,
KEY_q = 0x0071,
KEY_r = 0x0072,
KEY_s = 0x0073,
KEY_t = 0x0074,
KEY_u = 0x0075,
KEY_v = 0x0076,
KEY_w = 0x0077,
KEY_x = 0x0078,
KEY_y = 0x0079,
KEY_z = 0x007A,
KEY_braceleft = 0x007B,
KEY_bar = 0x007C,
KEY_braceright = 0x007D,
KEY_asciitilde = 0x007E,
KEY_nobreakspace = 0x00A0,
KEY_exclamdown = 0x00A1,
KEY_cent = 0x00A2,
KEY_sterling = 0x00A3,
KEY_currency = 0x00A4,
KEY_yen = 0x00A5,
KEY_brokenbar = 0x00A6,
KEY_section = 0x00A7,
KEY_diaeresis = 0x00A8,
KEY_copyright = 0x00A9,
KEY_ordfeminine = 0x00AA,
KEY_guillemotleft = 0x00AB,
KEY_notsign = 0x00AC,
KEY_hyphen = 0x00AD,
KEY_registered = 0x00AE,
KEY_macron = 0x00AF,
KEY_degree = 0x00B0,
KEY_plusminus = 0x00B1,
KEY_twosuperior = 0x00B2,
KEY_threesuperior = 0x00B3,
KEY_acute = 0x00B4,
KEY_mu = 0x00B5,
KEY_paragraph = 0x00B6,
KEY_periodcentered = 0x00B7,
KEY_cedilla = 0x00B8,
KEY_onesuperior = 0x00B9,
KEY_masculine = 0x00BA,
KEY_guillemotright = 0x00BB,
KEY_onequarter = 0x00BC,
KEY_onehalf = 0x00BD,
KEY_threequarters = 0x00BE,
KEY_questiondown = 0x00BF,
KEY_Agrave = 0x00C0,
KEY_Aacute = 0x00C1,
KEY_Acircumflex = 0x00C2,
KEY_Atilde = 0x00C3,
KEY_Adiaeresis = 0x00C4,
KEY_Aring = 0x00C5,
KEY_AE = 0x00C6,
KEY_Ccedilla = 0x00C7,
KEY_Egrave = 0x00C8,
KEY_Eacute = 0x00C9,
KEY_Ecircumflex = 0x00CA,
KEY_Ediaeresis = 0x00CB,
KEY_Igrave = 0x00CC,
KEY_Iacute = 0x00CD,
KEY_Icircumflex = 0x00CE,
KEY_Idiaeresis = 0x00CF,
KEY_ETH = 0x00D0,
KEY_Eth = 0x00D0,
KEY_Ntilde = 0x00D1,
KEY_Ograve = 0x00D2,
KEY_Oacute = 0x00D3,
KEY_Ocircumflex = 0x00D4,
KEY_Otilde = 0x00D5,
KEY_Odiaeresis = 0x00D6,
KEY_multiply = 0x00D7,
KEY_Ooblique = 0x00D8,
KEY_Ugrave = 0x00D9,
KEY_Uacute = 0x00DA,
KEY_Ucircumflex = 0x00DB,
KEY_Udiaeresis = 0x00DC,
KEY_Yacute = 0x00DD,
KEY_THORN = 0x00DE,
KEY_Thorn = 0x00DE,
KEY_ssharp = 0x00DF,
KEY_agrave = 0x00E0,
KEY_aacute = 0x00E1,
KEY_acircumflex = 0x00E2,
KEY_atilde = 0x00E3,
KEY_adiaeresis = 0x00E4,
KEY_aring = 0x00E5,
KEY_ae = 0x00E6,
KEY_ccedilla = 0x00E7,
KEY_egrave = 0x00E8,
KEY_eacute = 0x00E9,
KEY_ecircumflex = 0x00EA,
KEY_ediaeresis = 0x00EB,
KEY_igrave = 0x00EC,
KEY_iacute = 0x00ED,
KEY_icircumflex = 0x00EE,
KEY_idiaeresis = 0x00EF,
KEY_eth = 0x00F0,
KEY_ntilde = 0x00F1,
KEY_ograve = 0x00F2,
KEY_oacute = 0x00F3,
KEY_ocircumflex = 0x00F4,
KEY_otilde = 0x00F5,
KEY_odiaeresis = 0x00F6,
KEY_division = 0x00F7,
KEY_oslash = 0x00F8,
KEY_ugrave = 0x00F9,
KEY_uacute = 0x00FA,
KEY_ucircumflex = 0x00FB,
KEY_udiaeresis = 0x00FC,
KEY_yacute = 0x00FD,
KEY_thorn = 0x00FE,
KEY_ydiaeresis = 0x00FF,
KEY_Aogonek = 0x01A1,
KEY_breve = 0x01A2,
KEY_Lstroke = 0x01A3,
KEY_Lcaron = 0x01A5,
KEY_Sacute = 0x01A6,
KEY_Scaron = 0x01A9,
KEY_Scedilla = 0x01AA,
KEY_Tcaron = 0x01AB,
KEY_Zacute = 0x01AC,
KEY_Zcaron = 0x01AE,
KEY_Zabovedot = 0x01AF,
KEY_aogonek = 0x01B1,
KEY_ogonek = 0x01B2,
KEY_lstroke = 0x01B3,
KEY_lcaron = 0x01B5,
KEY_sacute = 0x01B6,
KEY_caron = 0x01B7,
KEY_scaron = 0x01B9,
KEY_scedilla = 0x01BA,
KEY_tcaron = 0x01BB,
KEY_zacute = 0x01BC,
KEY_doubleacute = 0x01BD,
KEY_zcaron = 0x01BE,
KEY_zabovedot = 0x01BF,
KEY_Racute = 0x01C0,
KEY_Abreve = 0x01C3,
KEY_Lacute = 0x01C5,
KEY_Cacute = 0x01C6,
KEY_Ccaron = 0x01C8,
KEY_Eogonek = 0x01CA,
KEY_Ecaron = 0x01CC,
KEY_Dcaron = 0x01CF,
KEY_Dstroke = 0x01D0,
KEY_Nacute = 0x01D1,
KEY_Ncaron = 0x01D2,
KEY_Odoubleacute = 0x01D5,
KEY_Rcaron = 0x01D8,
KEY_Uring = 0x01D9,
KEY_Udoubleacute = 0x01DB,
KEY_Tcedilla = 0x01DE,
KEY_racute = 0x01E0,
KEY_abreve = 0x01E3,
KEY_lacute = 0x01E5,
KEY_cacute = 0x01E6,
KEY_ccaron = 0x01E8,
KEY_eogonek = 0x01EA,
KEY_ecaron = 0x01EC,
KEY_dcaron = 0x01EF,
KEY_dstroke = 0x01F0,
KEY_nacute = 0x01F1,
KEY_ncaron = 0x01F2,
KEY_odoubleacute = 0x01F5,
KEY_udoubleacute = 0x01FB,
KEY_rcaron = 0x01F8,
KEY_uring = 0x01F9,
KEY_tcedilla = 0x01FE,
KEY_abovedot = 0x01FF,
KEY_Hstroke = 0x02A1,
KEY_Hcircumflex = 0x02A6,
KEY_Iabovedot = 0x02A9,
KEY_Gbreve = 0x02AB,
KEY_Jcircumflex = 0x02AC,
KEY_hstroke = 0x02B1,
KEY_hcircumflex = 0x02B6,
KEY_idotless = 0x02B9,
KEY_gbreve = 0x02BB,
KEY_jcircumflex = 0x02BC,
KEY_Cabovedot = 0x02C5,
KEY_Ccircumflex = 0x02C6,
KEY_Gabovedot = 0x02D5,
KEY_Gcircumflex = 0x02D8,
KEY_Ubreve = 0x02DD,
KEY_Scircumflex = 0x02DE,
KEY_cabovedot = 0x02E5,
KEY_ccircumflex = 0x02E6,
KEY_gabovedot = 0x02F5,
KEY_gcircumflex = 0x02F8,
KEY_ubreve = 0x02FD,
KEY_scircumflex = 0x02FE,
KEY_kra = 0x03A2,
KEY_kappa = 0x03A2,
KEY_Rcedilla = 0x03A3,
KEY_Itilde = 0x03A5,
KEY_Lcedilla = 0x03A6,
KEY_Emacron = 0x03AA,
KEY_Gcedilla = 0x03AB,
KEY_Tslash = 0x03AC,
KEY_rcedilla = 0x03B3,
KEY_itilde = 0x03B5,
KEY_lcedilla = 0x03B6,
KEY_emacron = 0x03BA,
KEY_gcedilla = 0x03BB,
KEY_tslash = 0x03BC,
KEY_ENG = 0x03BD,
KEY_eng = 0x03BF,
KEY_Amacron = 0x03C0,
KEY_Iogonek = 0x03C7,
KEY_Eabovedot = 0x03CC,
KEY_Imacron = 0x03CF,
KEY_Ncedilla = 0x03D1,
KEY_Omacron = 0x03D2,
KEY_Kcedilla = 0x03D3,
KEY_Uogonek = 0x03D9,
KEY_Utilde = 0x03DD,
KEY_Umacron = 0x03DE,
KEY_amacron = 0x03E0,
KEY_iogonek = 0x03E7,
KEY_eabovedot = 0x03EC,
KEY_imacron = 0x03EF,
KEY_ncedilla = 0x03F1,
KEY_omacron = 0x03F2,
KEY_kcedilla = 0x03F3,
KEY_uogonek = 0x03F9,
KEY_utilde = 0x03FD,
KEY_umacron = 0x03FE,
KEY_overline = 0x047E,
KEY_kana_fullstop = 0x04A1,
KEY_kana_openingbracket = 0x04A2,
KEY_kana_closingbracket = 0x04A3,
KEY_kana_comma = 0x04A4,
KEY_kana_conjunctive = 0x04A5,
KEY_kana_middledot = 0x04A5,
KEY_kana_WO = 0x04A6,
KEY_kana_a = 0x04A7,
KEY_kana_i = 0x04A8,
KEY_kana_u = 0x04A9,
KEY_kana_e = 0x04AA,
KEY_kana_o = 0x04AB,
KEY_kana_ya = 0x04AC,
KEY_kana_yu = 0x04AD,
KEY_kana_yo = 0x04AE,
KEY_kana_tsu = 0x04AF,
KEY_kana_tu = 0x04AF,
KEY_prolongedsound = 0x04B0,
KEY_kana_A = 0x04B1,
KEY_kana_I = 0x04B2,
KEY_kana_U = 0x04B3,
KEY_kana_E = 0x04B4,
KEY_kana_O = 0x04B5,
KEY_kana_KA = 0x04B6,
KEY_kana_KI = 0x04B7,
KEY_kana_KU = 0x04B8,
KEY_kana_KE = 0x04B9,
KEY_kana_KO = 0x04BA,
KEY_kana_SA = 0x04BB,
KEY_kana_SHI = 0x04BC,
KEY_kana_SU = 0x04BD,
KEY_kana_SE = 0x04BE,
KEY_kana_SO = 0x04BF,
KEY_kana_TA = 0x04C0,
KEY_kana_CHI = 0x04C1,
KEY_kana_TI = 0x04C1,
KEY_kana_TSU = 0x04C2,
KEY_kana_TU = 0x04C2,
KEY_kana_TE = 0x04C3,
KEY_kana_TO = 0x04C4,
KEY_kana_NA = 0x04C5,
KEY_kana_NI = 0x04C6,
KEY_kana_NU = 0x04C7,
KEY_kana_NE = 0x04C8,
KEY_kana_NO = 0x04C9,
KEY_kana_HA = 0x04CA,
KEY_kana_HI = 0x04CB,
KEY_kana_FU = 0x04CC,
KEY_kana_HU = 0x04CC,
KEY_kana_HE = 0x04CD,
KEY_kana_HO = 0x04CE,
KEY_kana_MA = 0x04CF,
KEY_kana_MI = 0x04D0,
KEY_kana_MU = 0x04D1,
KEY_kana_ME = 0x04D2,
KEY_kana_MO = 0x04D3,
KEY_kana_YA = 0x04D4,
KEY_kana_YU = 0x04D5,
KEY_kana_YO = 0x04D6,
KEY_kana_RA = 0x04D7,
KEY_kana_RI = 0x04D8,
KEY_kana_RU = 0x04D9,
KEY_kana_RE = 0x04DA,
KEY_kana_RO = 0x04DB,
KEY_kana_WA = 0x04DC,
KEY_kana_N = 0x04DD,
KEY_voicedsound = 0x04DE,
KEY_semivoicedsound = 0x04DF,
KEY_kana_switch = 0x0FF7,
KEY_Arabic_comma = 0x05AC,
KEY_Arabic_semicolon = 0x05BB,
KEY_Arabic_question_mark = 0x05BF,
KEY_Arabic_hamza = 0x05C1,
KEY_Arabic_maddaonalef = 0x05C2,
KEY_Arabic_hamzaonalef = 0x05C3,
KEY_Arabic_hamzaonwaw = 0x05C4,
KEY_Arabic_hamzaunderalef = 0x05C5,
KEY_Arabic_hamzaonyeh = 0x05C6,
KEY_Arabic_alef = 0x05C7,
KEY_Arabic_beh = 0x05C8,
KEY_Arabic_tehmarbuta = 0x05C9,
KEY_Arabic_teh = 0x05CA,
KEY_Arabic_theh = 0x05CB,
KEY_Arabic_jeem = 0x05CC,
KEY_Arabic_hah = 0x05CD,
KEY_Arabic_khah = 0x05CE,
KEY_Arabic_dal = 0x05CF,
KEY_Arabic_thal = 0x05D0,
KEY_Arabic_ra = 0x05D1,
KEY_Arabic_zain = 0x05D2,
KEY_Arabic_seen = 0x05D3,
KEY_Arabic_sheen = 0x05D4,
KEY_Arabic_sad = 0x05D5,
KEY_Arabic_dad = 0x05D6,
KEY_Arabic_tah = 0x05D7,
KEY_Arabic_zah = 0x05D8,
KEY_Arabic_ain = 0x05D9,
KEY_Arabic_ghain = 0x05DA,
KEY_Arabic_tatweel = 0x05E0,
KEY_Arabic_feh = 0x05E1,
KEY_Arabic_qaf = 0x05E2,
KEY_Arabic_kaf = 0x05E3,
KEY_Arabic_lam = 0x05E4,
KEY_Arabic_meem = 0x05E5,
KEY_Arabic_noon = 0x05E6,
KEY_Arabic_ha = 0x05E7,
KEY_Arabic_heh = 0x05E7,
KEY_Arabic_waw = 0x05E8,
KEY_Arabic_alefmaksura = 0x05E9,
KEY_Arabic_yeh = 0x05EA,
KEY_Arabic_fathatan = 0x05EB,
KEY_Arabic_dammatan = 0x05EC,
KEY_Arabic_kasratan = 0x05ED,
KEY_Arabic_fatha = 0x05EE,
KEY_Arabic_damma = 0x05EF,
KEY_Arabic_kasra = 0x05F0,
KEY_Arabic_shadda = 0x05F1,
KEY_Arabic_sukun = 0x05F2,
KEY_Arabic_switch = 0xFF7E,
KEY_Serbian_dje = 0x06A1,
KEY_Macedonia_gje = 0x06A2,
KEY_Cyrillic_io = 0x06A3,
KEY_Ukrainian_ie = 0x06A4,
KEY_Ukranian_je = 0x06A4,
KEY_Macedonia_dse = 0x06A5,
KEY_Ukrainian_i = 0x06A6,
KEY_Ukranian_i = 0x06A6,
KEY_Ukrainian_yi = 0x06A7,
KEY_Ukranian_yi = 0x06A7,
KEY_Cyrillic_je = 0x06A8,
KEY_Serbian_je = 0x06A8,
KEY_Cyrillic_lje = 0x06A9,
KEY_Serbian_lje = 0x06A9,
KEY_Cyrillic_nje = 0x06AA,
KEY_Serbian_nje = 0x06AA,
KEY_Serbian_tshe = 0x06AB,
KEY_Macedonia_kje = 0x06AC,
KEY_Byelorussian_shortu = 0x06AE,
KEY_Cyrillic_dzhe = 0x06AF,
KEY_Serbian_dze = 0x06AF,
KEY_numerosign = 0x06B0,
KEY_Serbian_DJE = 0x06B1,
KEY_Macedonia_GJE = 0x06B2,
KEY_Cyrillic_IO = 0x06B3,
KEY_Ukrainian_IE = 0x06B4,
KEY_Ukranian_JE = 0x06B4,
KEY_Macedonia_DSE = 0x06B5,
KEY_Ukrainian_I = 0x06B6,
KEY_Ukranian_I = 0x06B6,
KEY_Ukrainian_YI = 0x06B7,
KEY_Ukranian_YI = 0x06B7,
KEY_Cyrillic_JE = 0x06B8,
KEY_Serbian_JE = 0x06B8,
KEY_Cyrillic_LJE = 0x06B9,
KEY_Serbian_LJE = 0x06B9,
KEY_Cyrillic_NJE = 0x06BA,
KEY_Serbian_NJE = 0x06BA,
KEY_Serbian_TSHE = 0x06BB,
KEY_Macedonia_KJE = 0x06BC,
KEY_Byelorussian_SHORTU = 0x06BE,
KEY_Cyrillic_DZHE = 0x06BF,
KEY_Serbian_DZE = 0x06BF,
KEY_Cyrillic_yu = 0x06C0,
KEY_Cyrillic_a = 0x06C1,
KEY_Cyrillic_be = 0x06C2,
KEY_Cyrillic_tse = 0x06C3,
KEY_Cyrillic_de = 0x06C4,
KEY_Cyrillic_ie = 0x06C5,
KEY_Cyrillic_ef = 0x06C6,
KEY_Cyrillic_ghe = 0x06C7,
KEY_Cyrillic_ha = 0x06C8,
KEY_Cyrillic_i = 0x06C9,
KEY_Cyrillic_shorti = 0x06CA,
KEY_Cyrillic_ka = 0x06CB,
KEY_Cyrillic_el = 0x06CC,
KEY_Cyrillic_em = 0x06CD,
KEY_Cyrillic_en = 0x06CE,
KEY_Cyrillic_o = 0x06CF,
KEY_Cyrillic_pe = 0x06D0,
KEY_Cyrillic_ya = 0x06D1,
KEY_Cyrillic_er = 0x06D2,
KEY_Cyrillic_es = 0x06D3,
KEY_Cyrillic_te = 0x06D4,
KEY_Cyrillic_u = 0x06D5,
KEY_Cyrillic_zhe = 0x06D6,
KEY_Cyrillic_ve = 0x06D7,
KEY_Cyrillic_softsign = 0x06D8,
KEY_Cyrillic_yeru = 0x06D9,
KEY_Cyrillic_ze = 0x06DA,
KEY_Cyrillic_sha = 0x06DB,
KEY_Cyrillic_e = 0x06DC,
KEY_Cyrillic_shcha = 0x06DD,
KEY_Cyrillic_che = 0x06DE,
KEY_Cyrillic_hardsign = 0x06DF,
KEY_Cyrillic_YU = 0x06E0,
KEY_Cyrillic_A = 0x06E1,
KEY_Cyrillic_BE = 0x06E2,
KEY_Cyrillic_TSE = 0x06E3,
KEY_Cyrillic_DE = 0x06E4,
KEY_Cyrillic_IE = 0x06E5,
KEY_Cyrillic_EF = 0x06E6,
KEY_Cyrillic_GHE = 0x06E7,
KEY_Cyrillic_HA = 0x06E8,
KEY_Cyrillic_I = 0x06E9,
KEY_Cyrillic_SHORTI = 0x06EA,
KEY_Cyrillic_KA = 0x06EB,
KEY_Cyrillic_EL = 0x06EC,
KEY_Cyrillic_EM = 0x06ED,
KEY_Cyrillic_EN = 0x06EE,
KEY_Cyrillic_O = 0x06EF,
KEY_Cyrillic_PE = 0x06F0,
KEY_Cyrillic_YA = 0x06F1,
KEY_Cyrillic_ER = 0x06F2,
KEY_Cyrillic_ES = 0x06F3,
KEY_Cyrillic_TE = 0x06F4,
KEY_Cyrillic_U = 0x06F5,
KEY_Cyrillic_ZHE = 0x06F6,
KEY_Cyrillic_VE = 0x06F7,
KEY_Cyrillic_SOFTSIGN = 0x06F8,
KEY_Cyrillic_YERU = 0x06F9,
KEY_Cyrillic_ZE = 0x06FA,
KEY_Cyrillic_SHA = 0x06FB,
KEY_Cyrillic_E = 0x06FC,
KEY_Cyrillic_SHCHA = 0x06FD,
KEY_Cyrillic_CHE = 0x06FE,
KEY_Cyrillic_HARDSIGN = 0x06FF,
KEY_Greek_ALPHAaccent = 0x07A1,
KEY_Greek_EPSILONaccent = 0x07A2,
KEY_Greek_ETAaccent = 0x07A3,
KEY_Greek_IOTAaccent = 0x07A4,
KEY_Greek_IOTAdiaeresis = 0x07A5,
KEY_Greek_OMICRONaccent = 0x07A7,
KEY_Greek_UPSILONaccent = 0x07A8,
KEY_Greek_UPSILONdieresis = 0x07A9,
KEY_Greek_OMEGAaccent = 0x07AB,
KEY_Greek_accentdieresis = 0x07AE,
KEY_Greek_horizbar = 0x07AF,
KEY_Greek_alphaaccent = 0x07B1,
KEY_Greek_epsilonaccent = 0x07B2,
KEY_Greek_etaaccent = 0x07B3,
KEY_Greek_iotaaccent = 0x07B4,
KEY_Greek_iotadieresis = 0x07B5,
KEY_Greek_iotaaccentdieresis = 0x07B6,
KEY_Greek_omicronaccent = 0x07B7,
KEY_Greek_upsilonaccent = 0x07B8,
KEY_Greek_upsilondieresis = 0x07B9,
KEY_Greek_upsilonaccentdieresis = 0x07BA,
KEY_Greek_omegaaccent = 0x07BB,
KEY_Greek_ALPHA = 0x07C1,
KEY_Greek_BETA = 0x07C2,
KEY_Greek_GAMMA = 0x07C3,
KEY_Greek_DELTA = 0x07C4,
KEY_Greek_EPSILON = 0x07C5,
KEY_Greek_ZETA = 0x07C6,
KEY_Greek_ETA = 0x07C7,
KEY_Greek_THETA = 0x07C8,
KEY_Greek_IOTA = 0x07C9,
KEY_Greek_KAPPA = 0x07CA,
KEY_Greek_LAMDA = 0x07CB,
KEY_Greek_LAMBDA = 0x07CB,
KEY_Greek_MU = 0x07CC,
KEY_Greek_NU = 0x07CD,
KEY_Greek_XI = 0x07CE,
KEY_Greek_OMICRON = 0x07CF,
KEY_Greek_PI = 0x07D0,
KEY_Greek_RHO = 0x07D1,
KEY_Greek_SIGMA = 0x07D2,
KEY_Greek_TAU = 0x07D4,
KEY_Greek_UPSILON = 0x07D5,
KEY_Greek_PHI = 0x07D6,
KEY_Greek_CHI = 0x07D7,
KEY_Greek_PSI = 0x07D8,
KEY_Greek_OMEGA = 0x07D9,
KEY_Greek_alpha = 0x07E1,
KEY_Greek_beta = 0x07E2,
KEY_Greek_gamma = 0x07E3,
KEY_Greek_delta = 0x07E4,
KEY_Greek_epsilon = 0x07E5,
KEY_Greek_zeta = 0x07E6,
KEY_Greek_eta = 0x07E7,
KEY_Greek_theta = 0x07E8,
KEY_Greek_iota = 0x07E9,
KEY_Greek_kappa = 0x07EA,
KEY_Greek_lamda = 0x07EB,
KEY_Greek_lambda = 0x07EB,
KEY_Greek_mu = 0x07EC,
KEY_Greek_nu = 0x07ED,
KEY_Greek_xi = 0x07EE,
KEY_Greek_omicron = 0x07EF,
KEY_Greek_pi = 0x07F0,
KEY_Greek_rho = 0x07F1,
KEY_Greek_sigma = 0x07F2,
KEY_Greek_finalsmallsigma = 0x07F3,
KEY_Greek_tau = 0x07F4,
KEY_Greek_upsilon = 0x07F5,
KEY_Greek_phi = 0x07F6,
KEY_Greek_chi = 0x07F7,
KEY_Greek_psi = 0x07F8,
KEY_Greek_omega = 0x07F9,
KEY_Greek_switch = 0xFF7E,
KEY_leftradical = 0x08A1,
KEY_topleftradical = 0x08A2,
KEY_horizconnector = 0x08A3,
KEY_topintegral = 0x08A4,
KEY_botintegral = 0x08A5,
KEY_vertconnector = 0x08A6,
KEY_topleftsqbracket = 0x08A7,
KEY_botleftsqbracket = 0x08A8,
KEY_toprightsqbracket = 0x08A9,
KEY_botrightsqbracket = 0x08AA,
KEY_topleftparens = 0x08AB,
KEY_botleftparens = 0x08AC,
KEY_toprightparens = 0x08AD,
KEY_botrightparens = 0x08AE,
KEY_leftmiddlecurlybrace = 0x08AF,
KEY_rightmiddlecurlybrace = 0x08B0,
KEY_topleftsummation = 0x08B1,
KEY_botleftsummation = 0x08B2,
KEY_topvertsummationconnector = 0x08B3,
KEY_botvertsummationconnector = 0x08B4,
KEY_toprightsummation = 0x08B5,
KEY_botrightsummation = 0x08B6,
KEY_rightmiddlesummation = 0x08B7,
KEY_lessthanequal = 0x08BC,
KEY_notequal = 0x08BD,
KEY_greaterthanequal = 0x08BE,
KEY_integral = 0x08BF,
KEY_therefore = 0x08C0,
KEY_variation = 0x08C1,
KEY_infinity = 0x08C2,
KEY_nabla = 0x08C5,
KEY_approximate = 0x08C8,
KEY_similarequal = 0x08C9,
KEY_ifonlyif = 0x08CD,
KEY_implies = 0x08CE,
KEY_identical = 0x08CF,
KEY_radical = 0x08D6,
KEY_includedin = 0x08DA,
KEY_includes = 0x08DB,
KEY_intersection = 0x08DC,
KEY_union = 0x08DD,
KEY_logicaland = 0x08DE,
KEY_logicalor = 0x08DF,
KEY_partialderivative = 0x08EF,
KEY_function = 0x08F6,
KEY_leftarrow = 0x08FB,
KEY_uparrow = 0x08FC,
KEY_rightarrow = 0x08FD,
KEY_downarrow = 0x08FE,
KEY_blank = 0x09DF,
KEY_soliddiamond = 0x09E0,
KEY_checkerboard = 0x09E1,
KEY_ht = 0x09E2,
KEY_ff = 0x09E3,
KEY_cr = 0x09E4,
KEY_lf = 0x09E5,
KEY_nl = 0x09E8,
KEY_vt = 0x09E9,
KEY_lowrightcorner = 0x09EA,
KEY_uprightcorner = 0x09EB,
KEY_upleftcorner = 0x09EC,
KEY_lowleftcorner = 0x09ED,
KEY_crossinglines = 0x09EE,
KEY_horizlinescan1 = 0x09EF,
KEY_horizlinescan3 = 0x09F0,
KEY_horizlinescan5 = 0x09F1,
KEY_horizlinescan7 = 0x09F2,
KEY_horizlinescan9 = 0x09F3,
KEY_leftt = 0x09F4,
KEY_rightt = 0x09F5,
KEY_bott = 0x09F6,
KEY_topt = 0x09F7,
KEY_vertbar = 0x09F8,
KEY_emspace = 0x0AA1,
KEY_enspace = 0x0AA2,
KEY_em3space = 0x0AA3,
KEY_em4space = 0x0AA4,
KEY_digitspace = 0x0AA5,
KEY_punctspace = 0x0AA6,
KEY_thinspace = 0x0AA7,
KEY_hairspace = 0x0AA8,
KEY_emdash = 0x0AA9,
KEY_endash = 0x0AAA,
KEY_signifblank = 0x0AAC,
KEY_ellipsis = 0x0AAE,
KEY_doubbaselinedot = 0x0AAF,
KEY_onethird = 0x0AB0,
KEY_twothirds = 0x0AB1,
KEY_onefifth = 0x0AB2,
KEY_twofifths = 0x0AB3,
KEY_threefifths = 0x0AB4,
KEY_fourfifths = 0x0AB5,
KEY_onesixth = 0x0AB6,
KEY_fivesixths = 0x0AB7,
KEY_careof = 0x0AB8,
KEY_figdash = 0x0ABB,
KEY_leftanglebracket = 0x0ABC,
KEY_decimalpoint = 0x0ABD,
KEY_rightanglebracket = 0x0ABE,
KEY_marker = 0x0ABF,
KEY_oneeighth = 0x0AC3,
KEY_threeeighths = 0x0AC4,
KEY_fiveeighths = 0x0AC5,
KEY_seveneighths = 0x0AC6,
KEY_trademark = 0x0AC9,
KEY_signaturemark = 0x0ACA,
KEY_trademarkincircle = 0x0ACB,
KEY_leftopentriangle = 0x0ACC,
KEY_rightopentriangle = 0x0ACD,
KEY_emopencircle = 0x0ACE,
KEY_emopenrectangle = 0x0ACF,
KEY_leftsinglequotemark = 0x0AD0,
KEY_rightsinglequotemark = 0x0AD1,
KEY_leftdoublequotemark = 0x0AD2,
KEY_rightdoublequotemark = 0x0AD3,
KEY_prescription = 0x0AD4,
KEY_minutes = 0x0AD6,
KEY_seconds = 0x0AD7,
KEY_latincross = 0x0AD9,
KEY_hexagram = 0x0ADA,
KEY_filledrectbullet = 0x0ADB,
KEY_filledlefttribullet = 0x0ADC,
KEY_filledrighttribullet = 0x0ADD,
KEY_emfilledcircle = 0x0ADE,
KEY_emfilledrect = 0x0ADF,
KEY_enopencircbullet = 0x0AE0,
KEY_enopensquarebullet = 0x0AE1,
KEY_openrectbullet = 0x0AE2,
KEY_opentribulletup = 0x0AE3,
KEY_opentribulletdown = 0x0AE4,
KEY_openstar = 0x0AE5,
KEY_enfilledcircbullet = 0x0AE6,
KEY_enfilledsqbullet = 0x0AE7,
KEY_filledtribulletup = 0x0AE8,
KEY_filledtribulletdown = 0x0AE9,
KEY_leftpointer = 0x0AEA,
KEY_rightpointer = 0x0AEB,
KEY_club = 0x0AEC,
KEY_diamond = 0x0AED,
KEY_heart = 0x0AEE,
KEY_maltesecross = 0x0AF0,
KEY_dagger = 0x0AF1,
KEY_doubledagger = 0x0AF2,
KEY_checkmark = 0x0AF3,
KEY_ballotcross = 0x0AF4,
KEY_musicalsharp = 0x0AF5,
KEY_musicalflat = 0x0AF6,
KEY_malesymbol = 0x0AF7,
KEY_femalesymbol = 0x0AF8,
KEY_telephone = 0x0AF9,
KEY_telephonerecorder = 0x0AFA,
KEY_phonographcopyright = 0x0AFB,
KEY_caret = 0x0AFC,
KEY_singlelowquotemark = 0x0AFD,
KEY_doublelowquotemark = 0x0AFE,
KEY_cursor = 0x0AFF,
KEY_leftcaret = 0x0BA3,
KEY_rightcaret = 0x0BA6,
KEY_downcaret = 0x0BA8,
KEY_upcaret = 0x0BA9,
KEY_overbar = 0x0BC0,
KEY_downtack = 0x0BC2,
KEY_upshoe = 0x0BC3,
KEY_downstile = 0x0BC4,
KEY_underbar = 0x0BC6,
KEY_jot = 0x0BCA,
KEY_quad = 0x0BCC,
KEY_uptack = 0x0BCE,
KEY_circle = 0x0BCF,
KEY_upstile = 0x0BD3,
KEY_downshoe = 0x0BD6,
KEY_rightshoe = 0x0BD8,
KEY_leftshoe = 0x0BDA,
KEY_lefttack = 0x0BDC,
KEY_righttack = 0x0BFC,
KEY_hebrew_doublelowline = 0x0CDF,
KEY_hebrew_aleph = 0x0CE0,
KEY_hebrew_bet = 0x0CE1,
KEY_hebrew_beth = 0x0CE1,
KEY_hebrew_gimel = 0x0CE2,
KEY_hebrew_gimmel = 0x0CE2,
KEY_hebrew_dalet = 0x0CE3,
KEY_hebrew_daleth = 0x0CE3,
KEY_hebrew_he = 0x0CE4,
KEY_hebrew_waw = 0x0CE5,
KEY_hebrew_zain = 0x0CE6,
KEY_hebrew_zayin = 0x0CE6,
KEY_hebrew_chet = 0x0CE7,
KEY_hebrew_het = 0x0CE7,
KEY_hebrew_tet = 0x0CE8,
KEY_hebrew_teth = 0x0CE8,
KEY_hebrew_yod = 0x0CE9,
KEY_hebrew_finalkaph = 0x0CEA,
KEY_hebrew_kaph = 0x0CEB,
KEY_hebrew_lamed = 0x0CEC,
KEY_hebrew_finalmem = 0x0CED,
KEY_hebrew_mem = 0x0CEE,
KEY_hebrew_finalnun = 0x0CEF,
KEY_hebrew_nun = 0x0CF0,
KEY_hebrew_samech = 0x0CF1,
KEY_hebrew_samekh = 0x0CF1,
KEY_hebrew_ayin = 0x0CF2,
KEY_hebrew_finalpe = 0x0CF3,
KEY_hebrew_pe = 0x0CF4,
KEY_hebrew_finalzade = 0x0CF5,
KEY_hebrew_finalzadi = 0x0CF5,
KEY_hebrew_zade = 0x0CF6,
KEY_hebrew_zadi = 0x0CF6,
KEY_hebrew_qoph = 0x0CF7,
KEY_hebrew_kuf = 0x0CF7,
KEY_hebrew_resh = 0x0CF8,
KEY_hebrew_shin = 0x0CF9,
KEY_hebrew_taw = 0x0CFA,
KEY_hebrew_taf = 0x0CFA,
KEY_Hebrew_switch = 0xFF7E,
KEY_Thai_kokai = 0x0DA1,
KEY_Thai_khokhai = 0x0DA2,
KEY_Thai_khokhuat = 0x0DA3,
KEY_Thai_khokhwai = 0x0DA4,
KEY_Thai_khokhon = 0x0DA5,
KEY_Thai_khorakhang = 0x0DA6,
KEY_Thai_ngongu = 0x0DA7,
KEY_Thai_chochan = 0x0DA8,
KEY_Thai_choching = 0x0DA9,
KEY_Thai_chochang = 0x0DAA,
KEY_Thai_soso = 0x0DAB,
KEY_Thai_chochoe = 0x0DAC,
KEY_Thai_yoying = 0x0DAD,
KEY_Thai_dochada = 0x0DAE,
KEY_Thai_topatak = 0x0DAF,
KEY_Thai_thothan = 0x0DB0,
KEY_Thai_thonangmontho = 0x0DB1,
KEY_Thai_thophuthao = 0x0DB2,
KEY_Thai_nonen = 0x0DB3,
KEY_Thai_dodek = 0x0DB4,
KEY_Thai_totao = 0x0DB5,
KEY_Thai_thothung = 0x0DB6,
KEY_Thai_thothahan = 0x0DB7,
KEY_Thai_thothong = 0x0DB8,
KEY_Thai_nonu = 0x0DB9,
KEY_Thai_bobaimai = 0x0DBA,
KEY_Thai_popla = 0x0DBB,
KEY_Thai_phophung = 0x0DBC,
KEY_Thai_fofa = 0x0DBD,
KEY_Thai_phophan = 0x0DBE,
KEY_Thai_fofan = 0x0DBF,
KEY_Thai_phosamphao = 0x0DC0,
KEY_Thai_moma = 0x0DC1,
KEY_Thai_yoyak = 0x0DC2,
KEY_Thai_rorua = 0x0DC3,
KEY_Thai_ru = 0x0DC4,
KEY_Thai_loling = 0x0DC5,
KEY_Thai_lu = 0x0DC6,
KEY_Thai_wowaen = 0x0DC7,
KEY_Thai_sosala = 0x0DC8,
KEY_Thai_sorusi = 0x0DC9,
KEY_Thai_sosua = 0x0DCA,
KEY_Thai_hohip = 0x0DCB,
KEY_Thai_lochula = 0x0DCC,
KEY_Thai_oang = 0x0DCD,
KEY_Thai_honokhuk = 0x0DCE,
KEY_Thai_paiyannoi = 0x0DCF,
KEY_Thai_saraa = 0x0DD0,
KEY_Thai_maihanakat = 0x0DD1,
KEY_Thai_saraaa = 0x0DD2,
KEY_Thai_saraam = 0x0DD3,
KEY_Thai_sarai = 0x0DD4,
KEY_Thai_saraii = 0x0DD5,
KEY_Thai_saraue = 0x0DD6,
KEY_Thai_sarauee = 0x0DD7,
KEY_Thai_sarau = 0x0DD8,
KEY_Thai_sarauu = 0x0DD9,
KEY_Thai_phinthu = 0x0DDA,
KEY_Thai_maihanakat_maitho = 0x0DDE,
KEY_Thai_baht = 0x0DDF,
KEY_Thai_sarae = 0x0DE0,
KEY_Thai_saraae = 0x0DE1,
KEY_Thai_sarao = 0x0DE2,
KEY_Thai_saraaimaimuan = 0x0DE3,
KEY_Thai_saraaimaimalai = 0x0DE4,
KEY_Thai_lakkhangyao = 0x0DE5,
KEY_Thai_maiyamok = 0x0DE6,
KEY_Thai_maitaikhu = 0x0DE7,
KEY_Thai_maiek = 0x0DE8,
KEY_Thai_maitho = 0x0DE9,
KEY_Thai_maitri = 0x0DEA,
KEY_Thai_maichattawa = 0x0DEB,
KEY_Thai_thanthakhat = 0x0DEC,
KEY_Thai_nikhahit = 0x0DED,
KEY_Thai_leksun = 0x0DF0,
KEY_Thai_leknung = 0x0DF1,
KEY_Thai_leksong = 0x0DF2,
KEY_Thai_leksam = 0x0DF3,
KEY_Thai_leksi = 0x0DF4,
KEY_Thai_lekha = 0x0DF5,
KEY_Thai_lekhok = 0x0DF6,
KEY_Thai_lekchet = 0x0DF7,
KEY_Thai_lekpaet = 0x0DF8,
KEY_Thai_lekkao = 0x0DF9,
KEY_Hangul = 0xFF31,
KEY_Hangul_Start = 0xFF32,
KEY_Hangul_End = 0xFF33,
KEY_Hangul_Hanja = 0xFF34,
KEY_Hangul_Jamo = 0xFF35,
KEY_Hangul_Romaja = 0xFF36,
KEY_Hangul_Codeinput = 0xFF37,
KEY_Hangul_Jeonja = 0xFF38,
KEY_Hangul_Banja = 0xFF39,
KEY_Hangul_PreHanja = 0xFF3A,
KEY_Hangul_PostHanja = 0xFF3B,
KEY_Hangul_SingleCandidate = 0xFF3C,
KEY_Hangul_MultipleCandidate = 0xFF3D,
KEY_Hangul_PreviousCandidate = 0xFF3E,
KEY_Hangul_Special = 0xFF3F,
KEY_Hangul_switch = 0xFF7E,
KEY_Hangul_Kiyeog = 0x0EA1,
KEY_Hangul_SsangKiyeog = 0x0EA2,
KEY_Hangul_KiyeogSios = 0x0EA3,
KEY_Hangul_Nieun = 0x0EA4,
KEY_Hangul_NieunJieuj = 0x0EA5,
KEY_Hangul_NieunHieuh = 0x0EA6,
KEY_Hangul_Dikeud = 0x0EA7,
KEY_Hangul_SsangDikeud = 0x0EA8,
KEY_Hangul_Rieul = 0x0EA9,
KEY_Hangul_RieulKiyeog = 0x0EAA,
KEY_Hangul_RieulMieum = 0x0EAB,
KEY_Hangul_RieulPieub = 0x0EAC,
KEY_Hangul_RieulSios = 0x0EAD,
KEY_Hangul_RieulTieut = 0x0EAE,
KEY_Hangul_RieulPhieuf = 0x0EAF,
KEY_Hangul_RieulHieuh = 0x0EB0,
KEY_Hangul_Mieum = 0x0EB1,
KEY_Hangul_Pieub = 0x0EB2,
KEY_Hangul_SsangPieub = 0x0EB3,
KEY_Hangul_PieubSios = 0x0EB4,
KEY_Hangul_Sios = 0x0EB5,
KEY_Hangul_SsangSios = 0x0EB6,
KEY_Hangul_Ieung = 0x0EB7,
KEY_Hangul_Jieuj = 0x0EB8,
KEY_Hangul_SsangJieuj = 0x0EB9,
KEY_Hangul_Cieuc = 0x0EBA,
KEY_Hangul_Khieuq = 0x0EBB,
KEY_Hangul_Tieut = 0x0EBC,
KEY_Hangul_Phieuf = 0x0EBD,
KEY_Hangul_Hieuh = 0x0EBE,
KEY_Hangul_A = 0x0EBF,
KEY_Hangul_AE = 0x0EC0,
KEY_Hangul_YA = 0x0EC1,
KEY_Hangul_YAE = 0x0EC2,
KEY_Hangul_EO = 0x0EC3,
KEY_Hangul_E = 0x0EC4,
KEY_Hangul_YEO = 0x0EC5,
KEY_Hangul_YE = 0x0EC6,
KEY_Hangul_O = 0x0EC7,
KEY_Hangul_WA = 0x0EC8,
KEY_Hangul_WAE = 0x0EC9,
KEY_Hangul_OE = 0x0ECA,
KEY_Hangul_YO = 0x0ECB,
KEY_Hangul_U = 0x0ECC,
KEY_Hangul_WEO = 0x0ECD,
KEY_Hangul_WE = 0x0ECE,
KEY_Hangul_WI = 0x0ECF,
KEY_Hangul_YU = 0x0ED0,
KEY_Hangul_EU = 0x0ED1,
KEY_Hangul_YI = 0x0ED2,
KEY_Hangul_I = 0x0ED3,
KEY_Hangul_J_Kiyeog = 0x0ED4,
KEY_Hangul_J_SsangKiyeog = 0x0ED5,
KEY_Hangul_J_KiyeogSios = 0x0ED6,
KEY_Hangul_J_Nieun = 0x0ED7,
KEY_Hangul_J_NieunJieuj = 0x0ED8,
KEY_Hangul_J_NieunHieuh = 0x0ED9,
KEY_Hangul_J_Dikeud = 0x0EDA,
KEY_Hangul_J_Rieul = 0x0EDB,
KEY_Hangul_J_RieulKiyeog = 0x0EDC,
KEY_Hangul_J_RieulMieum = 0x0EDD,
KEY_Hangul_J_RieulPieub = 0x0EDE,
KEY_Hangul_J_RieulSios = 0x0EDF,
KEY_Hangul_J_RieulTieut = 0x0EE0,
KEY_Hangul_J_RieulPhieuf = 0x0EE1,
KEY_Hangul_J_RieulHieuh = 0x0EE2,
KEY_Hangul_J_Mieum = 0x0EE3,
KEY_Hangul_J_Pieub = 0x0EE4,
KEY_Hangul_J_PieubSios = 0x0EE5,
KEY_Hangul_J_Sios = 0x0EE6,
KEY_Hangul_J_SsangSios = 0x0EE7,
KEY_Hangul_J_Ieung = 0x0EE8,
KEY_Hangul_J_Jieuj = 0x0EE9,
KEY_Hangul_J_Cieuc = 0x0EEA,
KEY_Hangul_J_Khieuq = 0x0EEB,
KEY_Hangul_J_Tieut = 0x0EEC,
KEY_Hangul_J_Phieuf = 0x0EED,
KEY_Hangul_J_Hieuh = 0x0EEE,
KEY_Hangul_RieulYeorinHieuh = 0x0EEF,
KEY_Hangul_SunkyeongeumMieum = 0x0EF0,
KEY_Hangul_SunkyeongeumPieub = 0x0EF1,
KEY_Hangul_PanSios = 0x0EF2,
KEY_Hangul_KkogjiDalrinIeung = 0x0EF3,
KEY_Hangul_SunkyeongeumPhieuf = 0x0EF4,
KEY_Hangul_YeorinHieuh = 0x0EF5,
KEY_Hangul_AraeA = 0x0EF6,
KEY_Hangul_AraeAE = 0x0EF7,
KEY_Hangul_J_PanSios = 0x0EF8,
KEY_Hangul_J_KkogjiDalrinIeung = 0x0EF9,
KEY_Hangul_J_YeorinHieuh = 0x0EFA,
KEY_Korean_Won = 0x0EFF
}
enum {
KNOB_NEEDLE = 0,
KNOB_DOT = 0x00008000,
KNOB_TICKS = 0x00010000,
KNOB_INDICATOR = 0x00020000,
KNOB_NORMAL = (KNOB_NEEDLE|KNOB_TICKS)
}
enum {
ICON_UNDER_TEXT = 0,
ICON_AFTER_TEXT = 0x00080000,
ICON_BEFORE_TEXT = 0x00100000,
ICON_ABOVE_TEXT = 0x00200000,
ICON_BELOW_TEXT = 0x00400000,
TEXT_OVER_ICON = ICON_UNDER_TEXT,
TEXT_AFTER_ICON = ICON_BEFORE_TEXT,
TEXT_BEFORE_ICON = ICON_AFTER_TEXT,
TEXT_ABOVE_ICON = ICON_BELOW_TEXT,
TEXT_BELOW_ICON = ICON_ABOVE_TEXT
}
enum { LABEL_NORMAL = JUSTIFY_NORMAL|ICON_BEFORE_TEXT }
enum {
LIST_EXTENDEDSELECT = 0,
LIST_SINGLESELECT = 0x00100000,
LIST_BROWSESELECT = 0x00200000,
LIST_MULTIPLESELECT = 0x00300000,
LIST_AUTOSELECT = 0x00400000,
LIST_NORMAL = LIST_EXTENDEDSELECT
}
enum { LISTBOX_NORMAL = 0 }
enum {
MATRIX_BY_ROWS = 0,
MATRIX_BY_COLUMNS = 0x00020000
}
enum {
MDI_NORMAL = 0,
MDI_MAXIMIZED = 0x00001000,
MDI_MINIMIZED = 0x00002000,
MDI_TRACKING = 0x00004000
}
enum {
MENUBUTTON_AUTOGRAY = 0x00800000,
MENUBUTTON_AUTOHIDE = 0x01000000,
MENUBUTTON_TOOLBAR = 0x02000000,
MENUBUTTON_DOWN = 0,
MENUBUTTON_UP = 0x04000000,
MENUBUTTON_LEFT = 0x08000000,
MENUBUTTON_RIGHT = MENUBUTTON_LEFT|MENUBUTTON_UP,
MENUBUTTON_NOARROWS = 0x10000000,
MENUBUTTON_ATTACH_LEFT = 0,
MENUBUTTON_ATTACH_TOP = MENUBUTTON_ATTACH_LEFT,
MENUBUTTON_ATTACH_RIGHT = 0x20000000,
MENUBUTTON_ATTACH_BOTTOM = MENUBUTTON_ATTACH_RIGHT,
MENUBUTTON_ATTACH_CENTER = 0x40000000,
MENUBUTTON_ATTACH_BOTH = MENUBUTTON_ATTACH_CENTER|MENUBUTTON_ATTACH_RIGHT
}
enum {
MENU_AUTOGRAY = 0x00008000,
MENU_AUTOHIDE = 0x00010000
}
enum {
MBOX_OK = 0x10000000,
MBOX_OK_CANCEL = 0x20000000,
MBOX_YES_NO = 0x30000000,
MBOX_YES_NO_CANCEL = 0x40000000,
MBOX_QUIT_CANCEL = 0x50000000,
MBOX_QUIT_SAVE_CANCEL = 0x60000000,
MBOX_SKIP_SKIPALL_CANCEL = 0x70000000,
MBOX_SAVE_CANCEL_DONTSAVE = 0x80000000
}
enum {
MBOX_CLICKED_YES = 1,
MBOX_CLICKED_NO = 2,
MBOX_CLICKED_OK = 3,
MBOX_CLICKED_CANCEL = 4,
MBOX_CLICKED_QUIT = 5,
MBOX_CLICKED_SAVE = 6,
MBOX_CLICKED_SKIP = 7,
MBOX_CLICKED_SKIPALL = 8
}
enum {
MINKEY = 0,
MAXKEY = 65535
}
enum {
MINTYPE = 0,
MAXTYPE = 65535
}
enum { DEFAULT_SPACING = 4 }
enum {
POPUP_VERTICAL = 0,
POPUP_HORIZONTAL = 0x00020000,
POPUP_SHRINKWRAP = 0x00040000
}
enum {
PROGRESSBAR_HORIZONTAL = 0,
PROGRESSBAR_VERTICAL = 0x00008000,
PROGRESSBAR_PERCENTAGE = 0x00010000,
PROGRESSBAR_DIAL = 0x00020000,
PROGRESSBAR_NORMAL = FRAME_SUNKEN|FRAME_THICK
}
enum {
PROGRESSDIALOG_NOCANCEL = 0,
PROGRESSDIALOG_CANCEL = 0x01000000,
PROGRESSDIALOG_NORMAL = (DECOR_TITLE|DECOR_BORDER)
}
enum {
RADIOBUTTON_AUTOGRAY = 0x00800000,
RADIOBUTTON_AUTOHIDE = 0x01000000,
RADIOBUTTON_NORMAL = JUSTIFY_NORMAL|ICON_BEFORE_TEXT
}
enum {
REALSLIDER_HORIZONTAL = 0,
REALSLIDER_VERTICAL = 0x00008000,
REALSLIDER_ARROW_UP = 0x00010000,
REALSLIDER_ARROW_DOWN = 0x00020000,
REALSLIDER_ARROW_LEFT = REALSLIDER_ARROW_UP,
REALSLIDER_ARROW_RIGHT = REALSLIDER_ARROW_DOWN,
REALSLIDER_INSIDE_BAR = 0x00040000,
REALSLIDER_TICKS_TOP = 0x00080000,
REALSLIDER_TICKS_BOTTOM = 0x00100000,
REALSLIDER_TICKS_LEFT = REALSLIDER_TICKS_TOP,
REALSLIDER_TICKS_RIGHT = REALSLIDER_TICKS_BOTTOM,
REALSLIDER_NORMAL = REALSLIDER_HORIZONTAL
}
enum {
REALSPIN_NORMAL = 0,
REALSPIN_CYCLIC = 0x00020000,
REALSPIN_NOTEXT = 0x00040000,
REALSPIN_NOMAX = 0x00080000,
REALSPIN_NOMIN = 0x00100000,
REALSPIN_LOG = 0x00200000
}
enum FXRexError {
REGERR_OK,
REGERR_EMPTY,
REGERR_PAREN,
REGERR_BRACK,
REGERR_BRACE,
REGERR_RANGE,
REGERR_ESC,
REGERR_COUNT,
REGERR_NOATOM,
REGERR_REPEAT,
REGERR_BACKREF,
REGERR_CLASS,
REGERR_COMPLEX,
REGERR_MEMORY,
REGERR_TOKEN
}
enum {
REX_NORMAL = 0,
REX_CAPTURE = 1,
REX_ICASE = 2,
REX_NEWLINE = 4,
REX_VERBATIM = 8,
REX_SYNTAX = 16
}
enum {
REX_FORWARD = 0,
REX_BACKWARD = 32,
REX_NOT_BOL = 64,
REX_NOT_EOL = 128,
REX_NOT_EMPTY = 256
}
enum {
RULER_NORMAL = 0,
RULER_HORIZONTAL = 0,
RULER_VERTICAL = 0x00008000,
RULER_TICKS_OFF = 0,
RULER_TICKS_TOP = 0x00010000,
RULER_TICKS_BOTTOM = 0x00020000,
RULER_TICKS_LEFT = RULER_TICKS_TOP,
RULER_TICKS_RIGHT = RULER_TICKS_BOTTOM,
RULER_TICKS_CENTER = RULER_TICKS_TOP|RULER_TICKS_BOTTOM,
RULER_NUMBERS = 0x00040000,
RULER_ARROW = 0x00080000,
RULER_MARKERS = 0x00100000,
RULER_METRIC = 0,
RULER_ENGLISH = 0x00200000,
RULER_MARGIN_ADJUST = 0x00400000,
RULER_ALIGN_CENTER = 0,
RULER_ALIGN_LEFT = 0x00800000,
RULER_ALIGN_RIGHT = 0x01000000,
RULER_ALIGN_TOP = RULER_ALIGN_LEFT,
RULER_ALIGN_BOTTOM = RULER_ALIGN_RIGHT,
RULER_ALIGN_STRETCH = RULER_ALIGN_LEFT|RULER_ALIGN_RIGHT,
RULER_ALIGN_NORMAL = RULER_ALIGN_CENTER
}
enum {
SCROLLERS_NORMAL = 0,
HSCROLLER_ALWAYS = 0x00008000,
HSCROLLER_NEVER = 0x00010000,
VSCROLLER_ALWAYS = 0x00020000,
VSCROLLER_NEVER = 0x00040000,
HSCROLLING_ON = 0,
HSCROLLING_OFF = HSCROLLER_NEVER|HSCROLLER_ALWAYS,
VSCROLLING_ON = 0,
VSCROLLING_OFF = VSCROLLER_NEVER|VSCROLLER_ALWAYS,
SCROLLERS_TRACK = 0,
SCROLLERS_DONT_TRACK = 0x00080000
}
enum {
SCROLLBAR_VERTICAL = 0,
SCROLLBAR_HORIZONTAL = 0x00020000,
SCROLLBAR_WHEELJUMP = 0x00040000
}
enum {
SEPARATOR_NONE = 0,
SEPARATOR_GROOVE = 0x00008000,
SEPARATOR_RIDGE = 0x00010000,
SEPARATOR_LINE = 0x00020000
}
enum {
SLIDER_HORIZONTAL = 0,
SLIDER_VERTICAL = 0x00008000,
SLIDER_ARROW_UP = 0x00010000,
SLIDER_ARROW_DOWN = 0x00020000,
SLIDER_ARROW_LEFT = SLIDER_ARROW_UP,
SLIDER_ARROW_RIGHT = SLIDER_ARROW_DOWN,
SLIDER_INSIDE_BAR = 0x00040000,
SLIDER_TICKS_TOP = 0x00080000,
SLIDER_TICKS_BOTTOM = 0x00100000,
SLIDER_TICKS_LEFT = SLIDER_TICKS_TOP,
SLIDER_TICKS_RIGHT = SLIDER_TICKS_BOTTOM,
SLIDER_NORMAL = SLIDER_HORIZONTAL
}
enum {
SPIN_NORMAL = 0,
SPIN_CYCLIC = 0x00020000,
SPIN_NOTEXT = 0x00040000,
SPIN_NOMAX = 0x00080000,
SPIN_NOMIN = 0x00100000
}
enum {
SPLASH_SIMPLE = 0,
SPLASH_SHAPED = 0x02000000,
SPLASH_OWNS_ICON = 0x04000000,
SPLASH_DESTROY = 0x08000000
}
enum {
SPLITTER_HORIZONTAL = 0,
SPLITTER_VERTICAL = 0x00008000,
SPLITTER_REVERSED = 0x00010000,
SPLITTER_TRACKING = 0x00020000,
SPLITTER_NORMAL = SPLITTER_HORIZONTAL
}
enum { STATUSBAR_WITH_DRAGCORNER = 0x00020000 }
enum FXStreamDirection {
FXStreamDead =0,
FXStreamSave =1,
FXStreamLoad =2
}
enum FXStreamStatus {
FXStreamOK =0,
FXStreamEnd =1,
FXStreamFull =2,
FXStreamNoWrite =3,
FXStreamNoRead =4,
FXStreamFormat =5,
FXStreamUnknown =6,
FXStreamAlloc =7,
FXStreamFailure =8
}
enum FXWhence {
FXFromStart =0,
FXFromCurrent =1,
FXFromEnd =2
}
enum {
SWITCHER_HCOLLAPSE = 0x00020000,
SWITCHER_VCOLLAPSE = 0x00040000
}
enum {
TABBOOK_TOPTABS = 0,
TABBOOK_BOTTOMTABS = 0x00020000,
TABBOOK_SIDEWAYS = 0x00040000,
TABBOOK_LEFTTABS = TABBOOK_SIDEWAYS|TABBOOK_TOPTABS,
TABBOOK_RIGHTTABS = TABBOOK_SIDEWAYS|TABBOOK_BOTTOMTABS,
TABBOOK_NORMAL = TABBOOK_TOPTABS
}
enum {
TAB_TOP = 0,
TAB_LEFT = 0x00800000,
TAB_RIGHT = 0x01000000,
TAB_BOTTOM = 0x01800000,
TAB_TOP_NORMAL = JUSTIFY_NORMAL|ICON_BEFORE_TEXT|TAB_TOP|FRAME_RAISED|FRAME_THICK,
TAB_BOTTOM_NORMAL = JUSTIFY_NORMAL|ICON_BEFORE_TEXT|TAB_BOTTOM|FRAME_RAISED|FRAME_THICK,
TAB_LEFT_NORMAL = JUSTIFY_LEFT|JUSTIFY_CENTER_Y|ICON_BEFORE_TEXT|TAB_LEFT|FRAME_RAISED|FRAME_THICK,
TAB_RIGHT_NORMAL = JUSTIFY_LEFT|JUSTIFY_CENTER_Y|ICON_BEFORE_TEXT|TAB_RIGHT|FRAME_RAISED|FRAME_THICK
}
enum { DEFAULT_MARGIN = 2 }
enum {
TABLE_COL_SIZABLE = 0x00100000,
TABLE_ROW_SIZABLE = 0x00200000,
TABLE_NO_COLSELECT = 0x00400000,
TABLE_NO_ROWSELECT = 0x00800000,
TABLE_READONLY = 0x01000000,
TABLE_COL_RENUMBER = 0x02000000,
TABLE_ROW_RENUMBER = 0x04000000
}
enum {
TEXT_READONLY = 0x00100000,
TEXT_WORDWRAP = 0x00200000,
TEXT_OVERSTRIKE = 0x00400000,
TEXT_FIXEDWRAP = 0x00800000,
TEXT_NO_TABS = 0x01000000,
TEXT_AUTOINDENT = 0x02000000,
TEXT_SHOWACTIVE = 0x04000000,
TEXT_AUTOSCROLL = 0x08000000
}
enum FXTextSelectionMode {
SELECT_CHARS,
SELECT_WORDS,
SELECT_LINES
}
enum {
TEXTFIELD_PASSWD = 0x00080000,
TEXTFIELD_INTEGER = 0x00100000,
TEXTFIELD_REAL = 0x00200000,
TEXTFIELD_READONLY = 0x00400000,
TEXTFIELD_ENTER_ONLY = 0x00800000,
TEXTFIELD_LIMITED = 0x01000000,
TEXTFIELD_OVERSTRIKE = 0x02000000,
TEXTFIELD_AUTOGRAY = 0x04000000,
TEXTFIELD_AUTOHIDE = 0x08000000,
TEXTFIELD_NORMAL = FRAME_SUNKEN|FRAME_THICK
}
enum {
TOGGLEBUTTON_AUTOGRAY = 0x00800000,
TOGGLEBUTTON_AUTOHIDE = 0x01000000,
TOGGLEBUTTON_TOOLBAR = 0x02000000,
TOGGLEBUTTON_KEEPSTATE = 0x04000000,
TOGGLEBUTTON_NORMAL = FRAME_RAISED|FRAME_THICK|JUSTIFY_NORMAL|ICON_BEFORE_TEXT
}
enum {
TOOLBARGRIP_SINGLE = 0,
TOOLBARGRIP_DOUBLE = 0x00008000
}
enum {
TOOLBARTAB_HORIZONTAL = 0,
TOOLBARTAB_VERTICAL = 0x00008000
}
enum {
TOOLTIP_PERMANENT = 0x00020000,
TOOLTIP_VARIABLE = 0x00040000,
TOOLTIP_NORMAL = 0
}
enum {
DECOR_NONE = 0,
DECOR_TITLE = 0x00020000,
DECOR_MINIMIZE = 0x00040000,
DECOR_MAXIMIZE = 0x00080000,
DECOR_CLOSE = 0x00100000,
DECOR_BORDER = 0x00200000,
DECOR_SHRINKABLE = 0x00400000,
DECOR_STRETCHABLE = 0x00800000,
DECOR_RESIZE = DECOR_SHRINKABLE|DECOR_STRETCHABLE,
DECOR_MENU = 0x01000000,
DECOR_ALL = (DECOR_TITLE|DECOR_MINIMIZE|DECOR_MAXIMIZE|DECOR_CLOSE|DECOR_BORDER|DECOR_SHRINKABLE|DECOR_STRETCHABLE|DECOR_MENU)
}
enum {
PLACEMENT_DEFAULT,
PLACEMENT_VISIBLE,
PLACEMENT_CURSOR,
PLACEMENT_OWNER,
PLACEMENT_SCREEN,
PLACEMENT_MAXIMIZED
}
enum {
TREELIST_EXTENDEDSELECT = 0,
TREELIST_SINGLESELECT = 0x00100000,
TREELIST_BROWSESELECT = 0x00200000,
TREELIST_MULTIPLESELECT = 0x00300000,
TREELIST_AUTOSELECT = 0x00400000,
TREELIST_SHOWS_LINES = 0x00800000,
TREELIST_SHOWS_BOXES = 0x01000000,
TREELIST_ROOT_BOXES = 0x02000000,
TREELIST_NORMAL = TREELIST_EXTENDEDSELECT
}
enum { TREELISTBOX_NORMAL = 0 }
enum {
CatNotAssigned = 0,
CatControl = 1,
CatFormat = 2,
CatSurrogate = 3,
CatOther = 4,
CatMarkNonSpacing = 5,
CatMarkSpacingCombining = 6,
CatMarkEnclosing = 7,
CatSeparatorSpace = 8,
CatSeparatorLine = 9,
CatSeparatorParagraph = 10,
CatLetterUpper = 11,
CatLetterLower = 12,
CatLetterTitle = 13,
CatLetterModifier = 14,
CatLetterOther = 15,
CatNumberLetter = 16,
CatNumberDecimal = 17,
CatNumberOther = 18,
CatPunctConnector = 19,
CatPunctDash = 20,
CatPunctOpen = 21,
CatPunctClose = 22,
CatPunctInitial = 23,
CatPunctFinal = 24,
CatPunctOther = 25,
CatSymbolMath = 26,
CatSymbolCurrency = 27,
CatSymbolModifier = 28,
CatSymbolOther = 29
}
enum {
DirL = 0,
DirLRE = 1,
DirLRO = 2,
DirR = 3,
DirAL = 4,
DirRLE = 5,
DirRLO = 6,
DirPDF = 7,
DirEN = 8,
DirES = 9,
DirET = 10,
DirAN = 11,
DirCS = 12,
DirNSM = 13,
DirBN = 14,
DirB = 15,
DirS = 16,
DirWS = 17,
DirON = 18
}
enum {
NonJoining = 0,
RightJoining = 1,
DualJoining = 2,
JoinCausing = 3
}
enum {
CombBelowLeftAtt = 200,
CombBelowAtt = 202,
CombBelowRightAtt = 204,
CombLeftAtt = 208,
CombRightAtt = 210,
CombAboveLeftAtt = 212,
CombAboveAtt = 214,
CombAboveRightAtt = 216,
CombBelowLeft = 218,
CombBelow = 220,
CombBelowRight = 222,
CombLeft = 224,
CombRight = 226,
CombAboveLeft = 228,
CombAbove = 230,
CombAboveRight = 232,
CombDoubleBelow = 233,
CombDoubleAbove = 234,
CombIotaSub = 240
}
enum {
DecNone = 0,
DecFont = 1,
DecNoBreak = 2,
DecInitial = 3,
DecMedial = 4,
DecFinal = 5,
DecIsolated = 6,
DecCircle = 7,
DecSuper = 8,
DecSub = 9,
DecVertical = 10,
DecWide = 11,
DecNarrow = 12,
DecSmall = 13,
DecSquare = 14,
DecFraction = 15,
DecCompat = 16,
DecCanonical = 17
}
enum {
BreakUnknown = 0,
BreakMandarory = 1,
BreakReturn = 2,
BreakLineFeed = 3,
BreakCombMark = 4,
BreakNextLine = 5,
BreakSurrogate = 6,
BreakWordJoiner = 7,
BreakZWSpace = 8,
BreakGlue = 9,
BreakContingent = 10,
BreakSpace = 11,
BreakBoth = 12,
BreakAfter = 13,
BreakBefore = 14,
BreakHyphen = 15,
BreakOpen = 16,
BreakClose = 17,
BreakQuote = 18,
BreakExclaim = 19,
BreakInsep = 20,
BreakNonStart = 21,
BreakInfix = 22,
BreakNumeric = 23,
BreakPostfix = 24,
BreakPrefix = 25,
BreakSymbol = 26,
BreakOrdinary = 27,
BreakIdeograph = 28,
BreakComplex = 29
}
enum {
ScriptCommon = 0,
ScriptInherited = 1,
ScriptLatin = 2,
ScriptGreek = 3,
ScriptCyrillic = 4,
ScriptArmenian = 5,
ScriptGeorgian = 6,
ScriptRunic = 7,
ScriptOgham = 8,
ScriptHebrew = 9,
ScriptArabic = 10,
ScriptSyriac = 11,
ScriptThaana = 12,
ScriptDevanagari = 13,
ScriptBengali = 14,
ScriptGurmukhi = 15,
ScriptGujarati = 16,
ScriptOriya = 17,
ScriptTamil = 18,
ScriptTelugu = 19,
ScriptKannada = 20,
ScriptMalayalam = 21,
ScriptSinhala = 22,
ScriptThai = 23,
ScriptLao = 24,
ScriptTibetan = 25,
ScriptMyanmar = 26,
ScriptKhmer = 27,
ScriptHan = 28,
ScriptHiragana = 29,
ScriptKatakana = 30,
ScriptHangul = 31,
ScriptBopomofo = 32,
ScriptYi = 33,
ScriptEthiopic = 34,
ScriptCherokee = 35,
ScriptCanadianAboriginal = 36,
ScriptMongolian = 37,
ScriptGothic = 38,
ScriptTagalog = 39,
ScriptHanunoo = 40,
ScriptBuhid = 41,
ScriptTagbanwa = 42,
ScriptLimbu = 43,
ScriptTaiLe = 44,
ScriptUgaritic = 45,
ScriptOsmanya = 46,
ScriptCypriot = 47,
ScriptShavian = 48,
ScriptDeseret = 49,
ScriptKatakanaHiragana = 50
}
enum FXVisualOptions {
VISUAL_DEFAULT = 0,
VISUAL_MONOCHROME = 1,
VISUAL_BEST = 2,
VISUAL_INDEXCOLOR = 4,
VISUAL_GRAYSCALE = 8,
VISUAL_TRUECOLOR = 16,
VISUAL_OWNCOLORMAP = 32,
VISUAL_DOUBLEBUFFER = 64,
VISUAL_STEREO = 128,
VISUAL_NOACCEL = 256,
VISUAL_SWAP_COPY = 512
}
enum FXVisualType {
VISUALTYPE_UNKNOWN,
VISUALTYPE_MONO,
VISUALTYPE_TRUE,
VISUALTYPE_INDEX,
VISUALTYPE_GRAY
}
enum {
LAYOUT_NORMAL = 0,
LAYOUT_SIDE_TOP = 0,
LAYOUT_SIDE_BOTTOM = 0x00000001,
LAYOUT_SIDE_LEFT = 0x00000002,
LAYOUT_SIDE_RIGHT = LAYOUT_SIDE_LEFT|LAYOUT_SIDE_BOTTOM,
LAYOUT_FILL_COLUMN = 0x00000001,
LAYOUT_FILL_ROW = 0x00000002,
LAYOUT_LEFT = 0,
LAYOUT_RIGHT = 0x00000004,
LAYOUT_CENTER_X = 0x00000008,
LAYOUT_FIX_X = LAYOUT_RIGHT|LAYOUT_CENTER_X,
LAYOUT_TOP = 0,
LAYOUT_BOTTOM = 0x00000010,
LAYOUT_CENTER_Y = 0x00000020,
LAYOUT_FIX_Y = LAYOUT_BOTTOM|LAYOUT_CENTER_Y,
LAYOUT_DOCK_SAME = 0,
LAYOUT_DOCK_NEXT = 0x00000040,
LAYOUT_RESERVED_1 = 0x00000080,
LAYOUT_FIX_WIDTH = 0x00000100,
LAYOUT_FIX_HEIGHT = 0x00000200,
LAYOUT_MIN_WIDTH = 0,
LAYOUT_MIN_HEIGHT = 0,
LAYOUT_FILL_X = 0x00000400,
LAYOUT_FILL_Y = 0x00000800,
LAYOUT_FILL = LAYOUT_FILL_X|LAYOUT_FILL_Y,
LAYOUT_EXPLICIT = LAYOUT_FIX_X|LAYOUT_FIX_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
}
enum {
FRAME_NONE = 0,
FRAME_SUNKEN = 0x00001000,
FRAME_RAISED = 0x00002000,
FRAME_THICK = 0x00004000,
FRAME_GROOVE = FRAME_THICK,
FRAME_RIDGE = FRAME_THICK|FRAME_RAISED|FRAME_SUNKEN,
FRAME_LINE = FRAME_RAISED|FRAME_SUNKEN,
FRAME_NORMAL = FRAME_SUNKEN|FRAME_THICK
}
enum {
PACK_NORMAL = 0,
PACK_UNIFORM_HEIGHT = 0x00008000,
PACK_UNIFORM_WIDTH = 0x00010000
}
Functions
FXHotKey parseAccel (const FXString &string)
FXString unparseAccel (FXHotKey key)
FXHotKey parseHotKey (const FXString &string)
FXint findHotKey (const FXString &string)
FXString stripHotKey (const FXString &string)
bool fxcheckBMP (FXStream &store)
bool fxloadBMP (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsaveBMP (FXStream &store, const FXColor *data, FXint width, FXint height)
bool fxcheckICO (FXStream &store)
bool fxloadICO (FXStream &store, FXColor *&data, FXint &width, FXint &height, FXint &xspot, FXint &yspot)
bool fxsaveICO (FXStream &store, const FXColor *data, FXint width, FXint height, FXint xspot=-1, FXint yspot=-1)
FXDate operator+ (const FXDate &d, FXint x)
FXDate operator+ (FXint x, const FXDate &d)
FXint operator- (const FXDate &a, const FXDate &b)
FXStream & operator<< (FXStream &store, const FXDate &d)
FXStream & operator>> (FXStream &store, FXDate &d)
FXuint fxrandom (FXuint &seed)
FXint fxmalloc (void **ptr, unsigned long size)
FXint fxcalloc (void **ptr, unsigned long size)
FXint fxresize (void **ptr, unsigned long size)
FXint fxmemdup (void **ptr, const void *src, unsigned long size)
void fxfree (void **ptr)
void fxerror (const char *format,...) FX_PRINTF(1
void void fxwarning (const char *format,...) FX_PRINTF(1
void void void fxmessage (const char *format,...) FX_PRINTF(1
void void void void fxassert (const char *expression, const char *filename, unsigned int lineno)
void fxtrace (unsigned int level, const char *format,...) FX_PRINTF(2
void void fxsleep (unsigned int n)
bool fxfilematch (const char *pattern, const char *string, FXuint flags=(FILEMATCH_NOESCAPE|FILEMATCH_FILE_NAME))
FXColor makeHiliteColor (FXColor clr)
FXColor makeShadowColor (FXColor clr)
FXint fxgetpid ()
bool fxtoDOS (FXchar *&string, FXint &len)
bool fxfromDOS (FXchar *&string, FXint &len)
FXchar * fxstrdup (const FXchar *str)
FXuint fxstrhash (const FXchar *str)
FXColor fxcolorfromname (const FXchar *colorname)
FXchar * fxnamefromcolor (FXchar *colorname, FXColor color)
void fxrgb_to_hsv (FXfloat &h, FXfloat &s, FXfloat &v, FXfloat r, FXfloat g, FXfloat b)
void fxhsv_to_rgb (FXfloat &r, FXfloat &g, FXfloat &b, FXfloat h, FXfloat s, FXfloat v)
FXint fxieeefloatclass (FXfloat number)
FXint fxieeedoubleclass (FXdouble number)
FXwchar fxkeysym2ucs (FXwchar sym)
FXwchar fxucs2keysym (FXwchar ucs)
FXint fxparsegeometry (const FXchar *string, FXint &x, FXint &y, FXint &w, FXint &h)
FXbool fxisconsole (const FXchar *path)
FXwchar wc (const FXchar *ptr)
FXwchar wc (const FXnchar *ptr)
FXint wclen (const FXchar *ptr)
FXint wclen (const FXnchar *ptr)
FXint wcvalidate (const FXchar *string, FXint pos)
FXint wcvalidate (const FXnchar *string, FXint pos)
FXint wcinc (const FXchar *string, FXint pos)
FXint wcinc (const FXnchar *string, FXint pos)
FXint wcdec (const FXchar *string, FXint pos)
FXint wcdec (const FXnchar *string, FXint pos)
FXint utfslen (const FXwchar *str, FXint n)
FXint utfslen (const FXwchar *str)
FXint utfslen (const FXnchar *str, FXint n)
FXint utfslen (const FXnchar *str)
FXint wcslen (const FXchar *str, FXint n)
FXint wcslen (const FXchar *str)
FXint ncslen (const FXchar *str, FXint n)
FXint ncslen (const FXchar *str)
FXint utf2wcs (FXwchar *dst, const FXchar *src, FXint n)
FXint utf2wcs (FXwchar *dst, const FXchar *src)
FXint utf2ncs (FXnchar *dst, const FXchar *src, FXint n)
FXint utf2ncs (FXnchar *dst, const FXchar *src)
FXint wc2utfs (FXchar *dst, const FXwchar *src, FXint n)
FXint wc2utfs (FXchar *dst, const FXwchar *src)
FXint nc2utfs (FXchar *dst, const FXnchar *src, FXint n)
FXint nc2utfs (FXchar *dst, const FXnchar *src)
void * fxdllOpen (const FXchar *dllname)
void fxdllClose (void *dllhandle)
void * fxdllSymbol (void *dllhandle, const FXchar *dllsymbol)
FXString fxdllError ()
template<class TYPE >
void constructElms (TYPE *ptr, unsigned long n)
template<class TYPE >
void destructElms (TYPE *ptr, unsigned long n)
template<class TYPE >
void copyElms (TYPE *dst, const TYPE *src, unsigned long n)
template<class TYPE >
void moveElms (TYPE *dst, const TYPE *src, unsigned long n)
template<class TYPE >
void fillElms (TYPE *dst, const TYPE &src, unsigned long n)
template<class TYPE >
void clearElms (TYPE *dst, unsigned long n)
template<class TYPE >
void saveElms (FXStream &store, const TYPE *ptr, unsigned long n)
template<class TYPE >
void loadElms (FXStream &store, TYPE *ptr, unsigned long n)
template<class TYPE >
FXint allocElms (TYPE *&ptr, unsigned long n)
template<class TYPE >
FXint callocElms (TYPE *&ptr, unsigned long n)
template<class TYPE >
FXint dupElms (TYPE *&ptr, const TYPE *src, unsigned long n)
template<class TYPE >
FXint resizeElms (TYPE *&ptr, unsigned long n)
template<class TYPE >
void freeElms (TYPE *&ptr)
void constructElms (FXuchar *, unsigned long)
void constructElms (FXchar *, unsigned long)
void constructElms (FXushort *, unsigned long)
void constructElms (FXshort *, unsigned long)
void constructElms (FXuint *, unsigned long)
void constructElms (FXint *, unsigned long)
void constructElms (FXfloat *, unsigned long)
void constructElms (FXdouble *, unsigned long)
void destructElms (FXuchar *, unsigned long)
void destructElms (FXchar *, unsigned long)
void destructElms (FXushort *, unsigned long)
void destructElms (FXshort *, unsigned long)
void destructElms (FXuint *, unsigned long)
void destructElms (FXint *, unsigned long)
void destructElms (FXfloat *, unsigned long)
void destructElms (FXdouble *, unsigned long)
void copyElms (FXuchar *dst, const FXuchar *src, unsigned long n)
void copyElms (FXchar *dst, const FXchar *src, unsigned long n)
void copyElms (FXushort *dst, const FXushort *src, unsigned long n)
void copyElms (FXshort *dst, const FXshort *src, unsigned long n)
void copyElms (FXuint *dst, const FXuint *src, unsigned long n)
void copyElms (FXint *dst, const FXint *src, unsigned long n)
void copyElms (FXfloat *dst, const FXfloat *src, unsigned long n)
void copyElms (FXdouble *dst, const FXdouble *src, unsigned long n)
template<class TYPE >
void copyElms (TYPE **dst, const TYPE **src, unsigned long n)
void moveElms (FXuchar *dst, const FXuchar *src, unsigned long n)
void moveElms (FXchar *dst, const FXchar *src, unsigned long n)
void moveElms (FXushort *dst, const FXushort *src, unsigned long n)
void moveElms (FXshort *dst, const FXshort *src, unsigned long n)
void moveElms (FXuint *dst, const FXuint *src, unsigned long n)
void moveElms (FXint *dst, const FXint *src, unsigned long n)
void moveElms (FXfloat *dst, const FXfloat *src, unsigned long n)
void moveElms (FXdouble *dst, const FXdouble *src, unsigned long n)
template<class TYPE >
void moveElms (TYPE **dst, const TYPE **src, unsigned long n)
void fillElms (FXuchar *dst, const FXuchar &src, unsigned long n)
void fillElms (FXchar *dst, const FXchar &src, unsigned long n)
void saveElms (FXStream &store, const FXuchar *ptr, unsigned long n)
void saveElms (FXStream &store, const FXchar *ptr, unsigned long n)
void saveElms (FXStream &store, const FXushort *ptr, unsigned long n)
void saveElms (FXStream &store, const FXshort *ptr, unsigned long n)
void saveElms (FXStream &store, const FXuint *ptr, unsigned long n)
void saveElms (FXStream &store, const FXint *ptr, unsigned long n)
void saveElms (FXStream &store, const FXfloat *ptr, unsigned long n)
void saveElms (FXStream &store, const FXdouble *ptr, unsigned long n)
void loadElms (FXStream &store, FXuchar *ptr, unsigned long n)
void loadElms (FXStream &store, FXchar *ptr, unsigned long n)
void loadElms (FXStream &store, FXushort *ptr, unsigned long n)
void loadElms (FXStream &store, FXshort *ptr, unsigned long n)
void loadElms (FXStream &store, FXuint *ptr, unsigned long n)
void loadElms (FXStream &store, FXint *ptr, unsigned long n)
void loadElms (FXStream &store, FXfloat *ptr, unsigned long n)
void loadElms (FXStream &store, FXdouble *ptr, unsigned long n)
bool overlap (const FXExtentd &a, const FXExtentd &b)
FXExtentd unite (const FXExtentd &a, const FXExtentd &b)
FXExtentd intersect (const FXExtentd &a, const FXExtentd &b)
FXStream & operator<< (FXStream &store, const FXExtentd &ext)
FXStream & operator>> (FXStream &store, FXExtentd &ext)
bool overlap (const FXExtentf &a, const FXExtentf &b)
FXExtentf unite (const FXExtentf &a, const FXExtentf &b)
FXExtentf intersect (const FXExtentf &a, const FXExtentf &b)
FXStream & operator<< (FXStream &store, const FXExtentf &ext)
FXStream & operator>> (FXStream &store, FXExtentf &ext)
bool fxcheckGIF (FXStream &store)
bool fxloadGIF (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsaveGIF (FXStream &store, const FXColor *data, FXint width, FXint height, bool fast=true)
void glUseFXFont (FXFont *font, int first, int count, int list)
bool fxcheckIFF (FXStream &store)
bool fxloadIFF (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxcheckJPG (FXStream &store)
bool fxloadJPG (FXStream &store, FXColor *&data, FXint &width, FXint &height, FXint &quality)
bool fxsaveJPG (FXStream &store, const FXColor *data, FXint width, FXint height, FXint quality)
FXMat3d operator * (FXdouble x, const FXMat3d &a)
FXMat3d operator * (const FXMat3d &a, FXdouble x)
FXMat3d operator/ (const FXMat3d &a, FXdouble x)
FXMat3d operator/ (FXdouble x, const FXMat3d &a)
FXStream & operator<< (FXStream &store, const FXMat3d &m)
FXStream & operator>> (FXStream &store, FXMat3d &m)
FXMat3f operator * (FXfloat x, const FXMat3f &a)
FXMat3f operator * (const FXMat3f &a, FXfloat x)
FXMat3f operator/ (const FXMat3f &a, FXfloat x)
FXMat3f operator/ (FXfloat x, const FXMat3f &a)
FXStream & operator<< (FXStream &store, const FXMat3f &m)
FXStream & operator>> (FXStream &store, FXMat3f &m)
FXMat4d operator * (FXdouble x, const FXMat4d &a)
FXMat4d operator * (const FXMat4d &a, FXdouble x)
FXMat4d operator/ (const FXMat4d &a, FXdouble x)
FXMat4d operator/ (FXdouble x, const FXMat4d &a)
FXStream & operator<< (FXStream &store, const FXMat4d &m)
FXStream & operator>> (FXStream &store, FXMat4d &m)
FXMat4f operator * (FXfloat x, const FXMat4f &a)
FXMat4f operator * (const FXMat4f &a, FXfloat x)
FXMat4f operator/ (const FXMat4f &a, FXfloat x)
FXMat4f operator/ (FXfloat x, const FXMat4f &a)
FXStream & operator<< (FXStream &store, const FXMat4f &m)
FXStream & operator>> (FXStream &store, FXMat4f &m)
bool fxcheckPCX (FXStream &store)
bool fxloadPCX (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsavePCX (FXStream &store, const FXColor *data, FXint width, FXint height)
bool fxcheckPNG (FXStream &store)
bool fxloadPNG (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsavePNG (FXStream &store, const FXColor *data, FXint width, FXint height)
FXPoint operator * (const FXPoint &p, FXshort c)
FXPoint operator * (FXshort c, const FXPoint &p)
FXPoint operator/ (const FXPoint &p, FXshort c)
FXPoint operator/ (FXshort c, const FXPoint &p)
FXStream & operator<< (FXStream &store, const FXPoint &p)
FXStream & operator>> (FXStream &store, FXPoint &p)
bool fxcheckPPM (FXStream &store)
bool fxloadPPM (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsavePPM (FXStream &store, const FXColor *data, FXint width, FXint height)
bool overlap (const FXRanged &a, const FXRanged &b)
FXRanged unite (const FXRanged &a, const FXRanged &b)
FXRanged intersect (const FXRanged &a, const FXRanged &b)
FXStream & operator<< (FXStream &store, const FXRanged &bounds)
FXStream & operator>> (FXStream &store, FXRanged &bounds)
bool overlap (const FXRangef &a, const FXRangef &b)
FXRangef unite (const FXRangef &a, const FXRangef &b)
FXRangef intersect (const FXRangef &a, const FXRangef &b)
FXStream & operator<< (FXStream &store, const FXRangef &bounds)
FXStream & operator>> (FXStream &store, FXRangef &bounds)
bool fxcheckRAS (FXStream &store)
bool fxloadRAS (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsaveRAS (FXStream &store, const FXColor *data, FXint width, FXint height)
bool overlap (const FXRectangle &a, const FXRectangle &b)
FXStream & operator<< (FXStream &store, const FXRectangle &r)
FXStream & operator>> (FXStream &store, FXRectangle &r)
FXStream & operator<< (FXStream &store, const FXRex &s)
FXStream & operator>> (FXStream &store, FXRex &s)
bool fxcheckRGB (FXStream &store)
bool fxloadRGB (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsaveRGB (FXStream &store, const FXColor *data, FXint width, FXint height)
FXSize operator * (const FXSize &s, FXshort c)
FXSize operator * (FXshort c, const FXSize &s)
FXSize operator/ (const FXSize &s, FXshort c)
FXSize operator/ (FXshort c, const FXSize &s)
FXStream & operator<< (FXStream &store, const FXSize &s)
FXStream & operator>> (FXStream &store, FXSize &s)
bool overlap (const FXRanged &a, const FXSphered &b)
bool overlap (const FXSphered &a, const FXRanged &b)
bool overlap (const FXSphered &a, const FXSphered &b)
FXStream & operator<< (FXStream &store, const FXSphered &sphere)
FXStream & operator>> (FXStream &store, FXSphered &sphere)
bool overlap (const FXRangef &a, const FXSpheref &b)
bool overlap (const FXSpheref &a, const FXRangef &b)
bool overlap (const FXSpheref &a, const FXSpheref &b)
FXStream & operator<< (FXStream &store, const FXSpheref &sphere)
FXStream & operator>> (FXStream &store, FXSpheref &sphere)
void swap (FXString &a, FXString &b)
FXint compare (const FXchar *s1, const FXchar *s2)
FXint compare (const FXchar *s1, const FXString &s2)
FXint compare (const FXString &s1, const FXchar *s2)
FXint compare (const FXString &s1, const FXString &s2)
FXint compare (const FXchar *s1, const FXchar *s2, FXint n)
FXint compare (const FXchar *s1, const FXString &s2, FXint n)
FXint compare (const FXString &s1, const FXchar *s2, FXint n)
FXint compare (const FXString &s1, const FXString &s2, FXint n)
FXint comparecase (const FXchar *s1, const FXchar *s2)
FXint comparecase (const FXchar *s1, const FXString &s2)
FXint comparecase (const FXString &s1, const FXchar *s2)
FXint comparecase (const FXString &s1, const FXString &s2)
FXint comparecase (const FXchar *s1, const FXchar *s2, FXint n)
FXint comparecase (const FXchar *s1, const FXString &s2, FXint n)
FXint comparecase (const FXString &s1, const FXchar *s2, FXint n)
FXint comparecase (const FXString &s1, const FXString &s2, FXint n)
FXint compareversion (const FXchar *s1, const FXchar *s2)
FXint compareversion (const FXchar *s1, const FXString &s2)
FXint compareversion (const FXString &s1, const FXchar *s2)
FXint compareversion (const FXString &s1, const FXString &s2)
bool operator== (const FXString &s1, const FXString &s2)
bool operator== (const FXString &s1, const FXchar *s2)
bool operator== (const FXchar *s1, const FXString &s2)
bool operator!= (const FXString &s1, const FXString &s2)
bool operator!= (const FXString &s1, const FXchar *s2)
bool operator!= (const FXchar *s1, const FXString &s2)
bool operator< (const FXString &s1, const FXString &s2)
bool operator< (const FXString &s1, const FXchar *s2)
bool operator< (const FXchar *s1, const FXString &s2)
bool operator<= (const FXString &s1, const FXString &s2)
bool operator<= (const FXString &s1, const FXchar *s2)
bool operator<= (const FXchar *s1, const FXString &s2)
bool operator> (const FXString &s1, const FXString &s2)
bool operator> (const FXString &s1, const FXchar *s2)
bool operator> (const FXchar *s1, const FXString &s2)
bool operator>= (const FXString &s1, const FXString &s2)
bool operator>= (const FXString &s1, const FXchar *s2)
bool operator>= (const FXchar *s1, const FXString &s2)
FXString operator+ (const FXString &s1, const FXString &s2)
FXString operator+ (const FXString &s1, const FXchar *s2)
FXString operator+ (const FXString &s1, const FXwchar *s2)
FXString operator+ (const FXString &s1, const FXnchar *s2)
FXString operator+ (const FXchar *s1, const FXString &s2)
FXString operator+ (const FXwchar *s1, const FXString &s2)
FXString operator+ (const FXnchar *s1, const FXString &s2)
FXString operator+ (const FXString &s, FXchar c)
FXString operator+ (FXchar c, const FXString &s)
FXStream & operator<< (FXStream &store, const FXString &s)
FXStream & operator>> (FXStream &store, FXString &s)
FXString FXStringFormat (const FXchar *fmt,...) FX_PRINTF(1
FXString FXString FXStringVFormat (const FXchar *fmt, va_list args)
FXString FXStringVal (FXint num, FXint base=10)
FXString FXStringVal (FXuint num, FXint base=10)
FXString FXStringVal (FXlong num, FXint base=10)
FXString FXStringVal (FXulong num, FXint base=10)
FXString FXStringVal (FXfloat num, FXint prec=6, FXint exp=MAYBE)
FXString FXStringVal (FXdouble num, FXint prec=6, FXint exp=MAYBE)
FXint FXIntVal (const FXString &s, FXint base=10)
FXuint FXUIntVal (const FXString &s, FXint base=10)
FXlong FXLongVal (const FXString &s, FXint base=10)
FXulong FXULongVal (const FXString &s, FXint base=10)
FXfloat FXFloatVal (const FXString &s)
FXdouble FXDoubleVal (const FXString &s)
FXString fromAscii (const FXString &s)
FXString toAscii (const FXString &s)
FXString escape (const FXString &s)
FXString unescape (const FXString &s)
FXString normalize (const FXString &s)
FXString decompose (const FXString &s, FXuint kind)
FXString compose (const FXString &s, FXuint kind)
FXString & unixToDos (FXString &str)
FXString & dosToUnix (FXString &str)
bool fxcheckTGA (FXStream &store)
bool fxloadTGA (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsaveTGA (FXStream &store, const FXColor *data, FXint width, FXint height)
bool fxcheckTIF (FXStream &store)
bool fxloadTIF (FXStream &store, FXColor *&data, FXint &width, FXint &height, FXushort &codec)
bool fxsaveTIF (FXStream &store, const FXColor *data, FXint width, FXint height, FXushort codec)
FXVec2d operator * (const FXVec2d &a, FXdouble n)
FXVec2d operator * (FXdouble n, const FXVec2d &a)
FXVec2d operator/ (const FXVec2d &a, FXdouble n)
FXVec2d operator/ (FXdouble n, const FXVec2d &a)
bool operator== (const FXVec2d &a, FXdouble n)
bool operator!= (const FXVec2d &a, FXdouble n)
bool operator== (FXdouble n, const FXVec2d &a)
bool operator!= (FXdouble n, const FXVec2d &a)
bool operator< (const FXVec2d &a, FXdouble n)
bool operator<= (const FXVec2d &a, FXdouble n)
bool operator> (const FXVec2d &a, FXdouble n)
bool operator>= (const FXVec2d &a, FXdouble n)
bool operator< (FXdouble n, const FXVec2d &a)
bool operator<= (FXdouble n, const FXVec2d &a)
bool operator> (FXdouble n, const FXVec2d &a)
bool operator>= (FXdouble n, const FXVec2d &a)
FXVec2d lo (const FXVec2d &a, const FXVec2d &b)
FXVec2d hi (const FXVec2d &a, const FXVec2d &b)
FXVec2d normalize (const FXVec2d &v)
FXStream & operator<< (FXStream &store, const FXVec2d &v)
FXStream & operator>> (FXStream &store, FXVec2d &v)
FXVec2f operator * (const FXVec2f &a, FXfloat n)
FXVec2f operator * (FXfloat n, const FXVec2f &a)
FXVec2f operator/ (const FXVec2f &a, FXfloat n)
FXVec2f operator/ (FXfloat n, const FXVec2f &a)
bool operator== (const FXVec2f &a, FXfloat n)
bool operator!= (const FXVec2f &a, FXfloat n)
bool operator== (FXfloat n, const FXVec2f &a)
bool operator!= (FXfloat n, const FXVec2f &a)
bool operator< (const FXVec2f &a, FXfloat n)
bool operator<= (const FXVec2f &a, FXfloat n)
bool operator> (const FXVec2f &a, FXfloat n)
bool operator>= (const FXVec2f &a, FXfloat n)
bool operator< (FXfloat n, const FXVec2f &a)
bool operator<= (FXfloat n, const FXVec2f &a)
bool operator> (FXfloat n, const FXVec2f &a)
bool operator>= (FXfloat n, const FXVec2f &a)
FXVec2f lo (const FXVec2f &a, const FXVec2f &b)
FXVec2f hi (const FXVec2f &a, const FXVec2f &b)
FXVec2f normalize (const FXVec2f &v)
FXStream & operator<< (FXStream &store, const FXVec2f &v)
FXStream & operator>> (FXStream &store, FXVec2f &v)
FXVec3d operator * (const FXVec3d &a, FXdouble n)
FXVec3d operator * (FXdouble n, const FXVec3d &a)
FXVec3d operator/ (const FXVec3d &a, FXdouble n)
FXVec3d operator/ (FXdouble n, const FXVec3d &a)
bool operator== (const FXVec3d &a, FXdouble n)
bool operator!= (const FXVec3d &a, FXdouble n)
bool operator== (FXdouble n, const FXVec3d &a)
bool operator!= (FXdouble n, const FXVec3d &a)
bool operator< (const FXVec3d &a, FXdouble n)
bool operator<= (const FXVec3d &a, FXdouble n)
bool operator> (const FXVec3d &a, FXdouble n)
bool operator>= (const FXVec3d &a, FXdouble n)
bool operator< (FXdouble n, const FXVec3d &a)
bool operator<= (FXdouble n, const FXVec3d &a)
bool operator> (FXdouble n, const FXVec3d &a)
bool operator>= (FXdouble n, const FXVec3d &a)
FXVec3d lo (const FXVec3d &a, const FXVec3d &b)
FXVec3d hi (const FXVec3d &a, const FXVec3d &b)
FXVec3d normal (const FXVec3d &a, const FXVec3d &b, const FXVec3d &c)
FXVec3d normal (const FXVec3d &a, const FXVec3d &b, const FXVec3d &c, const FXVec3d &d)
FXVec3d normalize (const FXVec3d &v)
FXStream & operator<< (FXStream &store, const FXVec3d &v)
FXStream & operator>> (FXStream &store, FXVec3d &v)
FXVec3f operator * (const FXVec3f &a, FXfloat n)
FXVec3f operator * (FXfloat n, const FXVec3f &a)
FXVec3f operator/ (const FXVec3f &a, FXfloat n)
FXVec3f operator/ (FXfloat n, const FXVec3f &a)
bool operator== (const FXVec3f &a, FXfloat n)
bool operator!= (const FXVec3f &a, FXfloat n)
bool operator== (FXfloat n, const FXVec3f &a)
bool operator!= (FXfloat n, const FXVec3f &a)
bool operator< (const FXVec3f &a, FXfloat n)
bool operator<= (const FXVec3f &a, FXfloat n)
bool operator> (const FXVec3f &a, FXfloat n)
bool operator>= (const FXVec3f &a, FXfloat n)
bool operator< (FXfloat n, const FXVec3f &a)
bool operator<= (FXfloat n, const FXVec3f &a)
bool operator> (FXfloat n, const FXVec3f &a)
bool operator>= (FXfloat n, const FXVec3f &a)
FXVec3f lo (const FXVec3f &a, const FXVec3f &b)
FXVec3f hi (const FXVec3f &a, const FXVec3f &b)
FXVec3f normal (const FXVec3f &a, const FXVec3f &b, const FXVec3f &c)
FXVec3f normal (const FXVec3f &a, const FXVec3f &b, const FXVec3f &c, const FXVec3f &d)
FXVec3f normalize (const FXVec3f &v)
FXStream & operator<< (FXStream &store, const FXVec3f &v)
FXStream & operator>> (FXStream &store, FXVec3f &v)
FXVec4d operator * (const FXVec4d &a, FXdouble n)
FXVec4d operator * (FXdouble n, const FXVec4d &a)
FXVec4d operator/ (const FXVec4d &a, FXdouble n)
FXVec4d operator/ (FXdouble n, const FXVec4d &a)
bool operator== (const FXVec4d &a, FXdouble n)
bool operator!= (const FXVec4d &a, FXdouble n)
bool operator== (FXdouble n, const FXVec4d &a)
bool operator!= (FXdouble n, const FXVec4d &a)
bool operator< (const FXVec4d &a, FXdouble n)
bool operator<= (const FXVec4d &a, FXdouble n)
bool operator> (const FXVec4d &a, FXdouble n)
bool operator>= (const FXVec4d &a, FXdouble n)
bool operator< (FXdouble n, const FXVec4d &a)
bool operator<= (FXdouble n, const FXVec4d &a)
bool operator> (FXdouble n, const FXVec4d &a)
bool operator>= (FXdouble n, const FXVec4d &a)
FXVec4d lo (const FXVec4d &a, const FXVec4d &b)
FXVec4d hi (const FXVec4d &a, const FXVec4d &b)
FXVec4d plane (const FXVec4d &vec)
FXVec4d plane (const FXVec3d &vec, FXdouble dist)
FXVec4d plane (const FXVec3d &vec, const FXVec3d &p)
FXVec4d plane (const FXVec3d &a, const FXVec3d &b, const FXVec3d &c)
FXVec4d normalize (const FXVec4d &v)
FXStream & operator<< (FXStream &store, const FXVec4d &v)
FXStream & operator>> (FXStream &store, FXVec4d &v)
FXVec4f operator * (const FXVec4f &a, FXfloat n)
FXVec4f operator * (FXfloat n, const FXVec4f &a)
FXVec4f operator/ (const FXVec4f &a, FXfloat n)
FXVec4f operator/ (FXfloat n, const FXVec4f &a)
bool operator== (const FXVec4f &a, FXfloat n)
bool operator!= (const FXVec4f &a, FXfloat n)
bool operator== (FXfloat n, const FXVec4f &a)
bool operator!= (FXfloat n, const FXVec4f &a)
bool operator< (const FXVec4f &a, FXfloat n)
bool operator<= (const FXVec4f &a, FXfloat n)
bool operator> (const FXVec4f &a, FXfloat n)
bool operator>= (const FXVec4f &a, FXfloat n)
bool operator< (FXfloat n, const FXVec4f &a)
bool operator<= (FXfloat n, const FXVec4f &a)
bool operator> (FXfloat n, const FXVec4f &a)
bool operator>= (FXfloat n, const FXVec4f &a)
FXVec4f lo (const FXVec4f &a, const FXVec4f &b)
FXVec4f hi (const FXVec4f &a, const FXVec4f &b)
FXVec4f plane (const FXVec4f &vec)
FXVec4f plane (const FXVec3f &vec, FXfloat dist)
FXVec4f plane (const FXVec3f &vec, const FXVec3f &p)
FXVec4f plane (const FXVec3f &a, const FXVec3f &b, const FXVec3f &c)
FXVec4f normalize (const FXVec4f &v)
FXStream & operator<< (FXStream &store, const FXVec4f &v)
FXStream & operator>> (FXStream &store, FXVec4f &v)
bool fxcheckXBM (FXStream &store)
bool fxloadXBM (FXColor *&data, const FXuchar *pix, const FXuchar *msk, FXint width, FXint height)
bool fxloadXBM (FXStream &store, FXColor *&data, FXint &width, FXint &height, FXint &hotx, FXint &hoty)
bool fxsaveXBM (FXStream &store, const FXColor *data, FXint width, FXint height, FXint hotx=-1, FXint hoty=-1)
bool fxsavePS (FXStream &store, const FXColor *data, FXint width, FXint height, FXint paperw=612, FXint paperh=792, FXint margin=35, bool color=true)
bool fxcheckXPM (FXStream &store)
bool fxloadXPM (const FXchar **pix, FXColor *&data, FXint &width, FXint &height)
bool fxloadXPM (FXStream &store, FXColor *&data, FXint &width, FXint &height)
bool fxsaveXPM (FXStream &store, const FXColor *data, FXint width, FXint height, bool fast=true)
Variables
const FXuchar fxversion [3]
unsigned int fxTraceLevel
Typedef Documentation
FXchar
typedef char FX::FXchar
FXuchar
typedef unsigned char FX::FXuchar
FXbool
typedef FXuchar FX::FXbool
FXushort
typedef unsigned short FX::FXushort
FXshort
typedef short FX::FXshort
FXuint
typedef unsigned int FX::FXuint
FXint
typedef int FX::FXint
FXfloat
typedef float FX::FXfloat
FXdouble
typedef double FX::FXdouble
FXObjectPtr
typedef FXObject* FX::FXObjectPtr
FXwchar
typedef wchar_t FX::FXwchar
FXnchar
typedef unsigned short FX::FXnchar
FXival
typedef long FX::FXival
FXuval
typedef unsigned long FX::FXuval
FXID
typedef unsigned long FX::FXID
FXTime
typedef long FX::FXTime
FXPixel
typedef unsigned long FX::FXPixel
FXColor
typedef FXuint FX::FXColor
FXHotKey
typedef FXuint FX::FXHotKey
FXDragType
typedef FXID FX::FXDragType
FXInputHandle
typedef FXint FX::FXInputHandle
FXRawEvent
typedef _XEvent FX::FXRawEvent
FXFoldingListSortFunc
typedef FXint(* FX::FXFoldingListSortFunc) (const FXFoldingItem *, const FXFoldingItem *)
Folding item collate function.
FXGLObjectList
typedef FXObjectListOf<FXGLObject> FX::FXGLObjectList
List of GL objects.
FXZSortFunc
typedef FXbool(* FX::FXZSortFunc) (FXfloat *&buffer, FXint &used, FXint &size)
FXHeaderItemList
typedef FXObjectListOf<FXHeaderItem> FX::FXHeaderItemList
List of FXHeaderItem's.
FXIconListSortFunc
typedef FXint(* FX::FXIconListSortFunc) (const FXIconItem *, const FXIconItem *)
Icon item collate function.
FXIconItemList
typedef FXObjectListOf<FXIconItem> FX::FXIconItemList
List of FXIconItem's.
FXListSortFunc
typedef FXint(* FX::FXListSortFunc) (const FXListItem *, const FXListItem *)
List item collate function.
FXListItemList
typedef FXObjectListOf<FXListItem> FX::FXListItemList
List of FXListItem's.
FXSelector
typedef FXuint FX::FXSelector
Association key.
FXThreadID
typedef unsigned long FX::FXThreadID
FXTreeListSortFunc
typedef FXint(* FX::FXTreeListSortFunc) (const FXTreeItem *, const FXTreeItem *)
Tree item collate function.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
KEY_VoidSymbol
Void symbol.
Miscellaneous
KEY_BackSpace
KEY_Tab
KEY_Linefeed
KEY_Clear
KEY_Return
KEY_Pause
KEY_Scroll_Lock
KEY_Sys_Req
KEY_Escape
KEY_Delete
KEY_Multi_key
Japanese.
KEY_Kanji
KEY_Muhenkan
KEY_Henkan_Mode
KEY_Henkan
KEY_Romaji
KEY_Hiragana
KEY_Katakana
KEY_Hiragana_Katakana
KEY_Zenkaku
KEY_Hankaku
KEY_Zenkaku_Hankaku
KEY_Touroku
KEY_Massyo
KEY_Kana_Lock
KEY_Kana_Shift
KEY_Eisu_Shift
KEY_Eisu_toggle
Cursor.
KEY_Home
KEY_Left
KEY_Up
KEY_Right
KEY_Down
KEY_Prior
KEY_Page_Up
KEY_Next
KEY_Page_Down
KEY_End
KEY_Begin
Functions.
KEY_Select
KEY_Print
KEY_Execute
KEY_Insert
KEY_Undo
KEY_Redo
KEY_Menu
KEY_Find
KEY_Cancel
KEY_Help
KEY_Break
KEY_Mode_switch
KEY_script_switch
KEY_Num_Lock
Keypad.
KEY_KP_Space
KEY_KP_Tab
KEY_KP_Enter
KEY_KP_F1
KEY_KP_F2
KEY_KP_F3
KEY_KP_F4
KEY_KP_Home
KEY_KP_Left
KEY_KP_Up
KEY_KP_Right
KEY_KP_Down
KEY_KP_Prior
KEY_KP_Page_Up
KEY_KP_Next
KEY_KP_Page_Down
KEY_KP_End
KEY_KP_Begin
KEY_KP_Insert
KEY_KP_Delete
KEY_KP_Equal
KEY_KP_Multiply
KEY_KP_Add
KEY_KP_Separator
KEY_KP_Subtract
KEY_KP_Decimal
KEY_KP_Divide
Keypad numbers.
KEY_KP_0
KEY_KP_1
KEY_KP_2
KEY_KP_3
KEY_KP_4
KEY_KP_5
KEY_KP_6
KEY_KP_7
KEY_KP_8
KEY_KP_9
Function keys.
KEY_F1
KEY_F2
KEY_F3
KEY_F4
KEY_F5
KEY_F6
KEY_F7
KEY_F8
KEY_F9
KEY_F10
KEY_F11
KEY_L1
KEY_F12
KEY_L2
KEY_F13
KEY_L3
KEY_F14
KEY_L4
KEY_F15
KEY_L5
KEY_F16
KEY_L6
KEY_F17
KEY_L7
KEY_F18
KEY_L8
KEY_F19
KEY_L9
KEY_F20
KEY_L10
KEY_F21
KEY_R1
KEY_F22
KEY_R2
KEY_F23
KEY_R3
KEY_F24
KEY_R4
KEY_F25
KEY_R5
KEY_F26
KEY_R6
KEY_F27
KEY_R7
KEY_F28
KEY_R8
KEY_F29
KEY_R9
KEY_F30
KEY_R10
KEY_F31
KEY_R11
KEY_F32
KEY_R12
KEY_F33
KEY_R13
KEY_F34
KEY_R14
KEY_F35
KEY_R15
Modifiers.
KEY_Shift_L
KEY_Shift_R
KEY_Control_L
KEY_Control_R
KEY_Caps_Lock
KEY_Shift_Lock
KEY_Meta_L
KEY_Meta_R
KEY_Alt_L
KEY_Alt_R
KEY_Super_L
KEY_Super_R
KEY_Hyper_L
KEY_Hyper_R
ISO 9995.
KEY_ISO_Lock
KEY_ISO_Level2_Latch
KEY_ISO_Level3_Shift
KEY_ISO_Level3_Latch
KEY_ISO_Level3_Lock
KEY_ISO_Group_Shift
KEY_ISO_Group_Latch
KEY_ISO_Group_Lock
KEY_ISO_Next_Group
KEY_ISO_Next_Group_Lock
KEY_ISO_Prev_Group
KEY_ISO_Prev_Group_Lock
KEY_ISO_First_Group
KEY_ISO_First_Group_Lock
KEY_ISO_Last_Group
KEY_ISO_Last_Group_Lock
KEY_ISO_Left_Tab
KEY_ISO_Move_Line_Up
KEY_ISO_Move_Line_Down
KEY_ISO_Partial_Line_Up
KEY_ISO_Partial_Line_Down
KEY_ISO_Partial_Space_Left
KEY_ISO_Partial_Space_Right
KEY_ISO_Set_Margin_Left
KEY_ISO_Set_Margin_Right
KEY_ISO_Release_Margin_Left
KEY_ISO_Release_Margin_Right
KEY_ISO_Release_Both_Margins
KEY_ISO_Fast_Cursor_Left
KEY_ISO_Fast_Cursor_Right
KEY_ISO_Fast_Cursor_Up
KEY_ISO_Fast_Cursor_Down
KEY_ISO_Continuous_Underline
KEY_ISO_Discontinuous_Underline
KEY_ISO_Emphasize
KEY_ISO_Center_Object
KEY_ISO_Enter
KEY_dead_grave
KEY_dead_acute
KEY_dead_circumflex
KEY_dead_tilde
KEY_dead_macron
KEY_dead_breve
KEY_dead_abovedot
KEY_dead_diaeresis
KEY_dead_abovering
KEY_dead_doubleacute
KEY_dead_caron
KEY_dead_cedilla
KEY_dead_ogonek
KEY_dead_iota
KEY_dead_voiced_sound
KEY_dead_semivoiced_sound
KEY_dead_belowdot
KEY_First_Virtual_Screen
KEY_Prev_Virtual_Screen
KEY_Next_Virtual_Screen
KEY_Last_Virtual_Screen
KEY_Terminate_Server
KEY_AccessX_Enable
KEY_AccessX_Feedback_Enable
KEY_RepeatKeys_Enable
KEY_SlowKeys_Enable
KEY_BounceKeys_Enable
KEY_StickyKeys_Enable
KEY_MouseKeys_Enable
KEY_MouseKeys_Accel_Enable
KEY_Overlay1_Enable
KEY_Overlay2_Enable
KEY_AudibleBell_Enable
KEY_Pointer_Left
KEY_Pointer_Right
KEY_Pointer_Up
KEY_Pointer_Down
KEY_Pointer_UpLeft
KEY_Pointer_UpRight
KEY_Pointer_DownLeft
KEY_Pointer_DownRight
KEY_Pointer_Button_Dflt
KEY_Pointer_Button1
KEY_Pointer_Button2
KEY_Pointer_Button3
KEY_Pointer_Button4
KEY_Pointer_Button5
KEY_Pointer_DblClick_Dflt
KEY_Pointer_DblClick1
KEY_Pointer_DblClick2
KEY_Pointer_DblClick3
KEY_Pointer_DblClick4
KEY_Pointer_DblClick5
KEY_Pointer_Drag_Dflt
KEY_Pointer_Drag1
KEY_Pointer_Drag2
KEY_Pointer_Drag3
KEY_Pointer_Drag4
KEY_Pointer_Drag5
KEY_Pointer_EnableKeys
KEY_Pointer_Accelerate
KEY_Pointer_DfltBtnNext
KEY_Pointer_DfltBtnPrev
3270 Terminal
KEY_3270_Duplicate
KEY_3270_FieldMark
KEY_3270_Right2
KEY_3270_Left2
KEY_3270_BackTab
KEY_3270_EraseEOF
KEY_3270_EraseInput
KEY_3270_Reset
KEY_3270_Quit
KEY_3270_PA1
KEY_3270_PA2
KEY_3270_PA3
KEY_3270_Test
KEY_3270_Attn
KEY_3270_CursorBlink
KEY_3270_AltCursor
KEY_3270_KeyClick
KEY_3270_Jump
KEY_3270_Ident
KEY_3270_Rule
KEY_3270_Copy
KEY_3270_Play
KEY_3270_Setup
KEY_3270_Record
KEY_3270_ChangeScreen
KEY_3270_DeleteWord
KEY_3270_ExSelect
KEY_3270_CursorSelect
KEY_3270_PrintScreen
KEY_3270_Enter
Latin 1.
KEY_space
KEY_exclam
KEY_quotedbl
KEY_numbersign
KEY_dollar
KEY_percent
KEY_ampersand
KEY_apostrophe
KEY_quoteright
KEY_parenleft
KEY_parenright
KEY_asterisk
KEY_plus
KEY_comma
KEY_minus
KEY_period
KEY_slash
KEY_0
KEY_1
KEY_2
KEY_3
KEY_4
KEY_5
KEY_6
KEY_7
KEY_8
KEY_9
KEY_colon
KEY_semicolon
KEY_less
KEY_equal
KEY_greater
KEY_question
KEY_at
KEY_A
KEY_B
KEY_C
KEY_D
KEY_E
KEY_F
KEY_G
KEY_H
KEY_I
KEY_J
KEY_K
KEY_L
KEY_M
KEY_N
KEY_O
KEY_P
KEY_Q
KEY_R
KEY_S
KEY_T
KEY_U
KEY_V
KEY_W
KEY_X
KEY_Y
KEY_Z
KEY_bracketleft
KEY_backslash
KEY_bracketright
KEY_asciicircum
KEY_underscore
KEY_grave
KEY_quoteleft
KEY_a
KEY_b
KEY_c
KEY_d
KEY_e
KEY_f
KEY_g
KEY_h
KEY_i
KEY_j
KEY_k
KEY_l
KEY_m
KEY_n
KEY_o
KEY_p
KEY_q
KEY_r
KEY_s
KEY_t
KEY_u
KEY_v
KEY_w
KEY_x
KEY_y
KEY_z
KEY_braceleft
KEY_bar
KEY_braceright
KEY_asciitilde
KEY_nobreakspace
KEY_exclamdown
KEY_cent
KEY_sterling
KEY_currency
KEY_yen
KEY_brokenbar
KEY_section
KEY_diaeresis
KEY_copyright
KEY_ordfeminine
KEY_guillemotleft
KEY_notsign
KEY_hyphen
KEY_registered
KEY_macron
KEY_degree
KEY_plusminus
KEY_twosuperior
KEY_threesuperior
KEY_acute
KEY_mu
KEY_paragraph
KEY_periodcentered
KEY_cedilla
KEY_onesuperior
KEY_masculine
KEY_guillemotright
KEY_onequarter
KEY_onehalf
KEY_threequarters
KEY_questiondown
KEY_Agrave
KEY_Aacute
KEY_Acircumflex
KEY_Atilde
KEY_Adiaeresis
KEY_Aring
KEY_AE
KEY_Ccedilla
KEY_Egrave
KEY_Eacute
KEY_Ecircumflex
KEY_Ediaeresis
KEY_Igrave
KEY_Iacute
KEY_Icircumflex
KEY_Idiaeresis
KEY_ETH
KEY_Eth
KEY_Ntilde
KEY_Ograve
KEY_Oacute
KEY_Ocircumflex
KEY_Otilde
KEY_Odiaeresis
KEY_multiply
KEY_Ooblique
KEY_Ugrave
KEY_Uacute
KEY_Ucircumflex
KEY_Udiaeresis
KEY_Yacute
KEY_THORN
KEY_Thorn
KEY_ssharp
KEY_agrave
KEY_aacute
KEY_acircumflex
KEY_atilde
KEY_adiaeresis
KEY_aring
KEY_ae
KEY_ccedilla
KEY_egrave
KEY_eacute
KEY_ecircumflex
KEY_ediaeresis
KEY_igrave
KEY_iacute
KEY_icircumflex
KEY_idiaeresis
KEY_eth
KEY_ntilde
KEY_ograve
KEY_oacute
KEY_ocircumflex
KEY_otilde
KEY_odiaeresis
KEY_division
KEY_oslash
KEY_ugrave
KEY_uacute
KEY_ucircumflex
KEY_udiaeresis
KEY_yacute
KEY_thorn
KEY_ydiaeresis
Latin 2.
KEY_Aogonek
KEY_breve
KEY_Lstroke
KEY_Lcaron
KEY_Sacute
KEY_Scaron
KEY_Scedilla
KEY_Tcaron
KEY_Zacute
KEY_Zcaron
KEY_Zabovedot
KEY_aogonek
KEY_ogonek
KEY_lstroke
KEY_lcaron
KEY_sacute
KEY_caron
KEY_scaron
KEY_scedilla
KEY_tcaron
KEY_zacute
KEY_doubleacute
KEY_zcaron
KEY_zabovedot
KEY_Racute
KEY_Abreve
KEY_Lacute
KEY_Cacute
KEY_Ccaron
KEY_Eogonek
KEY_Ecaron
KEY_Dcaron
KEY_Dstroke
KEY_Nacute
KEY_Ncaron
KEY_Odoubleacute
KEY_Rcaron
KEY_Uring
KEY_Udoubleacute
KEY_Tcedilla
KEY_racute
KEY_abreve
KEY_lacute
KEY_cacute
KEY_ccaron
KEY_eogonek
KEY_ecaron
KEY_dcaron
KEY_dstroke
KEY_nacute
KEY_ncaron
KEY_odoubleacute
KEY_udoubleacute
KEY_rcaron
KEY_uring
KEY_tcedilla
KEY_abovedot
Latin 3.
KEY_Hstroke
KEY_Hcircumflex
KEY_Iabovedot
KEY_Gbreve
KEY_Jcircumflex
KEY_hstroke
KEY_hcircumflex
KEY_idotless
KEY_gbreve
KEY_jcircumflex
KEY_Cabovedot
KEY_Ccircumflex
KEY_Gabovedot
KEY_Gcircumflex
KEY_Ubreve
KEY_Scircumflex
KEY_cabovedot
KEY_ccircumflex
KEY_gabovedot
KEY_gcircumflex
KEY_ubreve
KEY_scircumflex
Latin 4.
KEY_kra
KEY_kappa
KEY_Rcedilla
KEY_Itilde
KEY_Lcedilla
KEY_Emacron
KEY_Gcedilla
KEY_Tslash
KEY_rcedilla
KEY_itilde
KEY_lcedilla
KEY_emacron
KEY_gcedilla
KEY_tslash
KEY_ENG
KEY_eng
KEY_Amacron
KEY_Iogonek
KEY_Eabovedot
KEY_Imacron
KEY_Ncedilla
KEY_Omacron
KEY_Kcedilla
KEY_Uogonek
KEY_Utilde
KEY_Umacron
KEY_amacron
KEY_iogonek
KEY_eabovedot
KEY_imacron
KEY_ncedilla
KEY_omacron
KEY_kcedilla
KEY_uogonek
KEY_utilde
KEY_umacron
Katakana.
KEY_overline
KEY_kana_fullstop
KEY_kana_openingbracket
KEY_kana_closingbracket
KEY_kana_comma
KEY_kana_conjunctive
KEY_kana_middledot
KEY_kana_WO
KEY_kana_a
KEY_kana_i
KEY_kana_u
KEY_kana_e
KEY_kana_o
KEY_kana_ya
KEY_kana_yu
KEY_kana_yo
KEY_kana_tsu
KEY_kana_tu
KEY_prolongedsound
KEY_kana_A
KEY_kana_I
KEY_kana_U
KEY_kana_E
KEY_kana_O
KEY_kana_KA
KEY_kana_KI
KEY_kana_KU
KEY_kana_KE
KEY_kana_KO
KEY_kana_SA
KEY_kana_SHI
KEY_kana_SU
KEY_kana_SE
KEY_kana_SO
KEY_kana_TA
KEY_kana_CHI
KEY_kana_TI
KEY_kana_TSU
KEY_kana_TU
KEY_kana_TE
KEY_kana_TO
KEY_kana_NA
KEY_kana_NI
KEY_kana_NU
KEY_kana_NE
KEY_kana_NO
KEY_kana_HA
KEY_kana_HI
KEY_kana_FU
KEY_kana_HU
KEY_kana_HE
KEY_kana_HO
KEY_kana_MA
KEY_kana_MI
KEY_kana_MU
KEY_kana_ME
KEY_kana_MO
KEY_kana_YA
KEY_kana_YU
KEY_kana_YO
KEY_kana_RA
KEY_kana_RI
KEY_kana_RU
KEY_kana_RE
KEY_kana_RO
KEY_kana_WA
KEY_kana_N
KEY_voicedsound
KEY_semivoicedsound
KEY_kana_switch
Arabic.
KEY_Arabic_comma
KEY_Arabic_semicolon
KEY_Arabic_question_mark
KEY_Arabic_hamza
KEY_Arabic_maddaonalef
KEY_Arabic_hamzaonalef
KEY_Arabic_hamzaonwaw
KEY_Arabic_hamzaunderalef
KEY_Arabic_hamzaonyeh
KEY_Arabic_alef
KEY_Arabic_beh
KEY_Arabic_tehmarbuta
KEY_Arabic_teh
KEY_Arabic_theh
KEY_Arabic_jeem
KEY_Arabic_hah
KEY_Arabic_khah
KEY_Arabic_dal
KEY_Arabic_thal
KEY_Arabic_ra
KEY_Arabic_zain
KEY_Arabic_seen
KEY_Arabic_sheen
KEY_Arabic_sad
KEY_Arabic_dad
KEY_Arabic_tah
KEY_Arabic_zah
KEY_Arabic_ain
KEY_Arabic_ghain
KEY_Arabic_tatweel
KEY_Arabic_feh
KEY_Arabic_qaf
KEY_Arabic_kaf
KEY_Arabic_lam
KEY_Arabic_meem
KEY_Arabic_noon
KEY_Arabic_ha
KEY_Arabic_heh
KEY_Arabic_waw
KEY_Arabic_alefmaksura
KEY_Arabic_yeh
KEY_Arabic_fathatan
KEY_Arabic_dammatan
KEY_Arabic_kasratan
KEY_Arabic_fatha
KEY_Arabic_damma
KEY_Arabic_kasra
KEY_Arabic_shadda
KEY_Arabic_sukun
KEY_Arabic_switch
Cyrillic.
KEY_Serbian_dje
KEY_Macedonia_gje
KEY_Cyrillic_io
KEY_Ukrainian_ie
KEY_Ukranian_je
KEY_Macedonia_dse
KEY_Ukrainian_i
KEY_Ukranian_i
KEY_Ukrainian_yi
KEY_Ukranian_yi
KEY_Cyrillic_je
KEY_Serbian_je
KEY_Cyrillic_lje
KEY_Serbian_lje
KEY_Cyrillic_nje
KEY_Serbian_nje
KEY_Serbian_tshe
KEY_Macedonia_kje
KEY_Byelorussian_shortu
KEY_Cyrillic_dzhe
KEY_Serbian_dze
KEY_numerosign
KEY_Serbian_DJE
KEY_Macedonia_GJE
KEY_Cyrillic_IO
KEY_Ukrainian_IE
KEY_Ukranian_JE
KEY_Macedonia_DSE
KEY_Ukrainian_I
KEY_Ukranian_I
KEY_Ukrainian_YI
KEY_Ukranian_YI
KEY_Cyrillic_JE
KEY_Serbian_JE
KEY_Cyrillic_LJE
KEY_Serbian_LJE
KEY_Cyrillic_NJE
KEY_Serbian_NJE
KEY_Serbian_TSHE
KEY_Macedonia_KJE
KEY_Byelorussian_SHORTU
KEY_Cyrillic_DZHE
KEY_Serbian_DZE
KEY_Cyrillic_yu
KEY_Cyrillic_a
KEY_Cyrillic_be
KEY_Cyrillic_tse
KEY_Cyrillic_de
KEY_Cyrillic_ie
KEY_Cyrillic_ef
KEY_Cyrillic_ghe
KEY_Cyrillic_ha
KEY_Cyrillic_i
KEY_Cyrillic_shorti
KEY_Cyrillic_ka
KEY_Cyrillic_el
KEY_Cyrillic_em
KEY_Cyrillic_en
KEY_Cyrillic_o
KEY_Cyrillic_pe
KEY_Cyrillic_ya
KEY_Cyrillic_er
KEY_Cyrillic_es
KEY_Cyrillic_te
KEY_Cyrillic_u
KEY_Cyrillic_zhe
KEY_Cyrillic_ve
KEY_Cyrillic_softsign
KEY_Cyrillic_yeru
KEY_Cyrillic_ze
KEY_Cyrillic_sha
KEY_Cyrillic_e
KEY_Cyrillic_shcha
KEY_Cyrillic_che
KEY_Cyrillic_hardsign
KEY_Cyrillic_YU
KEY_Cyrillic_A
KEY_Cyrillic_BE
KEY_Cyrillic_TSE
KEY_Cyrillic_DE
KEY_Cyrillic_IE
KEY_Cyrillic_EF
KEY_Cyrillic_GHE
KEY_Cyrillic_HA
KEY_Cyrillic_I
KEY_Cyrillic_SHORTI
KEY_Cyrillic_KA
KEY_Cyrillic_EL
KEY_Cyrillic_EM
KEY_Cyrillic_EN
KEY_Cyrillic_O
KEY_Cyrillic_PE
KEY_Cyrillic_YA
KEY_Cyrillic_ER
KEY_Cyrillic_ES
KEY_Cyrillic_TE
KEY_Cyrillic_U
KEY_Cyrillic_ZHE
KEY_Cyrillic_VE
KEY_Cyrillic_SOFTSIGN
KEY_Cyrillic_YERU
KEY_Cyrillic_ZE
KEY_Cyrillic_SHA
KEY_Cyrillic_E
KEY_Cyrillic_SHCHA
KEY_Cyrillic_CHE
KEY_Cyrillic_HARDSIGN
Greek.
KEY_Greek_ALPHAaccent
KEY_Greek_EPSILONaccent
KEY_Greek_ETAaccent
KEY_Greek_IOTAaccent
KEY_Greek_IOTAdiaeresis
KEY_Greek_OMICRONaccent
KEY_Greek_UPSILONaccent
KEY_Greek_UPSILONdieresis
KEY_Greek_OMEGAaccent
KEY_Greek_accentdieresis
KEY_Greek_horizbar
KEY_Greek_alphaaccent
KEY_Greek_epsilonaccent
KEY_Greek_etaaccent
KEY_Greek_iotaaccent
KEY_Greek_iotadieresis
KEY_Greek_iotaaccentdieresis
KEY_Greek_omicronaccent
KEY_Greek_upsilonaccent
KEY_Greek_upsilondieresis
KEY_Greek_upsilonaccentdieresis
KEY_Greek_omegaaccent
KEY_Greek_ALPHA
KEY_Greek_BETA
KEY_Greek_GAMMA
KEY_Greek_DELTA
KEY_Greek_EPSILON
KEY_Greek_ZETA
KEY_Greek_ETA
KEY_Greek_THETA
KEY_Greek_IOTA
KEY_Greek_KAPPA
KEY_Greek_LAMDA
KEY_Greek_LAMBDA
KEY_Greek_MU
KEY_Greek_NU
KEY_Greek_XI
KEY_Greek_OMICRON
KEY_Greek_PI
KEY_Greek_RHO
KEY_Greek_SIGMA
KEY_Greek_TAU
KEY_Greek_UPSILON
KEY_Greek_PHI
KEY_Greek_CHI
KEY_Greek_PSI
KEY_Greek_OMEGA
KEY_Greek_alpha
KEY_Greek_beta
KEY_Greek_gamma
KEY_Greek_delta
KEY_Greek_epsilon
KEY_Greek_zeta
KEY_Greek_eta
KEY_Greek_theta
KEY_Greek_iota
KEY_Greek_kappa
KEY_Greek_lamda
KEY_Greek_lambda
KEY_Greek_mu
KEY_Greek_nu
KEY_Greek_xi
KEY_Greek_omicron
KEY_Greek_pi
KEY_Greek_rho
KEY_Greek_sigma
KEY_Greek_finalsmallsigma
KEY_Greek_tau
KEY_Greek_upsilon
KEY_Greek_phi
KEY_Greek_chi
KEY_Greek_psi
KEY_Greek_omega
KEY_Greek_switch
Technical.
KEY_leftradical
KEY_topleftradical
KEY_horizconnector
KEY_topintegral
KEY_botintegral
KEY_vertconnector
KEY_topleftsqbracket
KEY_botleftsqbracket
KEY_toprightsqbracket
KEY_botrightsqbracket
KEY_topleftparens
KEY_botleftparens
KEY_toprightparens
KEY_botrightparens
KEY_leftmiddlecurlybrace
KEY_rightmiddlecurlybrace
KEY_topleftsummation
KEY_botleftsummation
KEY_topvertsummationconnector
KEY_botvertsummationconnector
KEY_toprightsummation
KEY_botrightsummation
KEY_rightmiddlesummation
KEY_lessthanequal
KEY_notequal
KEY_greaterthanequal
KEY_integral
KEY_therefore
KEY_variation
KEY_infinity
KEY_nabla
KEY_approximate
KEY_similarequal
KEY_ifonlyif
KEY_implies
KEY_identical
KEY_radical
KEY_includedin
KEY_includes
KEY_intersection
KEY_union
KEY_logicaland
KEY_logicalor
KEY_partialderivative
KEY_function
KEY_leftarrow
KEY_uparrow
KEY_rightarrow
KEY_downarrow
Special.
KEY_blank
KEY_soliddiamond
KEY_checkerboard
KEY_ht
KEY_ff
KEY_cr
KEY_lf
KEY_nl
KEY_vt
KEY_lowrightcorner
KEY_uprightcorner
KEY_upleftcorner
KEY_lowleftcorner
KEY_crossinglines
KEY_horizlinescan1
KEY_horizlinescan3
KEY_horizlinescan5
KEY_horizlinescan7
KEY_horizlinescan9
KEY_leftt
KEY_rightt
KEY_bott
KEY_topt
KEY_vertbar
Publishing.
KEY_emspace
KEY_enspace
KEY_em3space
KEY_em4space
KEY_digitspace
KEY_punctspace
KEY_thinspace
KEY_hairspace
KEY_emdash
KEY_endash
KEY_signifblank
KEY_ellipsis
KEY_doubbaselinedot
KEY_onethird
KEY_twothirds
KEY_onefifth
KEY_twofifths
KEY_threefifths
KEY_fourfifths
KEY_onesixth
KEY_fivesixths
KEY_careof
KEY_figdash
KEY_leftanglebracket
KEY_decimalpoint
KEY_rightanglebracket
KEY_marker
KEY_oneeighth
KEY_threeeighths
KEY_fiveeighths
KEY_seveneighths
KEY_trademark
KEY_signaturemark
KEY_trademarkincircle
KEY_leftopentriangle
KEY_rightopentriangle
KEY_emopencircle
KEY_emopenrectangle
KEY_leftsinglequotemark
KEY_rightsinglequotemark
KEY_leftdoublequotemark
KEY_rightdoublequotemark
KEY_prescription
KEY_minutes
KEY_seconds
KEY_latincross
KEY_hexagram
KEY_filledrectbullet
KEY_filledlefttribullet
KEY_filledrighttribullet
KEY_emfilledcircle
KEY_emfilledrect
KEY_enopencircbullet
KEY_enopensquarebullet
KEY_openrectbullet
KEY_opentribulletup
KEY_opentribulletdown
KEY_openstar
KEY_enfilledcircbullet
KEY_enfilledsqbullet
KEY_filledtribulletup
KEY_filledtribulletdown
KEY_leftpointer
KEY_rightpointer
KEY_club
KEY_diamond
KEY_heart
KEY_maltesecross
KEY_dagger
KEY_doubledagger
KEY_checkmark
KEY_ballotcross
KEY_musicalsharp
KEY_musicalflat
KEY_malesymbol
KEY_femalesymbol
KEY_telephone
KEY_telephonerecorder
KEY_phonographcopyright
KEY_caret
KEY_singlelowquotemark
KEY_doublelowquotemark
KEY_cursor
APL.
KEY_leftcaret
KEY_rightcaret
KEY_downcaret
KEY_upcaret
KEY_overbar
KEY_downtack
KEY_upshoe
KEY_downstile
KEY_underbar
KEY_jot
KEY_quad
KEY_uptack
KEY_circle
KEY_upstile
KEY_downshoe
KEY_rightshoe
KEY_leftshoe
KEY_lefttack
KEY_righttack
Hebrew.
KEY_hebrew_doublelowline
KEY_hebrew_aleph
KEY_hebrew_bet
KEY_hebrew_beth
KEY_hebrew_gimel
KEY_hebrew_gimmel
KEY_hebrew_dalet
KEY_hebrew_daleth
KEY_hebrew_he
KEY_hebrew_waw
KEY_hebrew_zain
KEY_hebrew_zayin
KEY_hebrew_chet
KEY_hebrew_het
KEY_hebrew_tet
KEY_hebrew_teth
KEY_hebrew_yod
KEY_hebrew_finalkaph
KEY_hebrew_kaph
KEY_hebrew_lamed
KEY_hebrew_finalmem
KEY_hebrew_mem
KEY_hebrew_finalnun
KEY_hebrew_nun
KEY_hebrew_samech
KEY_hebrew_samekh
KEY_hebrew_ayin
KEY_hebrew_finalpe
KEY_hebrew_pe
KEY_hebrew_finalzade
KEY_hebrew_finalzadi
KEY_hebrew_zade
KEY_hebrew_zadi
KEY_hebrew_qoph
KEY_hebrew_kuf
KEY_hebrew_resh
KEY_hebrew_shin
KEY_hebrew_taw
KEY_hebrew_taf
KEY_Hebrew_switch
Thai.
KEY_Thai_kokai
KEY_Thai_khokhai
KEY_Thai_khokhuat
KEY_Thai_khokhwai
KEY_Thai_khokhon
KEY_Thai_khorakhang
KEY_Thai_ngongu
KEY_Thai_chochan
KEY_Thai_choching
KEY_Thai_chochang
KEY_Thai_soso
KEY_Thai_chochoe
KEY_Thai_yoying
KEY_Thai_dochada
KEY_Thai_topatak
KEY_Thai_thothan
KEY_Thai_thonangmontho
KEY_Thai_thophuthao
KEY_Thai_nonen
KEY_Thai_dodek
KEY_Thai_totao
KEY_Thai_thothung
KEY_Thai_thothahan
KEY_Thai_thothong
KEY_Thai_nonu
KEY_Thai_bobaimai
KEY_Thai_popla
KEY_Thai_phophung
KEY_Thai_fofa
KEY_Thai_phophan
KEY_Thai_fofan
KEY_Thai_phosamphao
KEY_Thai_moma
KEY_Thai_yoyak
KEY_Thai_rorua
KEY_Thai_ru
KEY_Thai_loling
KEY_Thai_lu
KEY_Thai_wowaen
KEY_Thai_sosala
KEY_Thai_sorusi
KEY_Thai_sosua
KEY_Thai_hohip
KEY_Thai_lochula
KEY_Thai_oang
KEY_Thai_honokhuk
KEY_Thai_paiyannoi
KEY_Thai_saraa
KEY_Thai_maihanakat
KEY_Thai_saraaa
KEY_Thai_saraam
KEY_Thai_sarai
KEY_Thai_saraii
KEY_Thai_saraue
KEY_Thai_sarauee
KEY_Thai_sarau
KEY_Thai_sarauu
KEY_Thai_phinthu
KEY_Thai_maihanakat_maitho
KEY_Thai_baht
KEY_Thai_sarae
KEY_Thai_saraae
KEY_Thai_sarao
KEY_Thai_saraaimaimuan
KEY_Thai_saraaimaimalai
KEY_Thai_lakkhangyao
KEY_Thai_maiyamok
KEY_Thai_maitaikhu
KEY_Thai_maiek
KEY_Thai_maitho
KEY_Thai_maitri
KEY_Thai_maichattawa
KEY_Thai_thanthakhat
KEY_Thai_nikhahit
KEY_Thai_leksun
KEY_Thai_leknung
KEY_Thai_leksong
KEY_Thai_leksam
KEY_Thai_leksi
KEY_Thai_lekha
KEY_Thai_lekhok
KEY_Thai_lekchet
KEY_Thai_lekpaet
KEY_Thai_lekkao
Korean.
KEY_Hangul
KEY_Hangul_Start
KEY_Hangul_End
KEY_Hangul_Hanja
KEY_Hangul_Jamo
KEY_Hangul_Romaja
KEY_Hangul_Codeinput
KEY_Hangul_Jeonja
KEY_Hangul_Banja
KEY_Hangul_PreHanja
KEY_Hangul_PostHanja
KEY_Hangul_SingleCandidate
KEY_Hangul_MultipleCandidate
KEY_Hangul_PreviousCandidate
KEY_Hangul_Special
KEY_Hangul_switch
KEY_Hangul_Kiyeog
KEY_Hangul_SsangKiyeog
KEY_Hangul_KiyeogSios
KEY_Hangul_Nieun
KEY_Hangul_NieunJieuj
KEY_Hangul_NieunHieuh
KEY_Hangul_Dikeud
KEY_Hangul_SsangDikeud
KEY_Hangul_Rieul
KEY_Hangul_RieulKiyeog
KEY_Hangul_RieulMieum
KEY_Hangul_RieulPieub
KEY_Hangul_RieulSios
KEY_Hangul_RieulTieut
KEY_Hangul_RieulPhieuf
KEY_Hangul_RieulHieuh
KEY_Hangul_Mieum
KEY_Hangul_Pieub
KEY_Hangul_SsangPieub
KEY_Hangul_PieubSios
KEY_Hangul_Sios
KEY_Hangul_SsangSios
KEY_Hangul_Ieung
KEY_Hangul_Jieuj
KEY_Hangul_SsangJieuj
KEY_Hangul_Cieuc
KEY_Hangul_Khieuq
KEY_Hangul_Tieut
KEY_Hangul_Phieuf
KEY_Hangul_Hieuh
KEY_Hangul_A
KEY_Hangul_AE
KEY_Hangul_YA
KEY_Hangul_YAE
KEY_Hangul_EO
KEY_Hangul_E
KEY_Hangul_YEO
KEY_Hangul_YE
KEY_Hangul_O
KEY_Hangul_WA
KEY_Hangul_WAE
KEY_Hangul_OE
KEY_Hangul_YO
KEY_Hangul_U
KEY_Hangul_WEO
KEY_Hangul_WE
KEY_Hangul_WI
KEY_Hangul_YU
KEY_Hangul_EU
KEY_Hangul_YI
KEY_Hangul_I
KEY_Hangul_J_Kiyeog
KEY_Hangul_J_SsangKiyeog
KEY_Hangul_J_KiyeogSios
KEY_Hangul_J_Nieun
KEY_Hangul_J_NieunJieuj
KEY_Hangul_J_NieunHieuh
KEY_Hangul_J_Dikeud
KEY_Hangul_J_Rieul
KEY_Hangul_J_RieulKiyeog
KEY_Hangul_J_RieulMieum
KEY_Hangul_J_RieulPieub
KEY_Hangul_J_RieulSios
KEY_Hangul_J_RieulTieut
KEY_Hangul_J_RieulPhieuf
KEY_Hangul_J_RieulHieuh
KEY_Hangul_J_Mieum
KEY_Hangul_J_Pieub
KEY_Hangul_J_PieubSios
KEY_Hangul_J_Sios
KEY_Hangul_J_SsangSios
KEY_Hangul_J_Ieung
KEY_Hangul_J_Jieuj
KEY_Hangul_J_Cieuc
KEY_Hangul_J_Khieuq
KEY_Hangul_J_Tieut
KEY_Hangul_J_Phieuf
KEY_Hangul_J_Hieuh
KEY_Hangul_RieulYeorinHieuh
KEY_Hangul_SunkyeongeumMieum
KEY_Hangul_SunkyeongeumPieub
KEY_Hangul_PanSios
KEY_Hangul_KkogjiDalrinIeung
KEY_Hangul_SunkyeongeumPhieuf
KEY_Hangul_YeorinHieuh
KEY_Hangul_AraeA
KEY_Hangul_AraeAE
KEY_Hangul_J_PanSios
KEY_Hangul_J_KkogjiDalrinIeung
KEY_Hangul_J_YeorinHieuh
KEY_Korean_Won
anonymous enum
anonymous enum
Enumerator
PROGRESSDIALOG_NOCANCEL
Default is no cancel button.
PROGRESSDIALOG_CANCEL
Enable the cancel button.
PROGRESSDIALOG_NORMAL
Function Documentation
parseAccel()
FXHotKey FX::parseAccel (const FXString & string)
For example, parseAccel("Ctl+Shift+X") yields MKUINT(KEY_X,CONTROLMASK|SHIFTMASK).
unparseAccel()
FXString FX::unparseAccel (FXHotKey key)
parseHotKey()
FXHotKey FX::parseHotKey (const FXString & string)
For example, parseHotKey(""Salt && &Pepper!"") yields MKUINT(KEY_p,ALTMASK).
findHotKey()
FXint FX::findHotKey (const FXString & string)
For example, findHotKey("Salt && &Pepper!") yields 7. Note that this is the byte-offset, not the character index!
stripHotKey()
FXString FX::stripHotKey (const FXString & string)
For example, stripHotKey("Salt && &Pepper") should yield "Salt & Pepper".
fxcheckBMP()
bool FX::fxcheckBMP (FXStream & store)
Check if stream contains a bitmap, return TRUE if so.
fxloadBMP()
bool FX::fxloadBMP (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an BMP (Microsoft Bitmap) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveBMP()
bool FX::fxsaveBMP (FXStream & store, const FXColor * data, FXint width, FXint height)
Save an BMP (Microsoft Bitmap) file to a stream.
fxcheckICO()
bool FX::fxcheckICO (FXStream & store)
Check if stream contains a ICO, return TRUE if so.
fxloadICO()
bool FX::fxloadICO (FXStream & store, FXColor *& data, FXint & width, FXint & height, FXint & xspot, FXint & yspot)
Load an ICO (Microsoft icon format) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveICO()
bool FX::fxsaveICO (FXStream & store, const FXColor * data, FXint width, FXint height, FXint xspot = -1, FXint yspot = -1)
Save an ICO (Microsoft icon format) file to a stream.
If no hot-spot given, save as an ICO instead of a CUR resource.
operator+() [1/11]
FXDate FX::operator+ (const FXDate & d, FXint x) inline
operator+() [2/11]
FXDate FX::operator+ (FXint x, const FXDate & d) inline
operator-()
FXint FX::operator- (const FXDate & a, const FXDate & b) inline
operator<<() [1/22]
FXStream& FX::operator<< (FXStream & store, const FXDate & d)
operator>>() [1/22]
FXStream& FX::operator>> (FXStream & store, FXDate & d)
fxrandom()
FXuint FX::fxrandom (FXuint & seed)
Simple, thread-safe, random number generator.
fxmalloc()
FXint FX::fxmalloc (void ** ptr, unsigned long size)
Allocate memory.
Referenced by allocElms().
fxcalloc()
FXint FX::fxcalloc (void ** ptr, unsigned long size)
Allocate cleaned memory.
Referenced by callocElms().
fxresize()
FXint FX::fxresize (void ** ptr, unsigned long size)
Resize memory.
Referenced by resizeElms().
fxmemdup()
FXint FX::fxmemdup (void ** ptr, const void * src, unsigned long size)
Duplicate memory.
Referenced by dupElms().
fxfree()
void FX::fxfree (void ** ptr)
Free memory, resets ptr to NULL afterward.
Referenced by freeElms().
fxerror()
void FX::fxerror (const char * format, ...)
Error routine.
fxwarning()
void void FX::fxwarning (const char * format, ...)
Warning routine.
fxmessage()
void void void FX::fxmessage (const char * format, ...)
Log message to [typically] stderr.
fxassert()
void void void void FX::fxassert (const char * expression, const char * filename, unsigned int lineno)
Assert failed routine:- usually not called directly but called through FXASSERT.
fxtrace()
void FX::fxtrace (unsigned int level, const char * format, ...)
Trace printout routine:- usually not called directly but called through FXTRACE.
fxsleep()
void void FX::fxsleep (unsigned int n)
Sleep n microseconds.
fxfilematch()
bool FX::fxfilematch (const char * pattern, const char * string, FXuint flags = (FILEMATCH_NOESCAPE|FILEMATCH_FILE_NAME))
Match a file name with a pattern.
makeHiliteColor()
FXColor FX::makeHiliteColor (FXColor clr)
Get highlight color.
makeShadowColor()
FXColor FX::makeShadowColor (FXColor clr)
Get shadow color.
fxgetpid()
FXint FX::fxgetpid ()
Get process id.
fxtoDOS()
bool FX::fxtoDOS (FXchar *& string, FXint & len)
Convert string of length len to MSDOS; return new string and new length.
fxfromDOS()
bool FX::fxfromDOS (FXchar *& string, FXint & len)
Convert string of length len from MSDOS; return new string and new length.
fxstrdup()
FXchar* FX::fxstrdup (const FXchar * str)
Duplicate string.
fxstrhash()
FXuint FX::fxstrhash (const FXchar * str)
Calculate a hash value from a string.
fxcolorfromname()
FXColor FX::fxcolorfromname (const FXchar * colorname)
Get RGB value from color name.
fxnamefromcolor()
FXchar* FX::fxnamefromcolor (FXchar * colorname, FXColor color)
Get name of (closest) color to RGB.
fxrgb_to_hsv()
void FX::fxrgb_to_hsv (FXfloat & h, FXfloat & s, FXfloat & v, FXfloat r, FXfloat g, FXfloat b)
Convert RGB to HSV.
fxhsv_to_rgb()
void FX::fxhsv_to_rgb (FXfloat & r, FXfloat & g, FXfloat & b, FXfloat h, FXfloat s, FXfloat v)
Convert HSV to RGB.
fxieeefloatclass()
FXint FX::fxieeefloatclass (FXfloat number)
Floating point number classification: 0=OK, +/-1=Inf, +/-2=NaN.
fxieeedoubleclass()
FXint FX::fxieeedoubleclass (FXdouble number)
fxkeysym2ucs()
FXwchar FX::fxkeysym2ucs (FXwchar sym)
Convert keysym to unicode character.
fxucs2keysym()
FXwchar FX::fxucs2keysym (FXwchar ucs)
Convert unicode character to keysym.
fxparsegeometry()
FXint FX::fxparsegeometry (const FXchar * string, FXint & x, FXint & y, FXint & w, FXint & h)
Parse geometry, a-la X11 geometry specification.
fxisconsole()
FXbool FX::fxisconsole (const FXchar * path)
True if executable with given path is a console application.
wc() [1/2]
FXwchar FX::wc (const FXchar * ptr)
Return wide character from utf8 string at ptr.
wc() [2/2]
FXwchar FX::wc (const FXnchar * ptr)
Return wide character from utf16 string at ptr.
wclen() [1/2]
FXint FX::wclen (const FXchar * ptr)
Return number of FXchar's of wide character at ptr.
wclen() [2/2]
FXint FX::wclen (const FXnchar * ptr)
Return number of FXnchar's of narrow character at ptr.
wcvalidate() [1/2]
FXint FX::wcvalidate (const FXchar * string, FXint pos)
Return start of utf8 character containing position.
wcvalidate() [2/2]
FXint FX::wcvalidate (const FXnchar * string, FXint pos)
Return start of utf16 character containing position.
wcinc() [1/2]
FXint FX::wcinc (const FXchar * string, FXint pos)
Advance to next utf8 character start.
wcinc() [2/2]
FXint FX::wcinc (const FXnchar * string, FXint pos)
Advance to next utf16 character start.
wcdec() [1/2]
FXint FX::wcdec (const FXchar * string, FXint pos)
Retreat to previous utf8 character start.
wcdec() [2/2]
FXint FX::wcdec (const FXnchar * string, FXint pos)
Retreat to previous utf16 character start.
utfslen() [1/4]
FXint FX::utfslen (const FXwchar * str, FXint n)
Length of utf8 representation of wide characters string str of length n.
utfslen() [2/4]
FXint FX::utfslen (const FXwchar * str)
Length of utf8 representation of wide character string str.
utfslen() [3/4]
FXint FX::utfslen (const FXnchar * str, FXint n)
Length of utf8 representation of narrow characters string str of length n.
utfslen() [4/4]
FXint FX::utfslen (const FXnchar * str)
Length of utf8 representation of narrow characters string str.
wcslen() [1/2]
FXint FX::wcslen (const FXchar * str, FXint n)
Length of wide character representation of utf8 string str of length n.
wcslen() [2/2]
FXint FX::wcslen (const FXchar * str)
Length of wide character representation of utf8 string str.
ncslen() [1/2]
FXint FX::ncslen (const FXchar * str, FXint n)
Length of narrow character representation of utf8 string str of length n.
ncslen() [2/2]
FXint FX::ncslen (const FXchar * str)
Length of narrow character representation of utf8 string str.
utf2wcs() [1/2]
FXint FX::utf2wcs (FXwchar * dst, const FXchar * src, FXint n)
Copy utf8 string of length n to wide character string dst.
utf2wcs() [2/2]
FXint FX::utf2wcs (FXwchar * dst, const FXchar * src)
Copy utf8 string to wide character string dst.
utf2ncs() [1/2]
FXint FX::utf2ncs (FXnchar * dst, const FXchar * src, FXint n)
Copy utf8 string of length n to narrow character string dst.
utf2ncs() [2/2]
FXint FX::utf2ncs (FXnchar * dst, const FXchar * src)
Copy utf8 string to narrow character string dst.
wc2utfs() [1/2]
FXint FX::wc2utfs (FXchar * dst, const FXwchar * src, FXint n)
Copy wide character substring of length n to dst.
wc2utfs() [2/2]
FXint FX::wc2utfs (FXchar * dst, const FXwchar * src)
Copy wide character string to dst.
nc2utfs() [1/2]
FXint FX::nc2utfs (FXchar * dst, const FXnchar * src, FXint n)
Copy narrow character substring of length n to dst.
nc2utfs() [2/2]
FXint FX::nc2utfs (FXchar * dst, const FXnchar * src)
Copy narrow character string to dst.
fxdllOpen()
void* FX::fxdllOpen (const FXchar * dllname)
Open library with given name, returning handle to the library, or NULL if the operation failed.
fxdllClose()
void FX::fxdllClose (void * dllhandle)
Close library represented by dllhandle.
fxdllSymbol()
void* FX::fxdllSymbol (void * dllhandle, const FXchar * dllsymbol)
Return address of the symbol in the library represented by dllhandle, or NULL if the operation failed.
fxdllError()
FXString FX::fxdllError ()
Return the string error message when loading dll's.
constructElms() [1/9]
template<class TYPE > void FX::constructElms (TYPE * ptr, unsigned long n) inline
Construct some elements at a location.
Referenced by FX::FXArray< TYPE >::FXArray(), and FX::FXArray< TYPE >::no().
destructElms() [1/9]
template<class TYPE > void FX::destructElms (TYPE * ptr, unsigned long n) inline
Destruct some elements at a location.
Referenced by FX::FXArray< TYPE >::clear(), FX::FXArray< TYPE >::no(), and FX::FXArray< TYPE >::~FXArray().
copyElms() [1/10]
template<class TYPE > void FX::copyElms (TYPE * dst, const TYPE * src, unsigned long n) inline
Copy some elements from one place to another.
Referenced by FX::FXArray< TYPE >::append(), FX::FXArray< TYPE >::assign(), FX::FXArray< TYPE >::FXArray(), FX::FXArray< TYPE >::insert(), FX::FXArray< TYPE >::operator=(), and FX::FXArray< TYPE >::prepend().
moveElms() [1/10]
template<class TYPE > void FX::moveElms (TYPE * dst, const TYPE * src, unsigned long n) inline
Move some elements from overlapping place to another.
Referenced by FX::FXArray< TYPE >::erase(), FX::FXArray< TYPE >::insert(), and FX::FXArray< TYPE >::prepend().
fillElms() [1/3]
template<class TYPE > void FX::fillElms (TYPE * dst, const TYPE & src, unsigned long n) inline
Fill array of elements with given element.
Referenced by FX::FXArray< TYPE >::append(), FX::FXArray< TYPE >::assign(), FX::FXArray< TYPE >::FXArray(), FX::FXArray< TYPE >::insert(), and FX::FXArray< TYPE >::prepend().
clearElms()
template<class TYPE > void FX::clearElms (TYPE * dst, unsigned long n) inline
Zero out array of elements.
saveElms() [1/9]
template<class TYPE > void FX::saveElms (FXStream & store, const TYPE * ptr, unsigned long n) inline
Save some elements to persistent store.
loadElms() [1/9]
template<class TYPE > void FX::loadElms (FXStream & store, TYPE * ptr, unsigned long n) inline
Load some elements from persistent store.
allocElms()
template<class TYPE > FXint FX::allocElms (TYPE *& ptr, unsigned long n) inline
Allocate array of elements, uninitialized.
References fxmalloc().
Referenced by FX::FXArray< TYPE >::FXArray().
callocElms()
template<class TYPE > FXint FX::callocElms (TYPE *& ptr, unsigned long n) inline
Allocate array of elements, initialized with zero.
References fxcalloc().
dupElms()
template<class TYPE > FXint FX::dupElms (TYPE *& ptr, const TYPE * src, unsigned long n) inline
Allocate array of elements, initialized with bit-wise copy of src array.
References fxmemdup().
resizeElms()
template<class TYPE > FXint FX::resizeElms (TYPE *& ptr, unsigned long n) inline
Resize array of elements, without constructor or destructor.
References fxresize().
Referenced by FX::FXArray< TYPE >::no().
freeElms()
template<class TYPE > void FX::freeElms (TYPE *& ptr) inline
Free array of elements, without destruction.
References fxfree().
Referenced by FX::FXArray< TYPE >::clear(), and FX::FXArray< TYPE >::~FXArray().
constructElms() [2/9]
void FX::constructElms (FXuchar * , unsigned long) inline
constructElms() [3/9]
void FX::constructElms (FXchar * , unsigned long) inline
constructElms() [4/9]
void FX::constructElms (FXushort * , unsigned long) inline
constructElms() [5/9]
void FX::constructElms (FXshort * , unsigned long) inline
constructElms() [6/9]
void FX::constructElms (FXuint * , unsigned long) inline
constructElms() [7/9]
void FX::constructElms (FXint * , unsigned long) inline
constructElms() [8/9]
void FX::constructElms (FXfloat * , unsigned long) inline
constructElms() [9/9]
void FX::constructElms (FXdouble * , unsigned long) inline
destructElms() [2/9]
void FX::destructElms (FXuchar * , unsigned long) inline
destructElms() [3/9]
void FX::destructElms (FXchar * , unsigned long) inline
destructElms() [4/9]
void FX::destructElms (FXushort * , unsigned long) inline
destructElms() [5/9]
void FX::destructElms (FXshort * , unsigned long) inline
destructElms() [6/9]
void FX::destructElms (FXuint * , unsigned long) inline
destructElms() [7/9]
void FX::destructElms (FXint * , unsigned long) inline
destructElms() [8/9]
void FX::destructElms (FXfloat * , unsigned long) inline
destructElms() [9/9]
void FX::destructElms (FXdouble * , unsigned long) inline
copyElms() [2/10]
void FX::copyElms (FXuchar * dst, const FXuchar * src, unsigned long n) inline
copyElms() [3/10]
void FX::copyElms (FXchar * dst, const FXchar * src, unsigned long n) inline
copyElms() [4/10]
void FX::copyElms (FXushort * dst, const FXushort * src, unsigned long n) inline
copyElms() [5/10]
void FX::copyElms (FXshort * dst, const FXshort * src, unsigned long n) inline
copyElms() [6/10]
void FX::copyElms (FXuint * dst, const FXuint * src, unsigned long n) inline
copyElms() [7/10]
void FX::copyElms (FXint * dst, const FXint * src, unsigned long n) inline
copyElms() [8/10]
void FX::copyElms (FXfloat * dst, const FXfloat * src, unsigned long n) inline
copyElms() [9/10]
void FX::copyElms (FXdouble * dst, const FXdouble * src, unsigned long n) inline
copyElms() [10/10]
template<class TYPE > void FX::copyElms (TYPE ** dst, const TYPE ** src, unsigned long n) inline
moveElms() [2/10]
void FX::moveElms (FXuchar * dst, const FXuchar * src, unsigned long n) inline
moveElms() [3/10]
void FX::moveElms (FXchar * dst, const FXchar * src, unsigned long n) inline
moveElms() [4/10]
void FX::moveElms (FXushort * dst, const FXushort * src, unsigned long n) inline
moveElms() [5/10]
void FX::moveElms (FXshort * dst, const FXshort * src, unsigned long n) inline
moveElms() [6/10]
void FX::moveElms (FXuint * dst, const FXuint * src, unsigned long n) inline
moveElms() [7/10]
void FX::moveElms (FXint * dst, const FXint * src, unsigned long n) inline
moveElms() [8/10]
void FX::moveElms (FXfloat * dst, const FXfloat * src, unsigned long n) inline
moveElms() [9/10]
void FX::moveElms (FXdouble * dst, const FXdouble * src, unsigned long n) inline
moveElms() [10/10]
template<class TYPE > void FX::moveElms (TYPE ** dst, const TYPE ** src, unsigned long n) inline
fillElms() [2/3]
void FX::fillElms (FXuchar * dst, const FXuchar & src, unsigned long n) inline
fillElms() [3/3]
void FX::fillElms (FXchar * dst, const FXchar & src, unsigned long n) inline
saveElms() [2/9]
void FX::saveElms (FXStream & store, const FXuchar * ptr, unsigned long n) inline
References FX::FXStream::save().
saveElms() [3/9]
void FX::saveElms (FXStream & store, const FXchar * ptr, unsigned long n) inline
References FX::FXStream::save().
saveElms() [4/9]
void FX::saveElms (FXStream & store, const FXushort * ptr, unsigned long n) inline
References FX::FXStream::save().
saveElms() [5/9]
void FX::saveElms (FXStream & store, const FXshort * ptr, unsigned long n) inline
References FX::FXStream::save().
saveElms() [6/9]
void FX::saveElms (FXStream & store, const FXuint * ptr, unsigned long n) inline
References FX::FXStream::save().
saveElms() [7/9]
void FX::saveElms (FXStream & store, const FXint * ptr, unsigned long n) inline
References FX::FXStream::save().
saveElms() [8/9]
void FX::saveElms (FXStream & store, const FXfloat * ptr, unsigned long n) inline
References FX::FXStream::save().
saveElms() [9/9]
void FX::saveElms (FXStream & store, const FXdouble * ptr, unsigned long n) inline
References FX::FXStream::save().
loadElms() [2/9]
void FX::loadElms (FXStream & store, FXuchar * ptr, unsigned long n) inline
References FX::FXStream::load().
loadElms() [3/9]
void FX::loadElms (FXStream & store, FXchar * ptr, unsigned long n) inline
References FX::FXStream::load().
loadElms() [4/9]
void FX::loadElms (FXStream & store, FXushort * ptr, unsigned long n) inline
References FX::FXStream::load().
loadElms() [5/9]
void FX::loadElms (FXStream & store, FXshort * ptr, unsigned long n) inline
References FX::FXStream::load().
loadElms() [6/9]
void FX::loadElms (FXStream & store, FXuint * ptr, unsigned long n) inline
References FX::FXStream::load().
loadElms() [7/9]
void FX::loadElms (FXStream & store, FXint * ptr, unsigned long n) inline
References FX::FXStream::load().
loadElms() [8/9]
void FX::loadElms (FXStream & store, FXfloat * ptr, unsigned long n) inline
References FX::FXStream::load().
loadElms() [9/9]
void FX::loadElms (FXStream & store, FXdouble * ptr, unsigned long n) inline
References FX::FXStream::load().
overlap() [1/11]
bool FX::overlap (const FXExtentd & a, const FXExtentd & b)
unite() [1/4]
FXExtentd FX::unite (const FXExtentd & a, const FXExtentd & b)
intersect() [1/4]
FXExtentd FX::intersect (const FXExtentd & a, const FXExtentd & b)
operator<<() [2/22]
FXStream& FX::operator<< (FXStream & store, const FXExtentd & ext)
operator>>() [2/22]
FXStream& FX::operator>> (FXStream & store, FXExtentd & ext)
overlap() [2/11]
bool FX::overlap (const FXExtentf & a, const FXExtentf & b)
unite() [2/4]
FXExtentf FX::unite (const FXExtentf & a, const FXExtentf & b)
intersect() [2/4]
FXExtentf FX::intersect (const FXExtentf & a, const FXExtentf & b)
operator<<() [3/22]
FXStream& FX::operator<< (FXStream & store, const FXExtentf & ext)
operator>>() [3/22]
FXStream& FX::operator>> (FXStream & store, FXExtentf & ext)
fxcheckGIF()
bool FX::fxcheckGIF (FXStream & store)
Check if stream contains a GIF, return TRUE if so.
fxloadGIF()
bool FX::fxloadGIF (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an GIF (Graphics Interchange Format) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveGIF()
bool FX::fxsaveGIF (FXStream & store, const FXColor * data, FXint width, FXint height, bool fast = true)
Save an GIF (Graphics Interchange Format) file to a stream.
The flag "fast" is used to select the faster Floyd-Steinberg dither method instead of the slower Wu quantization algorithm.
glUseFXFont()
void FX::glUseFXFont (FXFont * font, int first, int count, int list)
Create a display list of bitmaps from font glyphs in a font.
fxcheckIFF()
bool FX::fxcheckIFF (FXStream & store)
Check if stream contains a IFF, return TRUE if so.
fxloadIFF()
bool FX::fxloadIFF (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an IFF (EA Image File Format) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxcheckJPG()
bool FX::fxcheckJPG (FXStream & store)
Check if stream contains a JPG, return TRUE if so.
fxloadJPG()
bool FX::fxloadJPG (FXStream & store, FXColor *& data, FXint & width, FXint & height, FXint & quality)
Load an JPEG (Joint Photographics Experts Group) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveJPG()
bool FX::fxsaveJPG (FXStream & store, const FXColor * data, FXint width, FXint height, FXint quality)
Save an JPEG (Joint Photographics Experts Group) file to a stream.
operator *() [1/24]
FXMat3d FX::operator * (FXdouble x, const FXMat3d & a)
operator *() [2/24]
FXMat3d FX::operator * (const FXMat3d & a, FXdouble x)
operator/() [1/24]
FXMat3d FX::operator/ (const FXMat3d & a, FXdouble x)
operator/() [2/24]
FXMat3d FX::operator/ (FXdouble x, const FXMat3d & a)
operator<<() [4/22]
FXStream& FX::operator<< (FXStream & store, const FXMat3d & m)
operator>>() [4/22]
FXStream& FX::operator>> (FXStream & store, FXMat3d & m)
operator *() [3/24]
FXMat3f FX::operator * (FXfloat x, const FXMat3f & a)
operator *() [4/24]
FXMat3f FX::operator * (const FXMat3f & a, FXfloat x)
operator/() [3/24]
FXMat3f FX::operator/ (const FXMat3f & a, FXfloat x)
operator/() [4/24]
FXMat3f FX::operator/ (FXfloat x, const FXMat3f & a)
operator<<() [5/22]
FXStream& FX::operator<< (FXStream & store, const FXMat3f & m)
operator>>() [5/22]
FXStream& FX::operator>> (FXStream & store, FXMat3f & m)
operator *() [5/24]
FXMat4d FX::operator * (FXdouble x, const FXMat4d & a)
operator *() [6/24]
FXMat4d FX::operator * (const FXMat4d & a, FXdouble x)
operator/() [5/24]
FXMat4d FX::operator/ (const FXMat4d & a, FXdouble x)
operator/() [6/24]
FXMat4d FX::operator/ (FXdouble x, const FXMat4d & a)
operator<<() [6/22]
FXStream& FX::operator<< (FXStream & store, const FXMat4d & m)
operator>>() [6/22]
FXStream& FX::operator>> (FXStream & store, FXMat4d & m)
operator *() [7/24]
FXMat4f FX::operator * (FXfloat x, const FXMat4f & a)
operator *() [8/24]
FXMat4f FX::operator * (const FXMat4f & a, FXfloat x)
operator/() [7/24]
FXMat4f FX::operator/ (const FXMat4f & a, FXfloat x)
operator/() [8/24]
FXMat4f FX::operator/ (FXfloat x, const FXMat4f & a)
operator<<() [7/22]
FXStream& FX::operator<< (FXStream & store, const FXMat4f & m)
operator>>() [7/22]
FXStream& FX::operator>> (FXStream & store, FXMat4f & m)
fxcheckPCX()
bool FX::fxcheckPCX (FXStream & store)
Check if stream contains a PCX, return TRUE if so.
fxloadPCX()
bool FX::fxloadPCX (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an PCX (PC Paintbrush) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsavePCX()
bool FX::fxsavePCX (FXStream & store, const FXColor * data, FXint width, FXint height)
Save an PCX (PC Paintbrush) file to a stream.
fxcheckPNG()
bool FX::fxcheckPNG (FXStream & store)
Check if stream contains a PNG, return TRUE if so.
fxloadPNG()
bool FX::fxloadPNG (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an PNG (Portable Network Graphics) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsavePNG()
bool FX::fxsavePNG (FXStream & store, const FXColor * data, FXint width, FXint height)
Save an PNG (Portable Network Graphics) file to a stream.
operator *() [9/24]
FXPoint FX::operator * (const FXPoint & p, FXshort c) inline
References FX::FXPoint::x, and FX::FXPoint::y.
operator *() [10/24]
FXPoint FX::operator * (FXshort c, const FXPoint & p) inline
References FX::FXPoint::x, and FX::FXPoint::y.
operator/() [9/24]
FXPoint FX::operator/ (const FXPoint & p, FXshort c) inline
References FX::FXPoint::x, and FX::FXPoint::y.
operator/() [10/24]
FXPoint FX::operator/ (FXshort c, const FXPoint & p) inline
References FX::FXPoint::x, and FX::FXPoint::y.
operator<<() [8/22]
FXStream& FX::operator<< (FXStream & store, const FXPoint & p)
operator>>() [8/22]
FXStream& FX::operator>> (FXStream & store, FXPoint & p)
fxcheckPPM()
bool FX::fxcheckPPM (FXStream & store)
Check if stream contains a PPM, return TRUE if so.
fxloadPPM()
bool FX::fxloadPPM (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an PPM (Portable Pixmap Format) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsavePPM()
bool FX::fxsavePPM (FXStream & store, const FXColor * data, FXint width, FXint height)
Save an PPM (Portable Pixmap Format) file to a stream.
overlap() [3/11]
bool FX::overlap (const FXRanged & a, const FXRanged & b)
unite() [3/4]
FXRanged FX::unite (const FXRanged & a, const FXRanged & b)
intersect() [3/4]
FXRanged FX::intersect (const FXRanged & a, const FXRanged & b)
operator<<() [9/22]
FXStream& FX::operator<< (FXStream & store, const FXRanged & bounds)
operator>>() [9/22]
FXStream& FX::operator>> (FXStream & store, FXRanged & bounds)
overlap() [4/11]
bool FX::overlap (const FXRangef & a, const FXRangef & b)
unite() [4/4]
FXRangef FX::unite (const FXRangef & a, const FXRangef & b)
intersect() [4/4]
FXRangef FX::intersect (const FXRangef & a, const FXRangef & b)
operator<<() [10/22]
FXStream& FX::operator<< (FXStream & store, const FXRangef & bounds)
operator>>() [10/22]
FXStream& FX::operator>> (FXStream & store, FXRangef & bounds)
fxcheckRAS()
bool FX::fxcheckRAS (FXStream & store)
Check if stream contains a RAS, return TRUE if so.
fxloadRAS()
bool FX::fxloadRAS (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an SUN Raster Image format file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveRAS()
bool FX::fxsaveRAS (FXStream & store, const FXColor * data, FXint width, FXint height)
Save an SUN Raster Image format file to a stream.
overlap() [5/11]
bool FX::overlap (const FXRectangle & a, const FXRectangle & b) inline
References FX::FXRectangle::h, FX::FXRectangle::w, FX::FXRectangle::x, and FX::FXRectangle::y.
operator<<() [11/22]
FXStream& FX::operator<< (FXStream & store, const FXRectangle & r)
operator>>() [11/22]
FXStream& FX::operator>> (FXStream & store, FXRectangle & r)
operator<<() [12/22]
FXStream& FX::operator<< (FXStream & store, const FXRex & s)
operator>>() [12/22]
FXStream& FX::operator>> (FXStream & store, FXRex & s)
fxcheckRGB()
bool FX::fxcheckRGB (FXStream & store)
Check if stream contains a RGB, return TRUE if so.
fxloadRGB()
bool FX::fxloadRGB (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an RGB (SGI IRIS RGB) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveRGB()
bool FX::fxsaveRGB (FXStream & store, const FXColor * data, FXint width, FXint height)
Save an RGB (SGI IRIS RGB) file to a stream.
operator *() [11/24]
FXSize FX::operator * (const FXSize & s, FXshort c) inline
References FX::FXSize::h, and FX::FXSize::w.
operator *() [12/24]
FXSize FX::operator * (FXshort c, const FXSize & s) inline
References FX::FXSize::h, and FX::FXSize::w.
operator/() [11/24]
FXSize FX::operator/ (const FXSize & s, FXshort c) inline
References FX::FXSize::h, and FX::FXSize::w.
operator/() [12/24]
FXSize FX::operator/ (FXshort c, const FXSize & s) inline
References FX::FXSize::h, and FX::FXSize::w.
operator<<() [13/22]
FXStream& FX::operator<< (FXStream & store, const FXSize & s)
operator>>() [13/22]
FXStream& FX::operator>> (FXStream & store, FXSize & s)
overlap() [6/11]
bool FX::overlap (const FXRanged & a, const FXSphered & b)
overlap() [7/11]
bool FX::overlap (const FXSphered & a, const FXRanged & b)
overlap() [8/11]
bool FX::overlap (const FXSphered & a, const FXSphered & b)
operator<<() [14/22]
FXStream& FX::operator<< (FXStream & store, const FXSphered & sphere)
operator>>() [14/22]
FXStream& FX::operator>> (FXStream & store, FXSphered & sphere)
overlap() [9/11]
bool FX::overlap (const FXRangef & a, const FXSpheref & b)
overlap() [10/11]
bool FX::overlap (const FXSpheref & a, const FXRangef & b)
overlap() [11/11]
bool FX::overlap (const FXSpheref & a, const FXSpheref & b)
operator<<() [15/22]
FXStream& FX::operator<< (FXStream & store, const FXSpheref & sphere)
operator>>() [15/22]
FXStream& FX::operator>> (FXStream & store, FXSpheref & sphere)
swap()
void FX::swap (FXString & a, FXString & b) inline
Referenced by FX::FXStream::swapBytes().
compare() [1/8]
FXint FX::compare (const FXchar * s1, const FXchar * s2)
compare() [2/8]
FXint FX::compare (const FXchar * s1, const FXString & s2)
compare() [3/8]
FXint FX::compare (const FXString & s1, const FXchar * s2)
compare() [4/8]
FXint FX::compare (const FXString & s1, const FXString & s2)
compare() [5/8]
FXint FX::compare (const FXchar * s1, const FXchar * s2, FXint n)
compare() [6/8]
FXint FX::compare (const FXchar * s1, const FXString & s2, FXint n)
compare() [7/8]
FXint FX::compare (const FXString & s1, const FXchar * s2, FXint n)
compare() [8/8]
FXint FX::compare (const FXString & s1, const FXString & s2, FXint n)
comparecase() [1/8]
FXint FX::comparecase (const FXchar * s1, const FXchar * s2)
comparecase() [2/8]
FXint FX::comparecase (const FXchar * s1, const FXString & s2)
comparecase() [3/8]
FXint FX::comparecase (const FXString & s1, const FXchar * s2)
comparecase() [4/8]
FXint FX::comparecase (const FXString & s1, const FXString & s2)
comparecase() [5/8]
FXint FX::comparecase (const FXchar * s1, const FXchar * s2, FXint n)
comparecase() [6/8]
FXint FX::comparecase (const FXchar * s1, const FXString & s2, FXint n)
comparecase() [7/8]
FXint FX::comparecase (const FXString & s1, const FXchar * s2, FXint n)
comparecase() [8/8]
FXint FX::comparecase (const FXString & s1, const FXString & s2, FXint n)
compareversion() [1/4]
FXint FX::compareversion (const FXchar * s1, const FXchar * s2)
compareversion() [2/4]
FXint FX::compareversion (const FXchar * s1, const FXString & s2)
compareversion() [3/4]
FXint FX::compareversion (const FXString & s1, const FXchar * s2)
compareversion() [4/4]
FXint FX::compareversion (const FXString & s1, const FXString & s2)
operator==() [1/15]
bool FX::operator== (const FXString & s1, const FXString & s2)
operator==() [2/15]
bool FX::operator== (const FXString & s1, const FXchar * s2)
operator==() [3/15]
bool FX::operator== (const FXchar * s1, const FXString & s2)
operator!=() [1/15]
bool FX::operator!= (const FXString & s1, const FXString & s2)
operator!=() [2/15]
bool FX::operator!= (const FXString & s1, const FXchar * s2)
operator!=() [3/15]
bool FX::operator!= (const FXchar * s1, const FXString & s2)
operator<() [1/15]
bool FX::operator< (const FXString & s1, const FXString & s2)
operator<() [2/15]
bool FX::operator< (const FXString & s1, const FXchar * s2)
operator<() [3/15]
bool FX::operator< (const FXchar * s1, const FXString & s2)
operator<=() [1/15]
bool FX::operator<= (const FXString & s1, const FXString & s2)
operator<=() [2/15]
bool FX::operator<= (const FXString & s1, const FXchar * s2)
operator<=() [3/15]
bool FX::operator<= (const FXchar * s1, const FXString & s2)
operator>() [1/15]
bool FX::operator> (const FXString & s1, const FXString & s2)
operator>() [2/15]
bool FX::operator> (const FXString & s1, const FXchar * s2)
operator>() [3/15]
bool FX::operator> (const FXchar * s1, const FXString & s2)
operator>=() [1/15]
bool FX::operator>= (const FXString & s1, const FXString & s2)
operator>=() [2/15]
bool FX::operator>= (const FXString & s1, const FXchar * s2)
operator>=() [3/15]
bool FX::operator>= (const FXchar * s1, const FXString & s2)
operator+() [3/11]
FXString FX::operator+ (const FXString & s1, const FXString & s2)
operator+() [4/11]
FXString FX::operator+ (const FXString & s1, const FXchar * s2)
operator+() [5/11]
FXString FX::operator+ (const FXString & s1, const FXwchar * s2)
operator+() [6/11]
FXString FX::operator+ (const FXString & s1, const FXnchar * s2)
operator+() [7/11]
FXString FX::operator+ (const FXchar * s1, const FXString & s2)
operator+() [8/11]
FXString FX::operator+ (const FXwchar * s1, const FXString & s2)
operator+() [9/11]
FXString FX::operator+ (const FXnchar * s1, const FXString & s2)
operator+() [10/11]
FXString FX::operator+ (const FXString & s, FXchar c)
operator+() [11/11]
FXString FX::operator+ (FXchar c, const FXString & s)
operator<<() [16/22]
FXStream& FX::operator<< (FXStream & store, const FXString & s)
operator>>() [16/22]
FXStream& FX::operator>> (FXStream & store, FXString & s)
FXStringFormat()
FXString FX::FXStringFormat (const FXchar * fmt, ...)
FXStringVFormat()
FXString FXString FX::FXStringVFormat (const FXchar * fmt, va_list args)
FXStringVal() [1/6]
FXString FX::FXStringVal (FXint num, FXint base = 10)
FXStringVal() [2/6]
FXString FX::FXStringVal (FXuint num, FXint base = 10)
FXStringVal() [3/6]
FXString FX::FXStringVal (FXlong num, FXint base = 10)
FXStringVal() [4/6]
FXString FX::FXStringVal (FXulong num, FXint base = 10)
FXStringVal() [5/6]
FXString FX::FXStringVal (FXfloat num, FXint prec = 6, FXint exp = MAYBE)
FXStringVal() [6/6]
FXString FX::FXStringVal (FXdouble num, FXint prec = 6, FXint exp = MAYBE)
FXIntVal()
FXint FX::FXIntVal (const FXString & s, FXint base = 10)
FXUIntVal()
FXuint FX::FXUIntVal (const FXString & s, FXint base = 10)
FXLongVal()
FXlong FX::FXLongVal (const FXString & s, FXint base = 10)
FXULongVal()
FXulong FX::FXULongVal (const FXString & s, FXint base = 10)
FXFloatVal()
FXfloat FX::FXFloatVal (const FXString & s)
FXDoubleVal()
FXdouble FX::FXDoubleVal (const FXString & s)
fromAscii()
FXString FX::fromAscii (const FXString & s)
toAscii()
FXString FX::toAscii (const FXString & s)
escape()
FXString FX::escape (const FXString & s)
unescape()
FXString FX::unescape (const FXString & s)
normalize() [1/7]
FXString FX::normalize (const FXString & s)
decompose()
FXString FX::decompose (const FXString & s, FXuint kind)
compose()
FXString FX::compose (const FXString & s, FXuint kind)
unixToDos()
FXString& FX::unixToDos (FXString & str)
dosToUnix()
FXString& FX::dosToUnix (FXString & str)
fxcheckTGA()
bool FX::fxcheckTGA (FXStream & store)
Check if stream contains a TARGA, return TRUE if so.
fxloadTGA()
bool FX::fxloadTGA (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an TARGA file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveTGA()
bool FX::fxsaveTGA (FXStream & store, const FXColor * data, FXint width, FXint height)
Save an TARGA file to a stream.
fxcheckTIF()
bool FX::fxcheckTIF (FXStream & store)
Check if stream contains a TIFF, return TRUE if so.
fxloadTIF()
bool FX::fxloadTIF (FXStream & store, FXColor *& data, FXint & width, FXint & height, FXushort & codec)
Load an TIFF (Tagged Image File Format) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveTIF()
bool FX::fxsaveTIF (FXStream & store, const FXColor * data, FXint width, FXint height, FXushort codec)
Save an TIFF (Tagged Image File Format) file to a stream.
operator *() [13/24]
FXVec2d FX::operator * (const FXVec2d & a, FXdouble n) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator *() [14/24]
FXVec2d FX::operator * (FXdouble n, const FXVec2d & a) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator/() [13/24]
FXVec2d FX::operator/ (const FXVec2d & a, FXdouble n) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator/() [14/24]
FXVec2d FX::operator/ (FXdouble n, const FXVec2d & a) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator==() [4/15]
bool FX::operator== (const FXVec2d & a, FXdouble n) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator!=() [4/15]
bool FX::operator!= (const FXVec2d & a, FXdouble n) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator==() [5/15]
bool FX::operator== (FXdouble n, const FXVec2d & a) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator!=() [5/15]
bool FX::operator!= (FXdouble n, const FXVec2d & a) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator<() [4/15]
bool FX::operator< (const FXVec2d & a, FXdouble n) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator<=() [4/15]
bool FX::operator<= (const FXVec2d & a, FXdouble n) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator>() [4/15]
bool FX::operator> (const FXVec2d & a, FXdouble n) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator>=() [4/15]
bool FX::operator>= (const FXVec2d & a, FXdouble n) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator<() [5/15]
bool FX::operator< (FXdouble n, const FXVec2d & a) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator<=() [5/15]
bool FX::operator<= (FXdouble n, const FXVec2d & a) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator>() [5/15]
bool FX::operator> (FXdouble n, const FXVec2d & a) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
operator>=() [5/15]
bool FX::operator>= (FXdouble n, const FXVec2d & a) inline
References FX::FXVec2d::x, and FX::FXVec2d::y.
lo() [1/6]
FXVec2d FX::lo (const FXVec2d & a, const FXVec2d & b) inline
References FXMIN, FX::FXVec2d::x, and FX::FXVec2d::y.
Referenced by FX::FXVec2d::clamp(), FX::FXVec2f::clamp(), FX::FXVec4d::clamp(), FX::FXVec4f::clamp(), FX::FXVec3d::clamp(), FX::FXVec3f::clamp(), FX::FXInputDialog::getLimits(), FX::FXDial::getRange(), FX::FXKnob::getRange(), FX::FXRealSlider::getRange(), FX::FXSlider::getRange(), FX::FXSpinner::getRange(), FX::FXRealSpinner::getRange(), FX::FXRangef::set(), FX::FXRanged::set(), and FX::FXInputDialog::setLimits().
hi() [1/6]
FXVec2d FX::hi (const FXVec2d & a, const FXVec2d & b) inline
References FXMAX, FX::FXVec2d::x, and FX::FXVec2d::y.
Referenced by FX::FXVec2d::clamp(), FX::FXVec2f::clamp(), FX::FXVec4d::clamp(), FX::FXVec4f::clamp(), FX::FXVec3d::clamp(), FX::FXVec3f::clamp(), FX::FXInputDialog::getLimits(), FX::FXDial::getRange(), FX::FXKnob::getRange(), FX::FXRealSlider::getRange(), FX::FXSlider::getRange(), FX::FXSpinner::getRange(), FX::FXRealSpinner::getRange(), FX::FXRangef::set(), FX::FXRanged::set(), and FX::FXInputDialog::setLimits().
normalize() [2/7]
FXVec2d FX::normalize (const FXVec2d & v)
operator<<() [17/22]
FXStream& FX::operator<< (FXStream & store, const FXVec2d & v)
operator>>() [17/22]
FXStream& FX::operator>> (FXStream & store, FXVec2d & v)
operator *() [15/24]
FXVec2f FX::operator * (const FXVec2f & a, FXfloat n) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator *() [16/24]
FXVec2f FX::operator * (FXfloat n, const FXVec2f & a) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator/() [15/24]
FXVec2f FX::operator/ (const FXVec2f & a, FXfloat n) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator/() [16/24]
FXVec2f FX::operator/ (FXfloat n, const FXVec2f & a) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator==() [6/15]
bool FX::operator== (const FXVec2f & a, FXfloat n) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator!=() [6/15]
bool FX::operator!= (const FXVec2f & a, FXfloat n) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator==() [7/15]
bool FX::operator== (FXfloat n, const FXVec2f & a) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator!=() [7/15]
bool FX::operator!= (FXfloat n, const FXVec2f & a) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator<() [6/15]
bool FX::operator< (const FXVec2f & a, FXfloat n) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator<=() [6/15]
bool FX::operator<= (const FXVec2f & a, FXfloat n) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator>() [6/15]
bool FX::operator> (const FXVec2f & a, FXfloat n) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator>=() [6/15]
bool FX::operator>= (const FXVec2f & a, FXfloat n) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator<() [7/15]
bool FX::operator< (FXfloat n, const FXVec2f & a) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator<=() [7/15]
bool FX::operator<= (FXfloat n, const FXVec2f & a) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator>() [7/15]
bool FX::operator> (FXfloat n, const FXVec2f & a) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
operator>=() [7/15]
bool FX::operator>= (FXfloat n, const FXVec2f & a) inline
References FX::FXVec2f::x, and FX::FXVec2f::y.
lo() [2/6]
FXVec2f FX::lo (const FXVec2f & a, const FXVec2f & b) inline
References FXMIN, FX::FXVec2f::x, and FX::FXVec2f::y.
hi() [2/6]
FXVec2f FX::hi (const FXVec2f & a, const FXVec2f & b) inline
References FXMAX, FX::FXVec2f::x, and FX::FXVec2f::y.
normalize() [3/7]
FXVec2f FX::normalize (const FXVec2f & v)
operator<<() [18/22]
FXStream& FX::operator<< (FXStream & store, const FXVec2f & v)
operator>>() [18/22]
FXStream& FX::operator>> (FXStream & store, FXVec2f & v)
operator *() [17/24]
FXVec3d FX::operator * (const FXVec3d & a, FXdouble n) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator *() [18/24]
FXVec3d FX::operator * (FXdouble n, const FXVec3d & a) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator/() [17/24]
FXVec3d FX::operator/ (const FXVec3d & a, FXdouble n) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator/() [18/24]
FXVec3d FX::operator/ (FXdouble n, const FXVec3d & a) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator==() [8/15]
bool FX::operator== (const FXVec3d & a, FXdouble n) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator!=() [8/15]
bool FX::operator!= (const FXVec3d & a, FXdouble n) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator==() [9/15]
bool FX::operator== (FXdouble n, const FXVec3d & a) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator!=() [9/15]
bool FX::operator!= (FXdouble n, const FXVec3d & a) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator<() [8/15]
bool FX::operator< (const FXVec3d & a, FXdouble n) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator<=() [8/15]
bool FX::operator<= (const FXVec3d & a, FXdouble n) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator>() [8/15]
bool FX::operator> (const FXVec3d & a, FXdouble n) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator>=() [8/15]
bool FX::operator>= (const FXVec3d & a, FXdouble n) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator<() [9/15]
bool FX::operator< (FXdouble n, const FXVec3d & a) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator<=() [9/15]
bool FX::operator<= (FXdouble n, const FXVec3d & a) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator>() [9/15]
bool FX::operator> (FXdouble n, const FXVec3d & a) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
operator>=() [9/15]
bool FX::operator>= (FXdouble n, const FXVec3d & a) inline
References FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
lo() [3/6]
FXVec3d FX::lo (const FXVec3d & a, const FXVec3d & b) inline
References FXMIN, FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
hi() [3/6]
FXVec3d FX::hi (const FXVec3d & a, const FXVec3d & b) inline
References FXMAX, FX::FXVec3d::x, FX::FXVec3d::y, and FX::FXVec3d::z.
normal() [1/4]
FXVec3d FX::normal (const FXVec3d & a, const FXVec3d & b, const FXVec3d & c)
Referenced by FX::FXStatusLine::getNormalText().
normal() [2/4]
FXVec3d FX::normal (const FXVec3d & a, const FXVec3d & b, const FXVec3d & c, const FXVec3d & d)
normalize() [4/7]
FXVec3d FX::normalize (const FXVec3d & v)
operator<<() [19/22]
FXStream& FX::operator<< (FXStream & store, const FXVec3d & v)
operator>>() [19/22]
FXStream& FX::operator>> (FXStream & store, FXVec3d & v)
operator *() [19/24]
FXVec3f FX::operator * (const FXVec3f & a, FXfloat n) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator *() [20/24]
FXVec3f FX::operator * (FXfloat n, const FXVec3f & a) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator/() [19/24]
FXVec3f FX::operator/ (const FXVec3f & a, FXfloat n) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator/() [20/24]
FXVec3f FX::operator/ (FXfloat n, const FXVec3f & a) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator==() [10/15]
bool FX::operator== (const FXVec3f & a, FXfloat n) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator!=() [10/15]
bool FX::operator!= (const FXVec3f & a, FXfloat n) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator==() [11/15]
bool FX::operator== (FXfloat n, const FXVec3f & a) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator!=() [11/15]
bool FX::operator!= (FXfloat n, const FXVec3f & a) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator<() [10/15]
bool FX::operator< (const FXVec3f & a, FXfloat n) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator<=() [10/15]
bool FX::operator<= (const FXVec3f & a, FXfloat n) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator>() [10/15]
bool FX::operator> (const FXVec3f & a, FXfloat n) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator>=() [10/15]
bool FX::operator>= (const FXVec3f & a, FXfloat n) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator<() [11/15]
bool FX::operator< (FXfloat n, const FXVec3f & a) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator<=() [11/15]
bool FX::operator<= (FXfloat n, const FXVec3f & a) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator>() [11/15]
bool FX::operator> (FXfloat n, const FXVec3f & a) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
operator>=() [11/15]
bool FX::operator>= (FXfloat n, const FXVec3f & a) inline
References FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
lo() [4/6]
FXVec3f FX::lo (const FXVec3f & a, const FXVec3f & b) inline
References FXMIN, FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
hi() [4/6]
FXVec3f FX::hi (const FXVec3f & a, const FXVec3f & b) inline
References FXMAX, FX::FXVec3f::x, FX::FXVec3f::y, and FX::FXVec3f::z.
normal() [3/4]
FXVec3f FX::normal (const FXVec3f & a, const FXVec3f & b, const FXVec3f & c)
normal() [4/4]
FXVec3f FX::normal (const FXVec3f & a, const FXVec3f & b, const FXVec3f & c, const FXVec3f & d)
normalize() [5/7]
FXVec3f FX::normalize (const FXVec3f & v)
operator<<() [20/22]
FXStream& FX::operator<< (FXStream & store, const FXVec3f & v)
operator>>() [20/22]
FXStream& FX::operator>> (FXStream & store, FXVec3f & v)
operator *() [21/24]
FXVec4d FX::operator * (const FXVec4d & a, FXdouble n) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator *() [22/24]
FXVec4d FX::operator * (FXdouble n, const FXVec4d & a) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator/() [21/24]
FXVec4d FX::operator/ (const FXVec4d & a, FXdouble n) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator/() [22/24]
FXVec4d FX::operator/ (FXdouble n, const FXVec4d & a) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator==() [12/15]
bool FX::operator== (const FXVec4d & a, FXdouble n) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator!=() [12/15]
bool FX::operator!= (const FXVec4d & a, FXdouble n) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator==() [13/15]
bool FX::operator== (FXdouble n, const FXVec4d & a) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator!=() [13/15]
bool FX::operator!= (FXdouble n, const FXVec4d & a) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator<() [12/15]
bool FX::operator< (const FXVec4d & a, FXdouble n) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator<=() [12/15]
bool FX::operator<= (const FXVec4d & a, FXdouble n) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator>() [12/15]
bool FX::operator> (const FXVec4d & a, FXdouble n) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator>=() [12/15]
bool FX::operator>= (const FXVec4d & a, FXdouble n) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator<() [13/15]
bool FX::operator< (FXdouble n, const FXVec4d & a) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator<=() [13/15]
bool FX::operator<= (FXdouble n, const FXVec4d & a) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator>() [13/15]
bool FX::operator> (FXdouble n, const FXVec4d & a) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
operator>=() [13/15]
bool FX::operator>= (FXdouble n, const FXVec4d & a) inline
References FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
lo() [5/6]
FXVec4d FX::lo (const FXVec4d & a, const FXVec4d & b) inline
References FXMIN, FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
hi() [5/6]
FXVec4d FX::hi (const FXVec4d & a, const FXVec4d & b) inline
References FXMAX, FX::FXVec4d::w, FX::FXVec4d::x, FX::FXVec4d::y, and FX::FXVec4d::z.
plane() [1/8]
FXVec4d FX::plane (const FXVec4d & vec)
plane() [2/8]
FXVec4d FX::plane (const FXVec3d & vec, FXdouble dist)
plane() [3/8]
FXVec4d FX::plane (const FXVec3d & vec, const FXVec3d & p)
plane() [4/8]
FXVec4d FX::plane (const FXVec3d & a, const FXVec3d & b, const FXVec3d & c)
normalize() [6/7]
FXVec4d FX::normalize (const FXVec4d & v)
operator<<() [21/22]
FXStream& FX::operator<< (FXStream & store, const FXVec4d & v)
operator>>() [21/22]
FXStream& FX::operator>> (FXStream & store, FXVec4d & v)
operator *() [23/24]
FXVec4f FX::operator * (const FXVec4f & a, FXfloat n) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator *() [24/24]
FXVec4f FX::operator * (FXfloat n, const FXVec4f & a) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator/() [23/24]
FXVec4f FX::operator/ (const FXVec4f & a, FXfloat n) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator/() [24/24]
FXVec4f FX::operator/ (FXfloat n, const FXVec4f & a) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator==() [14/15]
bool FX::operator== (const FXVec4f & a, FXfloat n) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator!=() [14/15]
bool FX::operator!= (const FXVec4f & a, FXfloat n) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator==() [15/15]
bool FX::operator== (FXfloat n, const FXVec4f & a) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator!=() [15/15]
bool FX::operator!= (FXfloat n, const FXVec4f & a) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator<() [14/15]
bool FX::operator< (const FXVec4f & a, FXfloat n) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator<=() [14/15]
bool FX::operator<= (const FXVec4f & a, FXfloat n) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator>() [14/15]
bool FX::operator> (const FXVec4f & a, FXfloat n) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator>=() [14/15]
bool FX::operator>= (const FXVec4f & a, FXfloat n) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator<() [15/15]
bool FX::operator< (FXfloat n, const FXVec4f & a) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator<=() [15/15]
bool FX::operator<= (FXfloat n, const FXVec4f & a) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator>() [15/15]
bool FX::operator> (FXfloat n, const FXVec4f & a) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
operator>=() [15/15]
bool FX::operator>= (FXfloat n, const FXVec4f & a) inline
References FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
lo() [6/6]
FXVec4f FX::lo (const FXVec4f & a, const FXVec4f & b) inline
References FXMIN, FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
hi() [6/6]
FXVec4f FX::hi (const FXVec4f & a, const FXVec4f & b) inline
References FXMAX, FX::FXVec4f::w, FX::FXVec4f::x, FX::FXVec4f::y, and FX::FXVec4f::z.
plane() [5/8]
FXVec4f FX::plane (const FXVec4f & vec)
plane() [6/8]
FXVec4f FX::plane (const FXVec3f & vec, FXfloat dist)
plane() [7/8]
FXVec4f FX::plane (const FXVec3f & vec, const FXVec3f & p)
plane() [8/8]
FXVec4f FX::plane (const FXVec3f & a, const FXVec3f & b, const FXVec3f & c)
normalize() [7/7]
FXVec4f FX::normalize (const FXVec4f & v)
operator<<() [22/22]
FXStream& FX::operator<< (FXStream & store, const FXVec4f & v)
operator>>() [22/22]
FXStream& FX::operator>> (FXStream & store, FXVec4f & v)
fxcheckXBM()
bool FX::fxcheckXBM (FXStream & store)
Check if stream contains a XBM, return TRUE if so.
fxloadXBM() [1/2]
bool FX::fxloadXBM (FXColor *& data, const FXuchar * pix, const FXuchar * msk, FXint width, FXint height)
Load an XBM (X Bitmap) from pixel array and mask array.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxloadXBM() [2/2]
bool FX::fxloadXBM (FXStream & store, FXColor *& data, FXint & width, FXint & height, FXint & hotx, FXint & hoty)
Load an XBM (X Bitmap) file from a stream.
Upon successful return, the pixel array and size, and hot-spot are returned. If an error occurred, the pixel array is set to NULL.
fxsaveXBM()
bool FX::fxsaveXBM (FXStream & store, const FXColor * data, FXint width, FXint height, FXint hotx = -1, FXint hoty = -1)
Save an XBM (X Bitmap) file to a stream; if the parameters hotx and hoty are set to -1, no hotspot location is saved.
fxsavePS()
bool FX::fxsavePS (FXStream & store, const FXColor * data, FXint width, FXint height, FXint paperw = 612, FXint paperh = 792, FXint margin = 35, bool color = true)
Save a PostScript file to a stream; format the picture to the maximal size that fits within the given margins of the indicated paper size.
fxcheckXPM()
bool FX::fxcheckXPM (FXStream & store)
Check if stream contains a XPM, return TRUE if so.
fxloadXPM() [1/2]
bool FX::fxloadXPM (const FXchar ** pix, FXColor *& data, FXint & width, FXint & height)
Load an XPM (X Pixmap) from array of strings.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxloadXPM() [2/2]
bool FX::fxloadXPM (FXStream & store, FXColor *& data, FXint & width, FXint & height)
Load an XPM (X Pixmap) file from a stream.
Upon successful return, the pixel array and size are returned. If an error occurred, the pixel array is set to NULL.
fxsaveXPM()
bool FX::fxsaveXPM (FXStream & store, const FXColor * data, FXint width, FXint height, bool fast = true)
Save an XPM (X Pixmap) file to a stream.
Variable Documentation
fxversion
const FXuchar FX::fxversion[3]
Version number that the library has been compiled with.
fxTraceLevel
unsigned int FX::fxTraceLevel
Controls tracing level.
Copyright © 1997-2005 Jeroen van der Zijp