fox-toolkit.org - Documentation
Main Page Class Hierarchy Alphabetical List Compound List File List Compound Members
FX::FXPath Namespace Reference
Functions
FXString root (const FXString &file)
FXString directory (const FXString &file)
FXString name (const FXString &file)
FXString title (const FXString &file)
FXString extension (const FXString &file)
FXString stripExtension (const FXString &file)
FXString drive (const FXString &file)
FXString expand (const FXString &file)
FXString contract (const FXString &file, const FXString &user=FXString::null, const FXString &var=FXString::null)
FXString simplify (const FXString &file)
FXString absolute (const FXString &file)
FXString absolute (const FXString &base, const FXString &file)
FXString relative (const FXString &file)
FXString relative (const FXString &base, const FXString &file)
FXString convert (const FXString &path)
FXString upLevel (const FXString &file)
bool isAbsolute (const FXString &file)
bool isTopDirectory (const FXString &file)
bool isShare (const FXString &file)
FXString enquote (const FXString &file, bool forcequotes=false)
FXString dequote (const FXString &file)
bool match (const FXString &pattern, const FXString &file, FXuint flags=(FILEMATCH_NOESCAPE|FILEMATCH_FILE_NAME))
FXString unique (const FXString &file)
FXString search (const FXString &pathlist, const FXString &file)
Function Documentation
root()
FXString FX::FXPath::root (const FXString & file)
Return root of absolute path; on Unix, this is just "/".
On Windows, this is "\\" or "C:\". Returns the empty string if the given path is not absolute.
Referenced by FX::FXApp::getRootWindow().
directory()
FXString FX::FXPath::directory (const FXString & file)
Return the directory part of the path name.
Note that directory("/bla/bla/") is "/bla/bla" and NOT "/bla". However, directory("/bla/bla") is "/bla" as we expect!
Referenced by FX::FXFileList::getDirectory().
name()
FXString FX::FXPath::name (const FXString & file)
Return name and extension part of the path name.
Note that name("/bla/bla/") is "" and NOT "bla". However, name("/bla/bla") is "bla" as we expect!
Referenced by FX::FXIconDict::find(), FX::FXIconDict::insert(), FX::FXIconDict::remove(), and FX::FXRecentFiles::setGroupName().
title()
FXString FX::FXPath::title (const FXString & file)
Return file title, i.e. document name only.
Referenced by FX::FXDocument::getTitle(), FX::FXMDIChild::getTitle(), and FX::FXTopWindow::getTitle().
extension()
FXString FX::FXPath::extension (const FXString & file)
Return extension part of the file name.
stripExtension()
FXString FX::FXPath::stripExtension (const FXString & file)
Return file name less the extension.
drive()
FXString FX::FXPath::drive (const FXString & file)
Return the drive letter prefixing this file name (if any).
expand()
FXString FX::FXPath::expand (const FXString & file)
Perform tilde or environment variable expansion.
contract()
FXString FX::FXPath::contract (const FXString & file, const FXString & user = FXString::null, const FXString & var = FXString::null)
Contract path based on user name and environment variable.
simplify()
FXString FX::FXPath::simplify (const FXString & file)
Simplify a file path; the path will remain relative if it was relative, or absolute if it was absolute.
Also, a trailing "/" will be preserved as this is important in other functions. For example, simplify("..//aaa/./bbb//../c/") becomes "../aaa/c/".
absolute() [1/2]
FXString FX::FXPath::absolute (const FXString & file)
Return absolute path from current directory and file name.
absolute() [2/2]
FXString FX::FXPath::absolute (const FXString & base, const FXString & file)
Return absolute path from base directory and file name.
relative() [1/2]
FXString FX::FXPath::relative (const FXString & file)
Return relative path of file to the current directory.
relative() [2/2]
FXString FX::FXPath::relative (const FXString & base, const FXString & file)
Return relative path of file to given base directory.
convert()
FXString FX::FXPath::convert (const FXString & path)
Return path following local path separator conventions.
upLevel()
FXString FX::FXPath::upLevel (const FXString & file)
Return path to directory above input directory name.
isAbsolute()
bool FX::FXPath::isAbsolute (const FXString & file)
Return true if file name is absolute.
isTopDirectory()
bool FX::FXPath::isTopDirectory (const FXString & file)
Return true if input directory is a top-level directory.
isShare()
bool FX::FXPath::isShare (const FXString & file)
Return true if input path is a file share.
enquote()
FXString FX::FXPath::enquote (const FXString & file, bool forcequotes = false)
Enquote filename to make safe for shell.
dequote()
FXString FX::FXPath::dequote (const FXString & file)
Dequote filename to get original again.
match()
bool FX::FXPath::match (const FXString & pattern, const FXString & file, FXuint flags = (FILEMATCH_NOESCAPE|FILEMATCH_FILE_NAME))
Perform wildcard match of a filename against a wildcard pattern.
The wildcard pattern may comprise ordinary characters or special matching characters, as given below:
? Any single character.
Zero or more of any character. [abc] Any character from the set {a,b,c}. [^abc] Any character BUT the ones from the set {a,b,c}. [!abc] Ditto. [a-zA-Z] Matches single character, which must be one of a-z or A-Z. [^a-zA-Z] Matches single character, which must be anything other than a-z or A-Z. [!a-zA-Z] Ditto. pat1|pat2 Match sub-pattern pat1 or pat2. pat1,pat2 Ditto. (pat1|pat2) Match sub-pattern pat1 or pat2; patterns may be nested. (pat1,pat2) Ditto.
The special characters may be escaped to treat them as ordinary characters. Matching may be influenced by a number of flags:
FILEMATCH_FILE_NAME No wildcard can ever match / FILEMATCH_NOESCAPE Backslashes don't quote special chars FILEMATCH_PERIOD Leading . is matched only explicitly FILEMATCH_LEADING_DIR Ignore /... after a match FILEMATCH_CASEFOLD Compare without regard to case
unique()
FXString FX::FXPath::unique (const FXString & file)
Generate unique filename of the form pathnameXXX.ext, where pathname.ext is the original input file, and XXX is a number, possibly empty, that makes the file unique.
search()
FXString FX::FXPath::search (const FXString & pathlist, const FXString & file)
Search path list for this file, return full path name for first occurrence.
Copyright © 1997-2005 Jeroen van der Zijp