#!/usr/bin/env sh

printf "Killing 'jackd'...\n" >> "$LOGDIR"/.xlogout
killall jackd >> "$LOGDIR"/.xlogout 2>&1
printf "Killing 'Xorg'...\n" >> "$LOGDIR"/.xlogout
killall Xorg >> "$LOGDIR"/.xlogout 2>&1
