#!/usr/bin/env sh

sxhkd > $LOGDIR/sxhkd_log 2>&1 &                    # Bind keys
unclutter > $LOGDIR/unclutter_log 2>&1 &            # Remove mouse when idle
xcompmgr > $LOGDIR/xcompmgr_log 2>&1 &              # xcompmgr for transparency
