#!/usr/bin/env sh

prf_chk ()
{
	#$1==Command
	#$2==Logfile
	#$3==CommandName
	if [ -n "$(command -v "$3")" ] ; then
		printf "Running '%s'...\\n" "$1" >> "$LOGDIR"/xinit
		$1 > "$LOGDIR"/"$2" 2>&1 &
	else
		printf "'%s' not found on system.\\n" "$3" >> "$LOGDIR"/xinit
	fi
}

prf_chk "sxhkd" "sxhkd" "sxhkd" # Bind extra keys
prf_chk "unclutter" "unclutter" "unclutter" # Remove mouse when idle
prf_chk "xcompmgr" "xcompmgr" "xcompmgr" # Transparency
prf_chk "ibus-daemon -drx" "ibus-daemon" "ibus-daemon"

printf "Starting X...\\n" >> "$LOGDIR"/xinit

unset prf_chk
