#!/usr/bin/env sh

export QT_IM_MODULE=ibus

sxhkd > $LOGDIR/sxhkd 2>&1 &                    # Bind keys
unclutter > $LOGDIR/unclutter 2>&1 &            # Remove mouse when idle
xcompmgr > $LOGDIR/xcompmgr 2>&1 &              # xcompmgr for transparency
#tint2 &
ibus-daemon -drx &
