#!/bin/sh

# Get the type of the file
# Meaning get all the text after the first '.'
# Also known as the complement as fname
while [ ! -z "$1" ]; do
    if [ "$(echo "$1" | grep -c "\.")" -gt 0 ]; then
        # I do a double reverse because I'm too
        # lazy to do awk or sed
        echo "$1" | rev | cut -f 1 -d "." | rev
    else
        echo ""
    fi
    shift 1
done
