#!/bin/sh

# Status bar module for disk space
# $1 should be drive mountpoint
echo "CURRENTLY BROKEN"
exit
[ -z "$1" ] && exit
if "$( find "/dev" | grep "$1" | wc -l >"/dev/null" )" ; then
    printf "YAY\n"
fi
RT=""
MULTIPRT=1
case $1 in
    /dev/sd[a-z]|sd[a-z])
        MULTIPRT=0
        ;;
    /dev/sd[a-z][0-9]|sd[a-z][0-9])

        ;;
    *)
        printf "I DON'T GET IT"
        exit
        ;;
esac
